// Code generated by ent, DO NOT EDIT.

package feedbackrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/formbricks/hub/internal/ent/predicate"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldID, id))
}

// CollectedAt applies equality check predicate on the "collected_at" field. It's identical to CollectedAtEQ.
func CollectedAt(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldCollectedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldTenantID, v))
}

// ResponseID applies equality check predicate on the "response_id" field. It's identical to ResponseIDEQ.
func ResponseID(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldResponseID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSourceID, v))
}

// SourceName applies equality check predicate on the "source_name" field. It's identical to SourceNameEQ.
func SourceName(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSourceName, v))
}

// FieldLabel applies equality check predicate on the "field_label" field. It's identical to FieldLabelEQ.
func FieldLabel(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldFieldLabel, v))
}

// FieldType applies equality check predicate on the "field_type" field. It's identical to FieldTypeEQ.
func FieldType(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldFieldType, v))
}

// ValueText applies equality check predicate on the "value_text" field. It's identical to ValueTextEQ.
func ValueText(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueText, v))
}

// ValueNumber applies equality check predicate on the "value_number" field. It's identical to ValueNumberEQ.
func ValueNumber(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueNumber, v))
}

// ValueBoolean applies equality check predicate on the "value_boolean" field. It's identical to ValueBooleanEQ.
func ValueBoolean(v bool) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueBoolean, v))
}

// ValueDate applies equality check predicate on the "value_date" field. It's identical to ValueDateEQ.
func ValueDate(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueDate, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldLanguage, v))
}

// Sentiment applies equality check predicate on the "sentiment" field. It's identical to SentimentEQ.
func Sentiment(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSentiment, v))
}

// SentimentScore applies equality check predicate on the "sentiment_score" field. It's identical to SentimentScoreEQ.
func SentimentScore(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSentimentScore, v))
}

// Emotion applies equality check predicate on the "emotion" field. It's identical to EmotionEQ.
func Emotion(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldEmotion, v))
}

// UserIdentifier applies equality check predicate on the "user_identifier" field. It's identical to UserIdentifierEQ.
func UserIdentifier(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldUserIdentifier, v))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingModel applies equality check predicate on the "embedding_model" field. It's identical to EmbeddingModelEQ.
func EmbeddingModel(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldEmbeddingModel, v))
}

// CollectedAtEQ applies the EQ predicate on the "collected_at" field.
func CollectedAtEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldCollectedAt, v))
}

// CollectedAtNEQ applies the NEQ predicate on the "collected_at" field.
func CollectedAtNEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldCollectedAt, v))
}

// CollectedAtIn applies the In predicate on the "collected_at" field.
func CollectedAtIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldCollectedAt, vs...))
}

// CollectedAtNotIn applies the NotIn predicate on the "collected_at" field.
func CollectedAtNotIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldCollectedAt, vs...))
}

// CollectedAtGT applies the GT predicate on the "collected_at" field.
func CollectedAtGT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldCollectedAt, v))
}

// CollectedAtGTE applies the GTE predicate on the "collected_at" field.
func CollectedAtGTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldCollectedAt, v))
}

// CollectedAtLT applies the LT predicate on the "collected_at" field.
func CollectedAtLT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldCollectedAt, v))
}

// CollectedAtLTE applies the LTE predicate on the "collected_at" field.
func CollectedAtLTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldCollectedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldTenantID))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldTenantID, v))
}

// ResponseIDEQ applies the EQ predicate on the "response_id" field.
func ResponseIDEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldResponseID, v))
}

// ResponseIDNEQ applies the NEQ predicate on the "response_id" field.
func ResponseIDNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldResponseID, v))
}

// ResponseIDIn applies the In predicate on the "response_id" field.
func ResponseIDIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldResponseID, vs...))
}

// ResponseIDNotIn applies the NotIn predicate on the "response_id" field.
func ResponseIDNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldResponseID, vs...))
}

// ResponseIDGT applies the GT predicate on the "response_id" field.
func ResponseIDGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldResponseID, v))
}

// ResponseIDGTE applies the GTE predicate on the "response_id" field.
func ResponseIDGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldResponseID, v))
}

// ResponseIDLT applies the LT predicate on the "response_id" field.
func ResponseIDLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldResponseID, v))
}

// ResponseIDLTE applies the LTE predicate on the "response_id" field.
func ResponseIDLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldResponseID, v))
}

// ResponseIDContains applies the Contains predicate on the "response_id" field.
func ResponseIDContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldResponseID, v))
}

// ResponseIDHasPrefix applies the HasPrefix predicate on the "response_id" field.
func ResponseIDHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldResponseID, v))
}

// ResponseIDHasSuffix applies the HasSuffix predicate on the "response_id" field.
func ResponseIDHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldResponseID, v))
}

// ResponseIDIsNil applies the IsNil predicate on the "response_id" field.
func ResponseIDIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldResponseID))
}

// ResponseIDNotNil applies the NotNil predicate on the "response_id" field.
func ResponseIDNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldResponseID))
}

// ResponseIDEqualFold applies the EqualFold predicate on the "response_id" field.
func ResponseIDEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldResponseID, v))
}

// ResponseIDContainsFold applies the ContainsFold predicate on the "response_id" field.
func ResponseIDContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldResponseID, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldSourceID))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldSourceID, v))
}

// SourceNameEQ applies the EQ predicate on the "source_name" field.
func SourceNameEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSourceName, v))
}

// SourceNameNEQ applies the NEQ predicate on the "source_name" field.
func SourceNameNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldSourceName, v))
}

// SourceNameIn applies the In predicate on the "source_name" field.
func SourceNameIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldSourceName, vs...))
}

// SourceNameNotIn applies the NotIn predicate on the "source_name" field.
func SourceNameNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldSourceName, vs...))
}

// SourceNameGT applies the GT predicate on the "source_name" field.
func SourceNameGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldSourceName, v))
}

// SourceNameGTE applies the GTE predicate on the "source_name" field.
func SourceNameGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldSourceName, v))
}

// SourceNameLT applies the LT predicate on the "source_name" field.
func SourceNameLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldSourceName, v))
}

// SourceNameLTE applies the LTE predicate on the "source_name" field.
func SourceNameLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldSourceName, v))
}

// SourceNameContains applies the Contains predicate on the "source_name" field.
func SourceNameContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldSourceName, v))
}

// SourceNameHasPrefix applies the HasPrefix predicate on the "source_name" field.
func SourceNameHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldSourceName, v))
}

// SourceNameHasSuffix applies the HasSuffix predicate on the "source_name" field.
func SourceNameHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldSourceName, v))
}

// SourceNameIsNil applies the IsNil predicate on the "source_name" field.
func SourceNameIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldSourceName))
}

// SourceNameNotNil applies the NotNil predicate on the "source_name" field.
func SourceNameNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldSourceName))
}

// SourceNameEqualFold applies the EqualFold predicate on the "source_name" field.
func SourceNameEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldSourceName, v))
}

// SourceNameContainsFold applies the ContainsFold predicate on the "source_name" field.
func SourceNameContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldSourceName, v))
}

// FieldIDEQ applies the EQ predicate on the "field_id" field.
func FieldIDEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldFieldID, v))
}

// FieldIDNEQ applies the NEQ predicate on the "field_id" field.
func FieldIDNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldFieldID, v))
}

// FieldIDIn applies the In predicate on the "field_id" field.
func FieldIDIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldFieldID, vs...))
}

// FieldIDNotIn applies the NotIn predicate on the "field_id" field.
func FieldIDNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldFieldID, vs...))
}

// FieldIDGT applies the GT predicate on the "field_id" field.
func FieldIDGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldFieldID, v))
}

// FieldIDGTE applies the GTE predicate on the "field_id" field.
func FieldIDGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldFieldID, v))
}

// FieldIDLT applies the LT predicate on the "field_id" field.
func FieldIDLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldFieldID, v))
}

// FieldIDLTE applies the LTE predicate on the "field_id" field.
func FieldIDLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldFieldID, v))
}

// FieldIDContains applies the Contains predicate on the "field_id" field.
func FieldIDContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldFieldID, v))
}

// FieldIDHasPrefix applies the HasPrefix predicate on the "field_id" field.
func FieldIDHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldFieldID, v))
}

// FieldIDHasSuffix applies the HasSuffix predicate on the "field_id" field.
func FieldIDHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldFieldID, v))
}

// FieldIDEqualFold applies the EqualFold predicate on the "field_id" field.
func FieldIDEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldFieldID, v))
}

// FieldIDContainsFold applies the ContainsFold predicate on the "field_id" field.
func FieldIDContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldFieldID, v))
}

// FieldLabelEQ applies the EQ predicate on the "field_label" field.
func FieldLabelEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldFieldLabel, v))
}

// FieldLabelNEQ applies the NEQ predicate on the "field_label" field.
func FieldLabelNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldFieldLabel, v))
}

// FieldLabelIn applies the In predicate on the "field_label" field.
func FieldLabelIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldFieldLabel, vs...))
}

// FieldLabelNotIn applies the NotIn predicate on the "field_label" field.
func FieldLabelNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldFieldLabel, vs...))
}

// FieldLabelGT applies the GT predicate on the "field_label" field.
func FieldLabelGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldFieldLabel, v))
}

// FieldLabelGTE applies the GTE predicate on the "field_label" field.
func FieldLabelGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldFieldLabel, v))
}

// FieldLabelLT applies the LT predicate on the "field_label" field.
func FieldLabelLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldFieldLabel, v))
}

// FieldLabelLTE applies the LTE predicate on the "field_label" field.
func FieldLabelLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldFieldLabel, v))
}

// FieldLabelContains applies the Contains predicate on the "field_label" field.
func FieldLabelContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldFieldLabel, v))
}

// FieldLabelHasPrefix applies the HasPrefix predicate on the "field_label" field.
func FieldLabelHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldFieldLabel, v))
}

// FieldLabelHasSuffix applies the HasSuffix predicate on the "field_label" field.
func FieldLabelHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldFieldLabel, v))
}

// FieldLabelIsNil applies the IsNil predicate on the "field_label" field.
func FieldLabelIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldFieldLabel))
}

// FieldLabelNotNil applies the NotNil predicate on the "field_label" field.
func FieldLabelNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldFieldLabel))
}

// FieldLabelEqualFold applies the EqualFold predicate on the "field_label" field.
func FieldLabelEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldFieldLabel, v))
}

// FieldLabelContainsFold applies the ContainsFold predicate on the "field_label" field.
func FieldLabelContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldFieldLabel, v))
}

// FieldTypeEQ applies the EQ predicate on the "field_type" field.
func FieldTypeEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldFieldType, v))
}

// FieldTypeNEQ applies the NEQ predicate on the "field_type" field.
func FieldTypeNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldFieldType, v))
}

// FieldTypeIn applies the In predicate on the "field_type" field.
func FieldTypeIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldFieldType, vs...))
}

// FieldTypeNotIn applies the NotIn predicate on the "field_type" field.
func FieldTypeNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldFieldType, vs...))
}

// FieldTypeGT applies the GT predicate on the "field_type" field.
func FieldTypeGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldFieldType, v))
}

// FieldTypeGTE applies the GTE predicate on the "field_type" field.
func FieldTypeGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldFieldType, v))
}

// FieldTypeLT applies the LT predicate on the "field_type" field.
func FieldTypeLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldFieldType, v))
}

// FieldTypeLTE applies the LTE predicate on the "field_type" field.
func FieldTypeLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldFieldType, v))
}

// FieldTypeContains applies the Contains predicate on the "field_type" field.
func FieldTypeContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldFieldType, v))
}

// FieldTypeHasPrefix applies the HasPrefix predicate on the "field_type" field.
func FieldTypeHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldFieldType, v))
}

// FieldTypeHasSuffix applies the HasSuffix predicate on the "field_type" field.
func FieldTypeHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldFieldType, v))
}

// FieldTypeEqualFold applies the EqualFold predicate on the "field_type" field.
func FieldTypeEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldFieldType, v))
}

// FieldTypeContainsFold applies the ContainsFold predicate on the "field_type" field.
func FieldTypeContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldFieldType, v))
}

// ValueTextEQ applies the EQ predicate on the "value_text" field.
func ValueTextEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueText, v))
}

// ValueTextNEQ applies the NEQ predicate on the "value_text" field.
func ValueTextNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldValueText, v))
}

// ValueTextIn applies the In predicate on the "value_text" field.
func ValueTextIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldValueText, vs...))
}

// ValueTextNotIn applies the NotIn predicate on the "value_text" field.
func ValueTextNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldValueText, vs...))
}

// ValueTextGT applies the GT predicate on the "value_text" field.
func ValueTextGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldValueText, v))
}

// ValueTextGTE applies the GTE predicate on the "value_text" field.
func ValueTextGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldValueText, v))
}

// ValueTextLT applies the LT predicate on the "value_text" field.
func ValueTextLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldValueText, v))
}

// ValueTextLTE applies the LTE predicate on the "value_text" field.
func ValueTextLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldValueText, v))
}

// ValueTextContains applies the Contains predicate on the "value_text" field.
func ValueTextContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldValueText, v))
}

// ValueTextHasPrefix applies the HasPrefix predicate on the "value_text" field.
func ValueTextHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldValueText, v))
}

// ValueTextHasSuffix applies the HasSuffix predicate on the "value_text" field.
func ValueTextHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldValueText, v))
}

// ValueTextIsNil applies the IsNil predicate on the "value_text" field.
func ValueTextIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldValueText))
}

// ValueTextNotNil applies the NotNil predicate on the "value_text" field.
func ValueTextNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldValueText))
}

// ValueTextEqualFold applies the EqualFold predicate on the "value_text" field.
func ValueTextEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldValueText, v))
}

// ValueTextContainsFold applies the ContainsFold predicate on the "value_text" field.
func ValueTextContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldValueText, v))
}

// ValueNumberEQ applies the EQ predicate on the "value_number" field.
func ValueNumberEQ(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueNumber, v))
}

// ValueNumberNEQ applies the NEQ predicate on the "value_number" field.
func ValueNumberNEQ(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldValueNumber, v))
}

// ValueNumberIn applies the In predicate on the "value_number" field.
func ValueNumberIn(vs ...float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldValueNumber, vs...))
}

// ValueNumberNotIn applies the NotIn predicate on the "value_number" field.
func ValueNumberNotIn(vs ...float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldValueNumber, vs...))
}

// ValueNumberGT applies the GT predicate on the "value_number" field.
func ValueNumberGT(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldValueNumber, v))
}

// ValueNumberGTE applies the GTE predicate on the "value_number" field.
func ValueNumberGTE(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldValueNumber, v))
}

// ValueNumberLT applies the LT predicate on the "value_number" field.
func ValueNumberLT(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldValueNumber, v))
}

// ValueNumberLTE applies the LTE predicate on the "value_number" field.
func ValueNumberLTE(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldValueNumber, v))
}

// ValueNumberIsNil applies the IsNil predicate on the "value_number" field.
func ValueNumberIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldValueNumber))
}

// ValueNumberNotNil applies the NotNil predicate on the "value_number" field.
func ValueNumberNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldValueNumber))
}

// ValueBooleanEQ applies the EQ predicate on the "value_boolean" field.
func ValueBooleanEQ(v bool) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueBoolean, v))
}

// ValueBooleanNEQ applies the NEQ predicate on the "value_boolean" field.
func ValueBooleanNEQ(v bool) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldValueBoolean, v))
}

// ValueBooleanIsNil applies the IsNil predicate on the "value_boolean" field.
func ValueBooleanIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldValueBoolean))
}

// ValueBooleanNotNil applies the NotNil predicate on the "value_boolean" field.
func ValueBooleanNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldValueBoolean))
}

// ValueDateEQ applies the EQ predicate on the "value_date" field.
func ValueDateEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldValueDate, v))
}

// ValueDateNEQ applies the NEQ predicate on the "value_date" field.
func ValueDateNEQ(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldValueDate, v))
}

// ValueDateIn applies the In predicate on the "value_date" field.
func ValueDateIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldValueDate, vs...))
}

// ValueDateNotIn applies the NotIn predicate on the "value_date" field.
func ValueDateNotIn(vs ...time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldValueDate, vs...))
}

// ValueDateGT applies the GT predicate on the "value_date" field.
func ValueDateGT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldValueDate, v))
}

// ValueDateGTE applies the GTE predicate on the "value_date" field.
func ValueDateGTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldValueDate, v))
}

// ValueDateLT applies the LT predicate on the "value_date" field.
func ValueDateLT(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldValueDate, v))
}

// ValueDateLTE applies the LTE predicate on the "value_date" field.
func ValueDateLTE(v time.Time) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldValueDate, v))
}

// ValueDateIsNil applies the IsNil predicate on the "value_date" field.
func ValueDateIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldValueDate))
}

// ValueDateNotNil applies the NotNil predicate on the "value_date" field.
func ValueDateNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldValueDate))
}

// ValueJSONIsNil applies the IsNil predicate on the "value_json" field.
func ValueJSONIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldValueJSON))
}

// ValueJSONNotNil applies the NotNil predicate on the "value_json" field.
func ValueJSONNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldValueJSON))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldMetadata))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldLanguage, v))
}

// SentimentEQ applies the EQ predicate on the "sentiment" field.
func SentimentEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSentiment, v))
}

// SentimentNEQ applies the NEQ predicate on the "sentiment" field.
func SentimentNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldSentiment, v))
}

// SentimentIn applies the In predicate on the "sentiment" field.
func SentimentIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldSentiment, vs...))
}

// SentimentNotIn applies the NotIn predicate on the "sentiment" field.
func SentimentNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldSentiment, vs...))
}

// SentimentGT applies the GT predicate on the "sentiment" field.
func SentimentGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldSentiment, v))
}

// SentimentGTE applies the GTE predicate on the "sentiment" field.
func SentimentGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldSentiment, v))
}

// SentimentLT applies the LT predicate on the "sentiment" field.
func SentimentLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldSentiment, v))
}

// SentimentLTE applies the LTE predicate on the "sentiment" field.
func SentimentLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldSentiment, v))
}

// SentimentContains applies the Contains predicate on the "sentiment" field.
func SentimentContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldSentiment, v))
}

// SentimentHasPrefix applies the HasPrefix predicate on the "sentiment" field.
func SentimentHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldSentiment, v))
}

// SentimentHasSuffix applies the HasSuffix predicate on the "sentiment" field.
func SentimentHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldSentiment, v))
}

// SentimentIsNil applies the IsNil predicate on the "sentiment" field.
func SentimentIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldSentiment))
}

// SentimentNotNil applies the NotNil predicate on the "sentiment" field.
func SentimentNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldSentiment))
}

// SentimentEqualFold applies the EqualFold predicate on the "sentiment" field.
func SentimentEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldSentiment, v))
}

// SentimentContainsFold applies the ContainsFold predicate on the "sentiment" field.
func SentimentContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldSentiment, v))
}

// SentimentScoreEQ applies the EQ predicate on the "sentiment_score" field.
func SentimentScoreEQ(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldSentimentScore, v))
}

// SentimentScoreNEQ applies the NEQ predicate on the "sentiment_score" field.
func SentimentScoreNEQ(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldSentimentScore, v))
}

// SentimentScoreIn applies the In predicate on the "sentiment_score" field.
func SentimentScoreIn(vs ...float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldSentimentScore, vs...))
}

// SentimentScoreNotIn applies the NotIn predicate on the "sentiment_score" field.
func SentimentScoreNotIn(vs ...float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldSentimentScore, vs...))
}

// SentimentScoreGT applies the GT predicate on the "sentiment_score" field.
func SentimentScoreGT(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldSentimentScore, v))
}

// SentimentScoreGTE applies the GTE predicate on the "sentiment_score" field.
func SentimentScoreGTE(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldSentimentScore, v))
}

// SentimentScoreLT applies the LT predicate on the "sentiment_score" field.
func SentimentScoreLT(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldSentimentScore, v))
}

// SentimentScoreLTE applies the LTE predicate on the "sentiment_score" field.
func SentimentScoreLTE(v float64) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldSentimentScore, v))
}

// SentimentScoreIsNil applies the IsNil predicate on the "sentiment_score" field.
func SentimentScoreIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldSentimentScore))
}

// SentimentScoreNotNil applies the NotNil predicate on the "sentiment_score" field.
func SentimentScoreNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldSentimentScore))
}

// EmotionEQ applies the EQ predicate on the "emotion" field.
func EmotionEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldEmotion, v))
}

// EmotionNEQ applies the NEQ predicate on the "emotion" field.
func EmotionNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldEmotion, v))
}

// EmotionIn applies the In predicate on the "emotion" field.
func EmotionIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldEmotion, vs...))
}

// EmotionNotIn applies the NotIn predicate on the "emotion" field.
func EmotionNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldEmotion, vs...))
}

// EmotionGT applies the GT predicate on the "emotion" field.
func EmotionGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldEmotion, v))
}

// EmotionGTE applies the GTE predicate on the "emotion" field.
func EmotionGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldEmotion, v))
}

// EmotionLT applies the LT predicate on the "emotion" field.
func EmotionLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldEmotion, v))
}

// EmotionLTE applies the LTE predicate on the "emotion" field.
func EmotionLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldEmotion, v))
}

// EmotionContains applies the Contains predicate on the "emotion" field.
func EmotionContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldEmotion, v))
}

// EmotionHasPrefix applies the HasPrefix predicate on the "emotion" field.
func EmotionHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldEmotion, v))
}

// EmotionHasSuffix applies the HasSuffix predicate on the "emotion" field.
func EmotionHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldEmotion, v))
}

// EmotionIsNil applies the IsNil predicate on the "emotion" field.
func EmotionIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldEmotion))
}

// EmotionNotNil applies the NotNil predicate on the "emotion" field.
func EmotionNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldEmotion))
}

// EmotionEqualFold applies the EqualFold predicate on the "emotion" field.
func EmotionEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldEmotion, v))
}

// EmotionContainsFold applies the ContainsFold predicate on the "emotion" field.
func EmotionContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldEmotion, v))
}

// TopicsIsNil applies the IsNil predicate on the "topics" field.
func TopicsIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldTopics))
}

// TopicsNotNil applies the NotNil predicate on the "topics" field.
func TopicsNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldTopics))
}

// UserIdentifierEQ applies the EQ predicate on the "user_identifier" field.
func UserIdentifierEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldUserIdentifier, v))
}

// UserIdentifierNEQ applies the NEQ predicate on the "user_identifier" field.
func UserIdentifierNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldUserIdentifier, v))
}

// UserIdentifierIn applies the In predicate on the "user_identifier" field.
func UserIdentifierIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldUserIdentifier, vs...))
}

// UserIdentifierNotIn applies the NotIn predicate on the "user_identifier" field.
func UserIdentifierNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldUserIdentifier, vs...))
}

// UserIdentifierGT applies the GT predicate on the "user_identifier" field.
func UserIdentifierGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldUserIdentifier, v))
}

// UserIdentifierGTE applies the GTE predicate on the "user_identifier" field.
func UserIdentifierGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldUserIdentifier, v))
}

// UserIdentifierLT applies the LT predicate on the "user_identifier" field.
func UserIdentifierLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldUserIdentifier, v))
}

// UserIdentifierLTE applies the LTE predicate on the "user_identifier" field.
func UserIdentifierLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldUserIdentifier, v))
}

// UserIdentifierContains applies the Contains predicate on the "user_identifier" field.
func UserIdentifierContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldUserIdentifier, v))
}

// UserIdentifierHasPrefix applies the HasPrefix predicate on the "user_identifier" field.
func UserIdentifierHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldUserIdentifier, v))
}

// UserIdentifierHasSuffix applies the HasSuffix predicate on the "user_identifier" field.
func UserIdentifierHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldUserIdentifier, v))
}

// UserIdentifierIsNil applies the IsNil predicate on the "user_identifier" field.
func UserIdentifierIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldUserIdentifier))
}

// UserIdentifierNotNil applies the NotNil predicate on the "user_identifier" field.
func UserIdentifierNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldUserIdentifier))
}

// UserIdentifierEqualFold applies the EqualFold predicate on the "user_identifier" field.
func UserIdentifierEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldUserIdentifier, v))
}

// UserIdentifierContainsFold applies the ContainsFold predicate on the "user_identifier" field.
func UserIdentifierContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldUserIdentifier, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.Vector) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldEmbedding, v))
}

// EmbeddingIsNil applies the IsNil predicate on the "embedding" field.
func EmbeddingIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldEmbedding))
}

// EmbeddingNotNil applies the NotNil predicate on the "embedding" field.
func EmbeddingNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldEmbedding))
}

// EmbeddingModelEQ applies the EQ predicate on the "embedding_model" field.
func EmbeddingModelEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEQ(FieldEmbeddingModel, v))
}

// EmbeddingModelNEQ applies the NEQ predicate on the "embedding_model" field.
func EmbeddingModelNEQ(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNEQ(FieldEmbeddingModel, v))
}

// EmbeddingModelIn applies the In predicate on the "embedding_model" field.
func EmbeddingModelIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIn(FieldEmbeddingModel, vs...))
}

// EmbeddingModelNotIn applies the NotIn predicate on the "embedding_model" field.
func EmbeddingModelNotIn(vs ...string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotIn(FieldEmbeddingModel, vs...))
}

// EmbeddingModelGT applies the GT predicate on the "embedding_model" field.
func EmbeddingModelGT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGT(FieldEmbeddingModel, v))
}

// EmbeddingModelGTE applies the GTE predicate on the "embedding_model" field.
func EmbeddingModelGTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldGTE(FieldEmbeddingModel, v))
}

// EmbeddingModelLT applies the LT predicate on the "embedding_model" field.
func EmbeddingModelLT(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLT(FieldEmbeddingModel, v))
}

// EmbeddingModelLTE applies the LTE predicate on the "embedding_model" field.
func EmbeddingModelLTE(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldLTE(FieldEmbeddingModel, v))
}

// EmbeddingModelContains applies the Contains predicate on the "embedding_model" field.
func EmbeddingModelContains(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContains(FieldEmbeddingModel, v))
}

// EmbeddingModelHasPrefix applies the HasPrefix predicate on the "embedding_model" field.
func EmbeddingModelHasPrefix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasPrefix(FieldEmbeddingModel, v))
}

// EmbeddingModelHasSuffix applies the HasSuffix predicate on the "embedding_model" field.
func EmbeddingModelHasSuffix(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldHasSuffix(FieldEmbeddingModel, v))
}

// EmbeddingModelIsNil applies the IsNil predicate on the "embedding_model" field.
func EmbeddingModelIsNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldIsNull(FieldEmbeddingModel))
}

// EmbeddingModelNotNil applies the NotNil predicate on the "embedding_model" field.
func EmbeddingModelNotNil() predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldNotNull(FieldEmbeddingModel))
}

// EmbeddingModelEqualFold applies the EqualFold predicate on the "embedding_model" field.
func EmbeddingModelEqualFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldEqualFold(FieldEmbeddingModel, v))
}

// EmbeddingModelContainsFold applies the ContainsFold predicate on the "embedding_model" field.
func EmbeddingModelContainsFold(v string) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.FieldContainsFold(FieldEmbeddingModel, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FeedbackRecord) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FeedbackRecord) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FeedbackRecord) predicate.FeedbackRecord {
	return predicate.FeedbackRecord(sql.NotPredicates(p))
}
