version: 2
updates:
  # Go modules (security updates always immediate, regular updates grouped weekly)
  - package-ecosystem: "gomod"
    directory: "/apps/hub"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor/patch updates together, major updates separate
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # npm for docs (security updates always immediate, regular updates grouped monthly)
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docs"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"

  # npm for root workspace (security updates always immediate, regular updates grouped monthly)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker (security updates always immediate, regular updates monthly)
  - package-ecosystem: "docker"
    directory: "/apps/hub"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
