# golangci-lint v2 configuration
# Run: make lint (requires make install-tools)
# See: https://golangci-lint.run/docs/configuration/
# Optimized for: Safety, Strict Modern Standards, and Performance

version: "2"

run:
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly
  go: "1.25"
  # Allow linting test files but suppress specific strict rules via exclusion below
  tests: true

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true
  sort-order: ["linter", "file"]

formatters:
  enable:
    - gci     # Deterministic import ordering
    - gofumpt # Stricter gofmt (gold standard for formatting)
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/formbricks/hub)
    gofumpt:
      extra-rules: true

linters:
  # Disable everything first to have full control
  disable-all: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - nilnil       # mocks often return (nil, nil) for success
          - err113       # mocks and test helpers use dynamic errors
          - testpackage  # tests use same package (white-box); enable when adopting _test package
  settings:
    lll:
      line-length: 164  # enforce max line length; lower to 120–140 and fix lines to tighten
    # Struct tag naming: API uses snake_case for json/form/validate/river
    tagliatelle:
      case:
        rules:
          json: snake
          form: snake
          validate: snake
          river: snake
    # Ignore common Go idioms (handlers w/r, id, db, test tt, etc.)
    varnamelen:
      ignore-names:
        - id
        - w
        - r
        - db
        - tt
        - s
        - m
        - mp
        - rw
        - wh
        - i
        - ss
        - p
  enable:
    ## 1. Bugs & Logic
    - bodyclose     # Checks HTTP response bodies are closed
    - errcheck      # checks for unchecked errors
    - govet         # standard vetted checks
    - staticcheck   # massive suite of static analysis checks
    - ineffassign   # detects when assignments are not used
    - nilerr        # Reports return nil, err when err is not nil (Subtle bug catcher!)
    - noctx         # Ensures Context is sent to HTTP/DB requests
    - contextcheck  # Stricter: context must be first param and propagated correctly
    - rowserrcheck  # checks if rows.Err() is checked
    - sqlclosecheck # checks if rows/statements are closed
    - durationcheck # detects multiplying two durations (logic error)
    - copyloopvar   # detects loop variable capture issues (modern replacement for exportloopref)
    - asasalint     # flags passing []any as any in variadic func(...any) (can hide type bugs)
    - containedctx  # ensures structs that store context.Context use it (no unused ctx fields)
    - errchkjson    # checks that json.Marshal/Unmarshal (and similar) errors are handled
    - fatcontext    # discourages storing many values in context (use structs/params instead)
    - nilnesserr    # checks for nilness issues in error handling paths
    - nilnil        # flags return nil, nil (often a bug; prefer explicit sentinel or error)
    - nosprintfhostport # use net.JoinHostPort instead of fmt.Sprintf for host:port
    - spancheck     # OpenTelemetry spans: End(), RecordError(), SetStatus() usage
    - reassign      # Flags reassignment of package-level variables
    - wastedassign  # Assignments overwritten before use
    - unqueryvet    # SQL: detects SELECT *, format strings, etc.

    ## 2. Modern Error Handling
    - errorlint     # Enforces errors.Is/As and fmt.Errorf("%w") (CRITICAL for modern Go)
    - wrapcheck     # Enforces wrapping errors from external packages for context
    - errname       # Sentinel errors: Err prefix; error types: Error suffix
    - err113        # Stricter error handling (sentinel errors, error types, no dynamic errors)

    ## 3. Performance
    - perfsprint    # Checks for optimized usage of fmt.Sprintf
    - prealloc      # Encourages pre-allocating slices
    - makezero      # Prevents slice initialization with length + append (common perf bug)

    ## 4. Security
    - gosec         # Security scanner (SQLi, hardcoded creds, etc.)
    - gosmopolitan  # i18n/l10n anti-patterns (timezone, locale, etc.)

    ## 4b. Exhaustiveness & stdlib
    - exhaustive    # Exhaustive switch on enum-like types (catch missing cases)
    - usestdlibvars # Prefer http.StatusOK, time.Kitchen etc. over magic numbers
    - exptostd      # Replace golang.org/x/exp with stdlib when possible

    ## 4c. Interfaces & types
    - iface           # Interface misuse and "interface pollution"
    - inamedparam     # Interfaces should use named method parameters
    - interfacebloat  # Limits number of methods in an interface
    - intrange        # Suggests integer range in for loops where applicable
    - iotamixing      # Iota mixed with non-iota in same const block
    - recvcheck       # Receiver type consistency (value vs pointer)
    - unconvert       # Removes unnecessary type conversions

    ## 5. Style & Formatting (The "Clean" factor)
    - decorder                   # Declaration order and count of types, constants, variables, functions
    - embeddedstructfieldcheck   # Embedded types at top of struct, blank line before normal fields
    - funcorder     # Order of functions/methods/constructors
    - varnamelen    # Variable name length should match scope (short names for short scope)
    - lll           # Max line length (enforces readable line width)
    - whitespace    # Trailing newlines, unnecessary blank lines, spaces (consistency with if/for etc.)
    - wsl_v5        # Empty-line / statement grouping (granular checks)
    - nlreturn      # Newline before return and branch statements (complements wsl_v5)
    - asciicheck    # Identifiers must use only ASCII characters
    - bidichk       # Dangerous Unicode bidirectional characters
    - canonicalheader # net/http.Header canonical key format
    - dogsled       # Too many blank identifiers in assignments
    - dupword       # Duplicate words in source (e.g. "the the")
    - revive        # Faster, configurable replacement for golint
    - misspell      # Fixes typos
    - godot         # Comments should end in a period
    - godoclint     # Checks godoc style and conventions
    - godox         # Finds FIXME, TODO, BUG, etc. in comments
    - unparam       # Reports unused function parameters
    - unused        # Reports unused constants, variables, functions and types
    - sloglint      # Structured logging (log/slog) best practices — you use slog
    - loggercheck   # Key-value pairs for slog, zap, logr, klog, kitlog
    - zerologlint   # Correct use of zerolog (e.g. Send/Msg)
    - promlinter    # Prometheus metrics naming (promlint)
    - importas      # Enforces consistent import aliases (configure alias map in settings)
    - tagliatelle   # Struct tag naming (e.g. json, yaml) case
    - tagalign      # Align and sort struct tags
    - grouper       # Grouping of expressions (e.g. var blocks)
    - nakedret      # Restricts or disallows naked returns
    - goprintffuncname # Printf-like functions must have name ending in f

    ## 6. Code Quality/Complexity
    - nestif        # Deeply nested if statements (reduces nesting complexity)
    - gocritic      # Opinionated checks for bugs, performance, and style
    - modernize     # Suggests newer Go language features
    - mnd           # Magic number detection (prefer named constants)
    - nolintlint    # Ensures //nolint comments are actually useful and formatted

    ## 7. Testing
    - testifylint       # Checks for misuse of testify/require and testify/assert
    - usetesting        # Prefer newer testing APIs (e.g. context.Background vs context.TODO in tests)
    - tparallel         # Flags inappropriate use of t.Parallel()
    - testpackage       # Encourages _test package for black-box tests
    - testableexamples  # Example functions should have expected output

issues:
  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0

  exclude-rules:
    # Tests are allowed to be more relaxed
    - path: _test\.go
      linters:
        - noctx         # HTTP requests in tests often don't need context
        - contextcheck  # same: test helpers may not propagate context
        - wrapcheck     # We don't usually wrap errors in test assertions
        - gosec         # Weak RNG is fine in tests
        - bodyclose     # often irrelevant in simple test logic
        - funlen        # tests can be long
        - exhaustive    # test switch on types often intentionally partial
        - lll           # test URLs and mock signatures are often long
        - err113        # mocks and test helpers use dynamic errors
    # Integration tests (long URLs, request setup)
    - path: tests/
      linters:
        - lll

linters-settings:
  # Error checking strictness
  errcheck:
    check-blank: true
    check-type-assertions: true

  # Modern error handling strictness
  errorlint:
    errorf: true
    asserts: true
    comparison: true

  # Code Critic options
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam # optional: can be noisy, re-enable if you want strict struct passing rules

  # Ensure nolint comments explain WHY they are ignoring something
  nolintlint:
    require-explanation: true
    require-specific: true
