.PHONY: help tests tests-coverage build run init-db clean docker-up docker-down docker-clean deps install-tools fmt fmt-check lint dev-setup test-all schemathesis

# Default target - show help
help:
	@echo "Available targets:"
	@echo "Available targets:"
	@echo "  make tests       - Run all tests"
	@echo "  make build       - Build the API server"
	@echo "  make run         - Run the API server"
	@echo "  make init-db     - Initialize database schema"
	@echo "  make docker-up   - Start Docker containers"
	@echo "  make docker-down - Stop Docker containers"
	@echo "  make clean       - Clean build artifacts"
	@echo "  make fmt         - Format code with gofumpt"
	@echo "  make fmt-check   - Check if code is formatted"
	@echo "  make schemathesis - Run Schemathesis API tests (requires API server running)"

# Run all tests
tests:
	@echo "Running all tests..."
	go test ./tests/... -v

# Run tests with coverage
tests-coverage:
	@echo "Running tests with coverage..."
	go test ./tests/... -v -cover -coverprofile=coverage.out
	go tool cover -html=coverage.out -o coverage.html
	@echo "Coverage report generated: coverage.html"

# Build the API server
build:
	@echo "Building API server..."
	go build -o bin/api cmd/api/main.go
	@echo "Binary created: bin/api"

# Run the API server
run:
	@echo "Checking for .env file..."
	@if [ ! -f .env ]; then \
		echo "Creating .env file with default values..."; \
		echo "# Formbricks Hub Configuration" > .env; \
		echo "# Auto-generated by 'make run' - modify as needed" >> .env; \
		echo "" >> .env; \
		echo "# API Key for authentication (required)" >> .env; \
		echo "API_KEY=test-api-key-12345" >> .env; \
		echo "" >> .env; \
		echo "# Database connection URL" >> .env; \
		echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable" >> .env; \
		echo "" >> .env; \
		echo "# Server port (default: 8080)" >> .env; \
		echo "PORT=8080" >> .env; \
		echo ".env file created with default values."; \
	fi
	@echo "Starting API server..."
	go run cmd/api/main.go

# Initialize database schema
init-db:
	@echo "Initializing database schema..."
	@if [ -f .env ]; then \
		export $$(grep -v '^#' .env | xargs) && \
		if [ -z "$$DATABASE_URL" ]; then \
			echo "Error: DATABASE_URL not found in .env file"; \
			exit 1; \
		fi && \
		psql "$$DATABASE_URL" -f sql/001_initial_schema.sql; \
	else \
		if [ -z "$$DATABASE_URL" ]; then \
			echo "Error: DATABASE_URL environment variable is not set"; \
			echo "Please set it or create a .env file with DATABASE_URL"; \
			exit 1; \
		fi && \
		psql "$$DATABASE_URL" -f sql/001_initial_schema.sql; \
	fi
	@echo "Database schema initialized successfully"


# Start Docker containers
docker-up:
	@echo "Starting Docker containers..."
	docker-compose up -d
	@echo "Waiting for services to be ready..."
	@sleep 3
	@docker-compose ps

# Stop Docker containers
docker-down:
	@echo "Stopping Docker containers..."
	docker-compose down

# Stop and remove volumes
docker-clean:
	@echo "Stopping Docker containers and removing volumes..."
	docker-compose down -v

# Clean build artifacts
clean:
	@echo "Cleaning build artifacts..."
	rm -rf bin/
	rm -f coverage.out coverage.html
	@echo "Clean complete"

# Install dependencies
deps:
	@echo "Installing dependencies..."
	go mod download
	go mod tidy
	@echo "Dependencies installed"

# Install development tools
install-tools:
	@echo "Installing development tools..."
	go install mvdan.cc/gofumpt@latest
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
	@echo "Tools installed"

# Format code
fmt:
	@echo "Formatting code..."
	$(HOME)/go/bin/gofumpt -l -w .
	@echo "Code formatted"

# Check code formatting (fails if code needs formatting)
fmt-check:
	@echo "Checking code formatting..."
	@if [ -n "$$($(HOME)/go/bin/gofumpt -l .)" ]; then \
		echo "Error: Code is not formatted. Run 'make fmt' to fix."; \
		$(HOME)/go/bin/gofumpt -l .; \
		exit 1; \
	fi
	@echo "Code is properly formatted"

# Lint code
lint:
	@echo "Linting code..."
	$(HOME)/go/bin/golangci-lint run ./...

# Run everything needed for development
dev-setup: docker-up deps install-tools init-db
	@echo "Development environment ready!"
	@echo "Set API_KEY environment variable for authentication"
	@echo "Run 'make run' to start the API server"

# Full test suite (unit + integration)
test-all: tests
	@echo "All tests passed!"

# Run Schemathesis API tests
# Requires: API server running (make run in another terminal)
# Requires: uvx (install via: curl -LsSf https://astral.sh/uv/install.sh | sh)
schemathesis:
	@echo "Running Schemathesis API tests..."
	@export PATH="$$HOME/.local/bin:$$PATH" && \
	if [ -f .env ]; then \
		export $$(grep -v '^#' .env | xargs) && \
		if [ -z "$$API_KEY" ]; then \
			echo "Warning: API_KEY not found in .env file, tests may fail authentication"; \
		fi && \
		uvx schemathesis run ./openapi.yaml \
			--url http://localhost:8080 \
			--header "Authorization: Bearer $${API_KEY:-test-api-key-12345}" \
			--checks all \
			--max-examples 50; \
	else \
		if [ -z "$$API_KEY" ]; then \
			echo "Error: API_KEY environment variable is not set and .env file not found"; \
			echo "Please set API_KEY or create a .env file"; \
			exit 1; \
		fi && \
		uvx schemathesis run ./openapi.yaml \
			--url http://localhost:8080 \
			--header "Authorization: Bearer $$API_KEY" \
			--checks all \
			--max-examples 50; \
	fi
