.PHONY: help tests tests-coverage build run init-db clean docker-up docker-down docker-clean deps install-tools fmt lint lint-new dev-setup test-all test-unit schemathesis install-hooks migrate-status migrate-validate river-migrate

# Default target - show help
help:
	@echo "Available targets:"
	@echo "  make help             - Show this help message"
	@echo "  make dev-setup        - Set up development environment (docker, deps, tools, schema, hooks)"
	@echo "  make build            - Build the API server"
	@echo "  make run              - Run the API server"
	@echo "  make test-unit        - Run unit tests (fast, no database)"
	@echo "  make tests            - Run integration tests"
	@echo "  make test-all         - Run all tests (unit + integration)"
	@echo "  make tests-coverage   - Run tests with coverage report"
	@echo "  make init-db          - Initialize database schema (run migrations with goose)"
	@echo "  make migrate-status   - Show migration status"
	@echo "  make migrate-validate - Validate migration files (no DB)"
	@echo "  make river-migrate    - Run River job queue migrations (required for webhook delivery)"
	@echo "  make fmt              - Format code (golangci-lint run --fix)"
	@echo "  make lint             - Run linter (includes format checks)"
	@echo "  make lint-new         - Run linter only on new code since main (for CI; fail on new issues)"
	@echo "  make deps             - Install Go dependencies"
	@echo "  make install-tools    - Install development tools (golangci-lint, govulncheck, goose)"
	@echo "  make install-hooks    - Install git hooks"
	@echo "  make docker-up        - Start Docker containers"
	@echo "  make docker-down      - Stop Docker containers"
	@echo "  make docker-clean     - Stop Docker containers and remove volumes"
	@echo "  make clean            - Clean build artifacts"
	@echo "  make schemathesis     - Run Schemathesis API tests (requires API server running)"

# Run all tests (integration tests in tests/ directory)
tests:
	@echo "Running integration tests..."
	go test ./tests/... -v

# Run unit tests (fast, no database required)
test-unit:
	@echo "Running unit tests..."
	go test ./internal/... -v

# Run all tests (unit + integration)
test-all: test-unit tests
	@echo "All tests passed!"

# Run tests with coverage (unit + integration)
tests-coverage:
	@echo "Running tests with coverage..."
	go test ./internal/... ./tests/... -v -cover -coverprofile=coverage.out
	go tool cover -html=coverage.out -o coverage.html
	@echo "Coverage report generated: coverage.html"

# Build the API server
build:
	@echo "Building API server..."
	go build -o bin/api ./cmd/api
	@echo "Binary created: bin/api"

# Run the API server
run:
	@echo "Checking for .env file..."
	@if [ ! -f .env ]; then \
		echo "Creating .env file with default values..."; \
		echo "# Formbricks Hub Configuration" > .env; \
		echo "# Auto-generated by 'make run' - modify as needed" >> .env; \
		echo "" >> .env; \
		echo "# API Key for authentication (required)" >> .env; \
		echo "API_KEY=test-api-key-12345" >> .env; \
		echo "" >> .env; \
		echo "# Database connection URL (optional: set POSTGRES_PORT in .env if 5432 is in use; keep port in sync here)" >> .env; \
		echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable" >> .env; \
		echo "" >> .env; \
		echo "# Server port (default: 8080)" >> .env; \
		echo "PORT=8080" >> .env; \
		echo ".env file created with default values."; \
	fi
	@echo "Starting API server..."
	go run ./cmd/api

# Initialize database schema (run goose migrations up)
init-db:
	@echo "Running migrations..."
	@command -v goose >/dev/null 2>&1 || { echo "Error: goose not found. Install with: make install-tools"; exit 1; }
	@if [ -f .env ]; then \
		export $$(grep -v '^#' .env | xargs) && \
		if [ -z "$$DATABASE_URL" ]; then \
			echo "Error: DATABASE_URL not found in .env file"; \
			exit 1; \
		fi && \
		goose -dir migrations postgres "$$DATABASE_URL" up; \
	else \
		if [ -z "$$DATABASE_URL" ]; then \
			echo "Error: DATABASE_URL environment variable is not set"; \
			echo "Please set it or create a .env file with DATABASE_URL"; \
			exit 1; \
		fi && \
		goose -dir migrations postgres "$$DATABASE_URL" up; \
	fi
	@echo "Migrations applied successfully"

# Show migration status (requires DATABASE_URL)
migrate-status:
	@command -v goose >/dev/null 2>&1 || { echo "Error: goose not found. Install with: make install-tools"; exit 1; }
	@if [ -f .env ]; then export $$(grep -v '^#' .env | xargs); fi && \
	if [ -z "$$DATABASE_URL" ]; then \
		echo "Error: DATABASE_URL not set"; exit 1; \
	fi && \
	goose -dir migrations postgres "$$DATABASE_URL" status

# Validate migration files (no database required)
migrate-validate:
	@command -v goose >/dev/null 2>&1 || { echo "Error: goose not found. Install with: make install-tools"; exit 1; }
	@goose -dir migrations validate
	@echo "Migration files are valid"

# Run River job queue migrations (required for webhook delivery)
river-migrate:
	@command -v river >/dev/null 2>&1 || { echo "Error: river CLI not found. Install with: go install github.com/riverqueue/river/cmd/river@latest"; exit 1; }
	@if [ -f .env ]; then \
		export $$(grep -v '^#' .env | xargs) && \
		if [ -z "$$DATABASE_URL" ]; then echo "Error: DATABASE_URL not found in .env"; exit 1; fi && \
		river migrate-up --database-url "$$DATABASE_URL"; \
	else \
		if [ -z "$$DATABASE_URL" ]; then echo "Error: DATABASE_URL not set"; exit 1; fi && \
		river migrate-up --database-url "$$DATABASE_URL"; \
	fi
	@echo "River migrations applied"

# Start Docker containers
docker-up:
	@echo "Starting Docker containers..."
	docker compose up -d
	@echo "Waiting for services to be ready..."
	@sleep 3
	@docker compose ps

# Stop Docker containers
docker-down:
	@echo "Stopping Docker containers..."
	docker compose down

# Stop and remove volumes
docker-clean:
	@echo "Stopping Docker containers and removing volumes..."
	docker compose down -v

# Clean build artifacts
clean:
	@echo "Cleaning build artifacts..."
	rm -rf bin/
	rm -f coverage.out coverage.html
	@echo "Clean complete"

# Install dependencies
deps:
	@echo "Installing dependencies..."
	go mod download
	go mod tidy
	@echo "Dependencies installed"

# Install development tools
# Tool versions - update these periodically
GOLANGCI_LINT_VERSION := v2.8.0
GOVULNCHECK_VERSION := v1.1.4
GOOSE_VERSION := v3.26.0

install-tools:
	@echo "Installing development tools..."
	go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)
	go install golang.org/x/vuln/cmd/govulncheck@$(GOVULNCHECK_VERSION)
	go install github.com/pressly/goose/v3/cmd/goose@$(GOOSE_VERSION)
	@echo "Tools installed (golangci-lint $(GOLANGCI_LINT_VERSION), govulncheck $(GOVULNCHECK_VERSION), goose $(GOOSE_VERSION))"

# Format code (golangci-lint applies gofumpt + gci from .golangci.yml formatters)
fmt:
	@echo "Formatting code..."
	@command -v golangci-lint >/dev/null 2>&1 || { echo "Error: golangci-lint not found. Install with: make install-tools"; exit 1; }
	golangci-lint run --fix ./...
	@echo "Code formatted"

# Lint code
lint:
	@echo "Linting code..."
	@command -v golangci-lint >/dev/null 2>&1 || { echo "Error: golangci-lint not found. Install with: make install-tools"; exit 1; }
	golangci-lint run ./...

# Lint only new code since base branch (for CI: fail on new issues, not existing ones).
# Use in CI so the build fails only on new lint issues; fix in same PR and gradually clean legacy ones.
LINT_BASE_REV ?= main
lint-new:
	@echo "Linting new code since $(LINT_BASE_REV)..."
	@command -v golangci-lint >/dev/null 2>&1 || { echo "Error: golangci-lint not found. Install with: make install-tools"; exit 1; }
	golangci-lint run --new-from-rev=$(LINT_BASE_REV) ./...

# Install git hooks from .githooks directory
install-hooks:
	@echo "Installing git hooks..."
	@if [ -d .githooks ]; then \
		cp .githooks/pre-commit .git/hooks/pre-commit && \
		chmod +x .git/hooks/pre-commit && \
		echo "✅ Git hooks installed successfully"; \
	else \
		echo "Error: .githooks directory not found"; \
		exit 1; \
	fi

# Run everything needed for development
dev-setup: docker-up deps install-tools init-db install-hooks
	@echo "Development environment ready!"
	@echo "Set API_KEY environment variable for authentication"
	@echo "Run 'make run' to start the API server"

# Run Schemathesis API tests (all phases for thorough local testing)
# Phases: examples (schema examples), coverage (boundary values), stateful (API sequences), fuzzing (random)
# This runs more thorough tests than CI to find edge-case bugs.
# Requires: API server running (make run in another terminal)
# Requires: uvx (install via: curl -LsSf https://astral.sh/uv/install.sh | sh)
schemathesis:
	@echo "Running Schemathesis API tests (all phases)..."
	@echo "This is deeper testing than CI - may find edge-case bugs."
	@export PATH="$$HOME/.local/bin:$$PATH" && \
	if [ -f .env ]; then \
		export $$(grep -v '^#' .env | xargs) && \
		if [ -z "$$API_KEY" ]; then \
			echo "Warning: API_KEY not found in .env file, tests may fail authentication"; \
		fi && \
		uvx schemathesis run ./openapi.yaml \
			--url http://localhost:8080 \
			--header "Authorization: Bearer $${API_KEY:-test-api-key-12345}" \
			--checks all \
			--phases examples,coverage,stateful,fuzzing \
			--max-examples 50; \
	else \
		if [ -z "$$API_KEY" ]; then \
			echo "Error: API_KEY environment variable is not set and .env file not found"; \
			echo "Please set API_KEY or create a .env file"; \
			exit 1; \
		fi && \
		uvx schemathesis run ./openapi.yaml \
			--url http://localhost:8080 \
			--header "Authorization: Bearer $$API_KEY" \
			--checks all \
			--phases examples,coverage,stateful,fuzzing \
			--max-examples 50; \
	fi
