// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/hub/internal/ent/enrichmentjob"
	"github.com/formbricks/hub/internal/ent/feedbackrecord"
	"github.com/google/uuid"
)

// EnrichmentJobCreate is the builder for creating a EnrichmentJob entity.
type EnrichmentJobCreate struct {
	config
	mutation *EnrichmentJobMutation
	hooks    []Hook
}

// SetFeedbackRecordID sets the "feedback_record_id" field.
func (_c *EnrichmentJobCreate) SetFeedbackRecordID(v uuid.UUID) *EnrichmentJobCreate {
	_c.mutation.SetFeedbackRecordID(v)
	return _c
}

// SetNillableFeedbackRecordID sets the "feedback_record_id" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableFeedbackRecordID(v *uuid.UUID) *EnrichmentJobCreate {
	if v != nil {
		_c.SetFeedbackRecordID(*v)
	}
	return _c
}

// SetJobType sets the "job_type" field.
func (_c *EnrichmentJobCreate) SetJobType(v string) *EnrichmentJobCreate {
	_c.mutation.SetJobType(v)
	return _c
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableJobType(v *string) *EnrichmentJobCreate {
	if v != nil {
		_c.SetJobType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnrichmentJobCreate) SetStatus(v string) *EnrichmentJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableStatus(v *string) *EnrichmentJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetText sets the "text" field.
func (_c *EnrichmentJobCreate) SetText(v string) *EnrichmentJobCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetError sets the "error" field.
func (_c *EnrichmentJobCreate) SetError(v string) *EnrichmentJobCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableError(v *string) *EnrichmentJobCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *EnrichmentJobCreate) SetAttempts(v int) *EnrichmentJobCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableAttempts(v *int) *EnrichmentJobCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnrichmentJobCreate) SetCreatedAt(v time.Time) *EnrichmentJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableCreatedAt(v *time.Time) *EnrichmentJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *EnrichmentJobCreate) SetProcessedAt(v time.Time) *EnrichmentJobCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableProcessedAt(v *time.Time) *EnrichmentJobCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EnrichmentJobCreate) SetID(v uuid.UUID) *EnrichmentJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EnrichmentJobCreate) SetNillableID(v *uuid.UUID) *EnrichmentJobCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetFeedbackRecord sets the "feedback_record" edge to the FeedbackRecord entity.
func (_c *EnrichmentJobCreate) SetFeedbackRecord(v *FeedbackRecord) *EnrichmentJobCreate {
	return _c.SetFeedbackRecordID(v.ID)
}

// Mutation returns the EnrichmentJobMutation object of the builder.
func (_c *EnrichmentJobCreate) Mutation() *EnrichmentJobMutation {
	return _c.mutation
}

// Save creates the EnrichmentJob in the database.
func (_c *EnrichmentJobCreate) Save(ctx context.Context) (*EnrichmentJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnrichmentJobCreate) SaveX(ctx context.Context) *EnrichmentJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnrichmentJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnrichmentJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnrichmentJobCreate) defaults() {
	if _, ok := _c.mutation.JobType(); !ok {
		v := enrichmentjob.DefaultJobType
		_c.mutation.SetJobType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := enrichmentjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := enrichmentjob.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enrichmentjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := enrichmentjob.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnrichmentJobCreate) check() error {
	if _, ok := _c.mutation.JobType(); !ok {
		return &ValidationError{Name: "job_type", err: errors.New(`ent: missing required field "EnrichmentJob.job_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EnrichmentJob.status"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "EnrichmentJob.text"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "EnrichmentJob.attempts"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnrichmentJob.created_at"`)}
	}
	return nil
}

func (_c *EnrichmentJobCreate) sqlSave(ctx context.Context) (*EnrichmentJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnrichmentJobCreate) createSpec() (*EnrichmentJob, *sqlgraph.CreateSpec) {
	var (
		_node = &EnrichmentJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enrichmentjob.Table, sqlgraph.NewFieldSpec(enrichmentjob.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.JobType(); ok {
		_spec.SetField(enrichmentjob.FieldJobType, field.TypeString, value)
		_node.JobType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enrichmentjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(enrichmentjob.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(enrichmentjob.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(enrichmentjob.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enrichmentjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(enrichmentjob.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if nodes := _c.mutation.FeedbackRecordIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enrichmentjob.FeedbackRecordTable,
			Columns: []string{enrichmentjob.FeedbackRecordColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(feedbackrecord.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FeedbackRecordID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EnrichmentJobCreateBulk is the builder for creating many EnrichmentJob entities in bulk.
type EnrichmentJobCreateBulk struct {
	config
	err      error
	builders []*EnrichmentJobCreate
}

// Save creates the EnrichmentJob entities in the database.
func (_c *EnrichmentJobCreateBulk) Save(ctx context.Context) ([]*EnrichmentJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnrichmentJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnrichmentJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnrichmentJobCreateBulk) SaveX(ctx context.Context) []*EnrichmentJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnrichmentJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnrichmentJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
