// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/hub/internal/ent/feedbackrecord"
	"github.com/formbricks/hub/internal/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// FeedbackRecordUpdate is the builder for updating FeedbackRecord entities.
type FeedbackRecordUpdate struct {
	config
	hooks    []Hook
	mutation *FeedbackRecordMutation
}

// Where appends a list predicates to the FeedbackRecordUpdate builder.
func (_u *FeedbackRecordUpdate) Where(ps ...predicate.FeedbackRecord) *FeedbackRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *FeedbackRecordUpdate) SetCollectedAt(v time.Time) *FeedbackRecordUpdate {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableCollectedAt(v *time.Time) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedbackRecordUpdate) SetUpdatedAt(v time.Time) *FeedbackRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *FeedbackRecordUpdate) SetTenantID(v string) *FeedbackRecordUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableTenantID(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *FeedbackRecordUpdate) ClearTenantID() *FeedbackRecordUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetResponseID sets the "response_id" field.
func (_u *FeedbackRecordUpdate) SetResponseID(v string) *FeedbackRecordUpdate {
	_u.mutation.SetResponseID(v)
	return _u
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableResponseID(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetResponseID(*v)
	}
	return _u
}

// ClearResponseID clears the value of the "response_id" field.
func (_u *FeedbackRecordUpdate) ClearResponseID() *FeedbackRecordUpdate {
	_u.mutation.ClearResponseID()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *FeedbackRecordUpdate) SetSourceType(v string) *FeedbackRecordUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableSourceType(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *FeedbackRecordUpdate) SetSourceID(v string) *FeedbackRecordUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableSourceID(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *FeedbackRecordUpdate) ClearSourceID() *FeedbackRecordUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *FeedbackRecordUpdate) SetSourceName(v string) *FeedbackRecordUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableSourceName(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *FeedbackRecordUpdate) ClearSourceName() *FeedbackRecordUpdate {
	_u.mutation.ClearSourceName()
	return _u
}

// SetFieldID sets the "field_id" field.
func (_u *FeedbackRecordUpdate) SetFieldID(v string) *FeedbackRecordUpdate {
	_u.mutation.SetFieldID(v)
	return _u
}

// SetNillableFieldID sets the "field_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableFieldID(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetFieldID(*v)
	}
	return _u
}

// SetFieldLabel sets the "field_label" field.
func (_u *FeedbackRecordUpdate) SetFieldLabel(v string) *FeedbackRecordUpdate {
	_u.mutation.SetFieldLabel(v)
	return _u
}

// SetNillableFieldLabel sets the "field_label" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableFieldLabel(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetFieldLabel(*v)
	}
	return _u
}

// ClearFieldLabel clears the value of the "field_label" field.
func (_u *FeedbackRecordUpdate) ClearFieldLabel() *FeedbackRecordUpdate {
	_u.mutation.ClearFieldLabel()
	return _u
}

// SetFieldType sets the "field_type" field.
func (_u *FeedbackRecordUpdate) SetFieldType(v string) *FeedbackRecordUpdate {
	_u.mutation.SetFieldType(v)
	return _u
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableFieldType(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetFieldType(*v)
	}
	return _u
}

// SetValueText sets the "value_text" field.
func (_u *FeedbackRecordUpdate) SetValueText(v string) *FeedbackRecordUpdate {
	_u.mutation.SetValueText(v)
	return _u
}

// SetNillableValueText sets the "value_text" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableValueText(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetValueText(*v)
	}
	return _u
}

// ClearValueText clears the value of the "value_text" field.
func (_u *FeedbackRecordUpdate) ClearValueText() *FeedbackRecordUpdate {
	_u.mutation.ClearValueText()
	return _u
}

// SetValueNumber sets the "value_number" field.
func (_u *FeedbackRecordUpdate) SetValueNumber(v float64) *FeedbackRecordUpdate {
	_u.mutation.ResetValueNumber()
	_u.mutation.SetValueNumber(v)
	return _u
}

// SetNillableValueNumber sets the "value_number" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableValueNumber(v *float64) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetValueNumber(*v)
	}
	return _u
}

// AddValueNumber adds value to the "value_number" field.
func (_u *FeedbackRecordUpdate) AddValueNumber(v float64) *FeedbackRecordUpdate {
	_u.mutation.AddValueNumber(v)
	return _u
}

// ClearValueNumber clears the value of the "value_number" field.
func (_u *FeedbackRecordUpdate) ClearValueNumber() *FeedbackRecordUpdate {
	_u.mutation.ClearValueNumber()
	return _u
}

// SetValueBoolean sets the "value_boolean" field.
func (_u *FeedbackRecordUpdate) SetValueBoolean(v bool) *FeedbackRecordUpdate {
	_u.mutation.SetValueBoolean(v)
	return _u
}

// SetNillableValueBoolean sets the "value_boolean" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableValueBoolean(v *bool) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetValueBoolean(*v)
	}
	return _u
}

// ClearValueBoolean clears the value of the "value_boolean" field.
func (_u *FeedbackRecordUpdate) ClearValueBoolean() *FeedbackRecordUpdate {
	_u.mutation.ClearValueBoolean()
	return _u
}

// SetValueDate sets the "value_date" field.
func (_u *FeedbackRecordUpdate) SetValueDate(v time.Time) *FeedbackRecordUpdate {
	_u.mutation.SetValueDate(v)
	return _u
}

// SetNillableValueDate sets the "value_date" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableValueDate(v *time.Time) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetValueDate(*v)
	}
	return _u
}

// ClearValueDate clears the value of the "value_date" field.
func (_u *FeedbackRecordUpdate) ClearValueDate() *FeedbackRecordUpdate {
	_u.mutation.ClearValueDate()
	return _u
}

// SetValueJSON sets the "value_json" field.
func (_u *FeedbackRecordUpdate) SetValueJSON(v map[string]interface{}) *FeedbackRecordUpdate {
	_u.mutation.SetValueJSON(v)
	return _u
}

// ClearValueJSON clears the value of the "value_json" field.
func (_u *FeedbackRecordUpdate) ClearValueJSON() *FeedbackRecordUpdate {
	_u.mutation.ClearValueJSON()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FeedbackRecordUpdate) SetMetadata(v map[string]interface{}) *FeedbackRecordUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *FeedbackRecordUpdate) ClearMetadata() *FeedbackRecordUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *FeedbackRecordUpdate) SetLanguage(v string) *FeedbackRecordUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableLanguage(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *FeedbackRecordUpdate) ClearLanguage() *FeedbackRecordUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetSentiment sets the "sentiment" field.
func (_u *FeedbackRecordUpdate) SetSentiment(v string) *FeedbackRecordUpdate {
	_u.mutation.SetSentiment(v)
	return _u
}

// SetNillableSentiment sets the "sentiment" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableSentiment(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetSentiment(*v)
	}
	return _u
}

// ClearSentiment clears the value of the "sentiment" field.
func (_u *FeedbackRecordUpdate) ClearSentiment() *FeedbackRecordUpdate {
	_u.mutation.ClearSentiment()
	return _u
}

// SetSentimentScore sets the "sentiment_score" field.
func (_u *FeedbackRecordUpdate) SetSentimentScore(v float64) *FeedbackRecordUpdate {
	_u.mutation.ResetSentimentScore()
	_u.mutation.SetSentimentScore(v)
	return _u
}

// SetNillableSentimentScore sets the "sentiment_score" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableSentimentScore(v *float64) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetSentimentScore(*v)
	}
	return _u
}

// AddSentimentScore adds value to the "sentiment_score" field.
func (_u *FeedbackRecordUpdate) AddSentimentScore(v float64) *FeedbackRecordUpdate {
	_u.mutation.AddSentimentScore(v)
	return _u
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (_u *FeedbackRecordUpdate) ClearSentimentScore() *FeedbackRecordUpdate {
	_u.mutation.ClearSentimentScore()
	return _u
}

// SetEmotion sets the "emotion" field.
func (_u *FeedbackRecordUpdate) SetEmotion(v string) *FeedbackRecordUpdate {
	_u.mutation.SetEmotion(v)
	return _u
}

// SetNillableEmotion sets the "emotion" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableEmotion(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetEmotion(*v)
	}
	return _u
}

// ClearEmotion clears the value of the "emotion" field.
func (_u *FeedbackRecordUpdate) ClearEmotion() *FeedbackRecordUpdate {
	_u.mutation.ClearEmotion()
	return _u
}

// SetTopics sets the "topics" field.
func (_u *FeedbackRecordUpdate) SetTopics(v []string) *FeedbackRecordUpdate {
	_u.mutation.SetTopics(v)
	return _u
}

// AppendTopics appends value to the "topics" field.
func (_u *FeedbackRecordUpdate) AppendTopics(v []string) *FeedbackRecordUpdate {
	_u.mutation.AppendTopics(v)
	return _u
}

// ClearTopics clears the value of the "topics" field.
func (_u *FeedbackRecordUpdate) ClearTopics() *FeedbackRecordUpdate {
	_u.mutation.ClearTopics()
	return _u
}

// SetUserIdentifier sets the "user_identifier" field.
func (_u *FeedbackRecordUpdate) SetUserIdentifier(v string) *FeedbackRecordUpdate {
	_u.mutation.SetUserIdentifier(v)
	return _u
}

// SetNillableUserIdentifier sets the "user_identifier" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableUserIdentifier(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetUserIdentifier(*v)
	}
	return _u
}

// ClearUserIdentifier clears the value of the "user_identifier" field.
func (_u *FeedbackRecordUpdate) ClearUserIdentifier() *FeedbackRecordUpdate {
	_u.mutation.ClearUserIdentifier()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *FeedbackRecordUpdate) SetEmbedding(v pgvector.Vector) *FeedbackRecordUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableEmbedding(v *pgvector.Vector) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *FeedbackRecordUpdate) ClearEmbedding() *FeedbackRecordUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *FeedbackRecordUpdate) SetEmbeddingModel(v string) *FeedbackRecordUpdate {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *FeedbackRecordUpdate) SetNillableEmbeddingModel(v *string) *FeedbackRecordUpdate {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (_u *FeedbackRecordUpdate) ClearEmbeddingModel() *FeedbackRecordUpdate {
	_u.mutation.ClearEmbeddingModel()
	return _u
}

// Mutation returns the FeedbackRecordMutation object of the builder.
func (_u *FeedbackRecordUpdate) Mutation() *FeedbackRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeedbackRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeedbackRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedbackRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feedbackrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackRecordUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := feedbackrecord.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseID(); ok {
		if err := feedbackrecord.ResponseIDValidator(v); err != nil {
			return &ValidationError{Name: "response_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.response_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := feedbackrecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldID(); ok {
		if err := feedbackrecord.FieldIDValidator(v); err != nil {
			return &ValidationError{Name: "field_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.field_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldType(); ok {
		if err := feedbackrecord.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.field_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := feedbackrecord.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.language": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedbackRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedbackrecord.Table, feedbackrecord.Columns, sqlgraph.NewFieldSpec(feedbackrecord.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(feedbackrecord.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feedbackrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(feedbackrecord.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(feedbackrecord.FieldTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseID(); ok {
		_spec.SetField(feedbackrecord.FieldResponseID, field.TypeString, value)
	}
	if _u.mutation.ResponseIDCleared() {
		_spec.ClearField(feedbackrecord.FieldResponseID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(feedbackrecord.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(feedbackrecord.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(feedbackrecord.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(feedbackrecord.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(feedbackrecord.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.FieldID(); ok {
		_spec.SetField(feedbackrecord.FieldFieldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FieldLabel(); ok {
		_spec.SetField(feedbackrecord.FieldFieldLabel, field.TypeString, value)
	}
	if _u.mutation.FieldLabelCleared() {
		_spec.ClearField(feedbackrecord.FieldFieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.FieldType(); ok {
		_spec.SetField(feedbackrecord.FieldFieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueText(); ok {
		_spec.SetField(feedbackrecord.FieldValueText, field.TypeString, value)
	}
	if _u.mutation.ValueTextCleared() {
		_spec.ClearField(feedbackrecord.FieldValueText, field.TypeString)
	}
	if value, ok := _u.mutation.ValueNumber(); ok {
		_spec.SetField(feedbackrecord.FieldValueNumber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValueNumber(); ok {
		_spec.AddField(feedbackrecord.FieldValueNumber, field.TypeFloat64, value)
	}
	if _u.mutation.ValueNumberCleared() {
		_spec.ClearField(feedbackrecord.FieldValueNumber, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ValueBoolean(); ok {
		_spec.SetField(feedbackrecord.FieldValueBoolean, field.TypeBool, value)
	}
	if _u.mutation.ValueBooleanCleared() {
		_spec.ClearField(feedbackrecord.FieldValueBoolean, field.TypeBool)
	}
	if value, ok := _u.mutation.ValueDate(); ok {
		_spec.SetField(feedbackrecord.FieldValueDate, field.TypeTime, value)
	}
	if _u.mutation.ValueDateCleared() {
		_spec.ClearField(feedbackrecord.FieldValueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ValueJSON(); ok {
		_spec.SetField(feedbackrecord.FieldValueJSON, field.TypeJSON, value)
	}
	if _u.mutation.ValueJSONCleared() {
		_spec.ClearField(feedbackrecord.FieldValueJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(feedbackrecord.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(feedbackrecord.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(feedbackrecord.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(feedbackrecord.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.Sentiment(); ok {
		_spec.SetField(feedbackrecord.FieldSentiment, field.TypeString, value)
	}
	if _u.mutation.SentimentCleared() {
		_spec.ClearField(feedbackrecord.FieldSentiment, field.TypeString)
	}
	if value, ok := _u.mutation.SentimentScore(); ok {
		_spec.SetField(feedbackrecord.FieldSentimentScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSentimentScore(); ok {
		_spec.AddField(feedbackrecord.FieldSentimentScore, field.TypeFloat64, value)
	}
	if _u.mutation.SentimentScoreCleared() {
		_spec.ClearField(feedbackrecord.FieldSentimentScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Emotion(); ok {
		_spec.SetField(feedbackrecord.FieldEmotion, field.TypeString, value)
	}
	if _u.mutation.EmotionCleared() {
		_spec.ClearField(feedbackrecord.FieldEmotion, field.TypeString)
	}
	if value, ok := _u.mutation.Topics(); ok {
		_spec.SetField(feedbackrecord.FieldTopics, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTopics(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, feedbackrecord.FieldTopics, value)
		})
	}
	if _u.mutation.TopicsCleared() {
		_spec.ClearField(feedbackrecord.FieldTopics, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserIdentifier(); ok {
		_spec.SetField(feedbackrecord.FieldUserIdentifier, field.TypeString, value)
	}
	if _u.mutation.UserIdentifierCleared() {
		_spec.ClearField(feedbackrecord.FieldUserIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(feedbackrecord.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(feedbackrecord.FieldEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(feedbackrecord.FieldEmbeddingModel, field.TypeString, value)
	}
	if _u.mutation.EmbeddingModelCleared() {
		_spec.ClearField(feedbackrecord.FieldEmbeddingModel, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedbackrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeedbackRecordUpdateOne is the builder for updating a single FeedbackRecord entity.
type FeedbackRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeedbackRecordMutation
}

// SetCollectedAt sets the "collected_at" field.
func (_u *FeedbackRecordUpdateOne) SetCollectedAt(v time.Time) *FeedbackRecordUpdateOne {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableCollectedAt(v *time.Time) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeedbackRecordUpdateOne) SetUpdatedAt(v time.Time) *FeedbackRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *FeedbackRecordUpdateOne) SetTenantID(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableTenantID(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *FeedbackRecordUpdateOne) ClearTenantID() *FeedbackRecordUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetResponseID sets the "response_id" field.
func (_u *FeedbackRecordUpdateOne) SetResponseID(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetResponseID(v)
	return _u
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableResponseID(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetResponseID(*v)
	}
	return _u
}

// ClearResponseID clears the value of the "response_id" field.
func (_u *FeedbackRecordUpdateOne) ClearResponseID() *FeedbackRecordUpdateOne {
	_u.mutation.ClearResponseID()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *FeedbackRecordUpdateOne) SetSourceType(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableSourceType(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *FeedbackRecordUpdateOne) SetSourceID(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableSourceID(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *FeedbackRecordUpdateOne) ClearSourceID() *FeedbackRecordUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *FeedbackRecordUpdateOne) SetSourceName(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableSourceName(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *FeedbackRecordUpdateOne) ClearSourceName() *FeedbackRecordUpdateOne {
	_u.mutation.ClearSourceName()
	return _u
}

// SetFieldID sets the "field_id" field.
func (_u *FeedbackRecordUpdateOne) SetFieldID(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetFieldID(v)
	return _u
}

// SetNillableFieldID sets the "field_id" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableFieldID(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetFieldID(*v)
	}
	return _u
}

// SetFieldLabel sets the "field_label" field.
func (_u *FeedbackRecordUpdateOne) SetFieldLabel(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetFieldLabel(v)
	return _u
}

// SetNillableFieldLabel sets the "field_label" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableFieldLabel(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetFieldLabel(*v)
	}
	return _u
}

// ClearFieldLabel clears the value of the "field_label" field.
func (_u *FeedbackRecordUpdateOne) ClearFieldLabel() *FeedbackRecordUpdateOne {
	_u.mutation.ClearFieldLabel()
	return _u
}

// SetFieldType sets the "field_type" field.
func (_u *FeedbackRecordUpdateOne) SetFieldType(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetFieldType(v)
	return _u
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableFieldType(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetFieldType(*v)
	}
	return _u
}

// SetValueText sets the "value_text" field.
func (_u *FeedbackRecordUpdateOne) SetValueText(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetValueText(v)
	return _u
}

// SetNillableValueText sets the "value_text" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableValueText(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetValueText(*v)
	}
	return _u
}

// ClearValueText clears the value of the "value_text" field.
func (_u *FeedbackRecordUpdateOne) ClearValueText() *FeedbackRecordUpdateOne {
	_u.mutation.ClearValueText()
	return _u
}

// SetValueNumber sets the "value_number" field.
func (_u *FeedbackRecordUpdateOne) SetValueNumber(v float64) *FeedbackRecordUpdateOne {
	_u.mutation.ResetValueNumber()
	_u.mutation.SetValueNumber(v)
	return _u
}

// SetNillableValueNumber sets the "value_number" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableValueNumber(v *float64) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetValueNumber(*v)
	}
	return _u
}

// AddValueNumber adds value to the "value_number" field.
func (_u *FeedbackRecordUpdateOne) AddValueNumber(v float64) *FeedbackRecordUpdateOne {
	_u.mutation.AddValueNumber(v)
	return _u
}

// ClearValueNumber clears the value of the "value_number" field.
func (_u *FeedbackRecordUpdateOne) ClearValueNumber() *FeedbackRecordUpdateOne {
	_u.mutation.ClearValueNumber()
	return _u
}

// SetValueBoolean sets the "value_boolean" field.
func (_u *FeedbackRecordUpdateOne) SetValueBoolean(v bool) *FeedbackRecordUpdateOne {
	_u.mutation.SetValueBoolean(v)
	return _u
}

// SetNillableValueBoolean sets the "value_boolean" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableValueBoolean(v *bool) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetValueBoolean(*v)
	}
	return _u
}

// ClearValueBoolean clears the value of the "value_boolean" field.
func (_u *FeedbackRecordUpdateOne) ClearValueBoolean() *FeedbackRecordUpdateOne {
	_u.mutation.ClearValueBoolean()
	return _u
}

// SetValueDate sets the "value_date" field.
func (_u *FeedbackRecordUpdateOne) SetValueDate(v time.Time) *FeedbackRecordUpdateOne {
	_u.mutation.SetValueDate(v)
	return _u
}

// SetNillableValueDate sets the "value_date" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableValueDate(v *time.Time) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetValueDate(*v)
	}
	return _u
}

// ClearValueDate clears the value of the "value_date" field.
func (_u *FeedbackRecordUpdateOne) ClearValueDate() *FeedbackRecordUpdateOne {
	_u.mutation.ClearValueDate()
	return _u
}

// SetValueJSON sets the "value_json" field.
func (_u *FeedbackRecordUpdateOne) SetValueJSON(v map[string]interface{}) *FeedbackRecordUpdateOne {
	_u.mutation.SetValueJSON(v)
	return _u
}

// ClearValueJSON clears the value of the "value_json" field.
func (_u *FeedbackRecordUpdateOne) ClearValueJSON() *FeedbackRecordUpdateOne {
	_u.mutation.ClearValueJSON()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *FeedbackRecordUpdateOne) SetMetadata(v map[string]interface{}) *FeedbackRecordUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *FeedbackRecordUpdateOne) ClearMetadata() *FeedbackRecordUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *FeedbackRecordUpdateOne) SetLanguage(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableLanguage(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *FeedbackRecordUpdateOne) ClearLanguage() *FeedbackRecordUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetSentiment sets the "sentiment" field.
func (_u *FeedbackRecordUpdateOne) SetSentiment(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetSentiment(v)
	return _u
}

// SetNillableSentiment sets the "sentiment" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableSentiment(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetSentiment(*v)
	}
	return _u
}

// ClearSentiment clears the value of the "sentiment" field.
func (_u *FeedbackRecordUpdateOne) ClearSentiment() *FeedbackRecordUpdateOne {
	_u.mutation.ClearSentiment()
	return _u
}

// SetSentimentScore sets the "sentiment_score" field.
func (_u *FeedbackRecordUpdateOne) SetSentimentScore(v float64) *FeedbackRecordUpdateOne {
	_u.mutation.ResetSentimentScore()
	_u.mutation.SetSentimentScore(v)
	return _u
}

// SetNillableSentimentScore sets the "sentiment_score" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableSentimentScore(v *float64) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetSentimentScore(*v)
	}
	return _u
}

// AddSentimentScore adds value to the "sentiment_score" field.
func (_u *FeedbackRecordUpdateOne) AddSentimentScore(v float64) *FeedbackRecordUpdateOne {
	_u.mutation.AddSentimentScore(v)
	return _u
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (_u *FeedbackRecordUpdateOne) ClearSentimentScore() *FeedbackRecordUpdateOne {
	_u.mutation.ClearSentimentScore()
	return _u
}

// SetEmotion sets the "emotion" field.
func (_u *FeedbackRecordUpdateOne) SetEmotion(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetEmotion(v)
	return _u
}

// SetNillableEmotion sets the "emotion" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableEmotion(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetEmotion(*v)
	}
	return _u
}

// ClearEmotion clears the value of the "emotion" field.
func (_u *FeedbackRecordUpdateOne) ClearEmotion() *FeedbackRecordUpdateOne {
	_u.mutation.ClearEmotion()
	return _u
}

// SetTopics sets the "topics" field.
func (_u *FeedbackRecordUpdateOne) SetTopics(v []string) *FeedbackRecordUpdateOne {
	_u.mutation.SetTopics(v)
	return _u
}

// AppendTopics appends value to the "topics" field.
func (_u *FeedbackRecordUpdateOne) AppendTopics(v []string) *FeedbackRecordUpdateOne {
	_u.mutation.AppendTopics(v)
	return _u
}

// ClearTopics clears the value of the "topics" field.
func (_u *FeedbackRecordUpdateOne) ClearTopics() *FeedbackRecordUpdateOne {
	_u.mutation.ClearTopics()
	return _u
}

// SetUserIdentifier sets the "user_identifier" field.
func (_u *FeedbackRecordUpdateOne) SetUserIdentifier(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetUserIdentifier(v)
	return _u
}

// SetNillableUserIdentifier sets the "user_identifier" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableUserIdentifier(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetUserIdentifier(*v)
	}
	return _u
}

// ClearUserIdentifier clears the value of the "user_identifier" field.
func (_u *FeedbackRecordUpdateOne) ClearUserIdentifier() *FeedbackRecordUpdateOne {
	_u.mutation.ClearUserIdentifier()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *FeedbackRecordUpdateOne) SetEmbedding(v pgvector.Vector) *FeedbackRecordUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableEmbedding(v *pgvector.Vector) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *FeedbackRecordUpdateOne) ClearEmbedding() *FeedbackRecordUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *FeedbackRecordUpdateOne) SetEmbeddingModel(v string) *FeedbackRecordUpdateOne {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *FeedbackRecordUpdateOne) SetNillableEmbeddingModel(v *string) *FeedbackRecordUpdateOne {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (_u *FeedbackRecordUpdateOne) ClearEmbeddingModel() *FeedbackRecordUpdateOne {
	_u.mutation.ClearEmbeddingModel()
	return _u
}

// Mutation returns the FeedbackRecordMutation object of the builder.
func (_u *FeedbackRecordUpdateOne) Mutation() *FeedbackRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the FeedbackRecordUpdate builder.
func (_u *FeedbackRecordUpdateOne) Where(ps ...predicate.FeedbackRecord) *FeedbackRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeedbackRecordUpdateOne) Select(field string, fields ...string) *FeedbackRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FeedbackRecord entity.
func (_u *FeedbackRecordUpdateOne) Save(ctx context.Context) (*FeedbackRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeedbackRecordUpdateOne) SaveX(ctx context.Context) *FeedbackRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeedbackRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeedbackRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FeedbackRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := feedbackrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeedbackRecordUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := feedbackrecord.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseID(); ok {
		if err := feedbackrecord.ResponseIDValidator(v); err != nil {
			return &ValidationError{Name: "response_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.response_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := feedbackrecord.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldID(); ok {
		if err := feedbackrecord.FieldIDValidator(v); err != nil {
			return &ValidationError{Name: "field_id", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.field_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldType(); ok {
		if err := feedbackrecord.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.field_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := feedbackrecord.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "FeedbackRecord.language": %w`, err)}
		}
	}
	return nil
}

func (_u *FeedbackRecordUpdateOne) sqlSave(ctx context.Context) (_node *FeedbackRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feedbackrecord.Table, feedbackrecord.Columns, sqlgraph.NewFieldSpec(feedbackrecord.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FeedbackRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feedbackrecord.FieldID)
		for _, f := range fields {
			if !feedbackrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feedbackrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(feedbackrecord.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feedbackrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(feedbackrecord.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(feedbackrecord.FieldTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseID(); ok {
		_spec.SetField(feedbackrecord.FieldResponseID, field.TypeString, value)
	}
	if _u.mutation.ResponseIDCleared() {
		_spec.ClearField(feedbackrecord.FieldResponseID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(feedbackrecord.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(feedbackrecord.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(feedbackrecord.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(feedbackrecord.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(feedbackrecord.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.FieldID(); ok {
		_spec.SetField(feedbackrecord.FieldFieldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FieldLabel(); ok {
		_spec.SetField(feedbackrecord.FieldFieldLabel, field.TypeString, value)
	}
	if _u.mutation.FieldLabelCleared() {
		_spec.ClearField(feedbackrecord.FieldFieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.FieldType(); ok {
		_spec.SetField(feedbackrecord.FieldFieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueText(); ok {
		_spec.SetField(feedbackrecord.FieldValueText, field.TypeString, value)
	}
	if _u.mutation.ValueTextCleared() {
		_spec.ClearField(feedbackrecord.FieldValueText, field.TypeString)
	}
	if value, ok := _u.mutation.ValueNumber(); ok {
		_spec.SetField(feedbackrecord.FieldValueNumber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValueNumber(); ok {
		_spec.AddField(feedbackrecord.FieldValueNumber, field.TypeFloat64, value)
	}
	if _u.mutation.ValueNumberCleared() {
		_spec.ClearField(feedbackrecord.FieldValueNumber, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ValueBoolean(); ok {
		_spec.SetField(feedbackrecord.FieldValueBoolean, field.TypeBool, value)
	}
	if _u.mutation.ValueBooleanCleared() {
		_spec.ClearField(feedbackrecord.FieldValueBoolean, field.TypeBool)
	}
	if value, ok := _u.mutation.ValueDate(); ok {
		_spec.SetField(feedbackrecord.FieldValueDate, field.TypeTime, value)
	}
	if _u.mutation.ValueDateCleared() {
		_spec.ClearField(feedbackrecord.FieldValueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ValueJSON(); ok {
		_spec.SetField(feedbackrecord.FieldValueJSON, field.TypeJSON, value)
	}
	if _u.mutation.ValueJSONCleared() {
		_spec.ClearField(feedbackrecord.FieldValueJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(feedbackrecord.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(feedbackrecord.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(feedbackrecord.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(feedbackrecord.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.Sentiment(); ok {
		_spec.SetField(feedbackrecord.FieldSentiment, field.TypeString, value)
	}
	if _u.mutation.SentimentCleared() {
		_spec.ClearField(feedbackrecord.FieldSentiment, field.TypeString)
	}
	if value, ok := _u.mutation.SentimentScore(); ok {
		_spec.SetField(feedbackrecord.FieldSentimentScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSentimentScore(); ok {
		_spec.AddField(feedbackrecord.FieldSentimentScore, field.TypeFloat64, value)
	}
	if _u.mutation.SentimentScoreCleared() {
		_spec.ClearField(feedbackrecord.FieldSentimentScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Emotion(); ok {
		_spec.SetField(feedbackrecord.FieldEmotion, field.TypeString, value)
	}
	if _u.mutation.EmotionCleared() {
		_spec.ClearField(feedbackrecord.FieldEmotion, field.TypeString)
	}
	if value, ok := _u.mutation.Topics(); ok {
		_spec.SetField(feedbackrecord.FieldTopics, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTopics(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, feedbackrecord.FieldTopics, value)
		})
	}
	if _u.mutation.TopicsCleared() {
		_spec.ClearField(feedbackrecord.FieldTopics, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserIdentifier(); ok {
		_spec.SetField(feedbackrecord.FieldUserIdentifier, field.TypeString, value)
	}
	if _u.mutation.UserIdentifierCleared() {
		_spec.ClearField(feedbackrecord.FieldUserIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(feedbackrecord.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(feedbackrecord.FieldEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(feedbackrecord.FieldEmbeddingModel, field.TypeString, value)
	}
	if _u.mutation.EmbeddingModelCleared() {
		_spec.ClearField(feedbackrecord.FieldEmbeddingModel, field.TypeString)
	}
	_node = &FeedbackRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feedbackrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
