// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/formbricks/hub/internal/ent/feedbackrecord"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

// FeedbackRecord is the model entity for the FeedbackRecord schema.
type FeedbackRecord struct {
	config `json:"-"`
	// ID of the ent.
	// UUIDv7 primary key (time-ordered)
	ID uuid.UUID `json:"id,omitempty"`
	// When the feedback was collected
	CollectedAt time.Time `json:"collected_at,omitempty"`
	// When this record was created in the database
	CreatedAt time.Time `json:"created_at,omitempty"`
	// When this record was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant/organization identifier for multi-tenancy (optional for self-hosted single-tenant deployments)
	TenantID string `json:"tenant_id,omitempty"`
	// Groups multiple answers from a single submission/session (e.g., all answers from one survey response)
	ResponseID string `json:"response_id,omitempty"`
	// Type of feedback source (e.g., survey, review, feedback_form, support, social)
	SourceType string `json:"source_type,omitempty"`
	// Reference to survey/form/ticket ID
	SourceID string `json:"source_id,omitempty"`
	// Human-readable name (e.g., 'Q1 NPS Survey')
	SourceName string `json:"source_name,omitempty"`
	// Identifier for the question/field being answered
	FieldID string `json:"field_id,omitempty"`
	// The actual question text (e.g., 'How satisfied are you?')
	FieldLabel string `json:"field_label,omitempty"`
	// Type of field: text (enrichable), categorical, nps, csat, ces, rating, number, boolean, date
	FieldType string `json:"field_type,omitempty"`
	// For open-ended text responses
	ValueText *string `json:"value_text,omitempty"`
	// For ratings, NPS scores, numeric responses
	ValueNumber *float64 `json:"value_number,omitempty"`
	// For yes/no questions
	ValueBoolean *bool `json:"value_boolean,omitempty"`
	// For date responses
	ValueDate *time.Time `json:"value_date,omitempty"`
	// For complex responses like multiple choice arrays
	ValueJSON map[string]interface{} `json:"value_json,omitempty"`
	// User agent, device, location, referrer, tags, custom fields, etc.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// ISO language code (e.g., 'en', 'de')
	Language string `json:"language,omitempty"`
	// AI-detected sentiment (positive, negative, neutral)
	Sentiment *string `json:"sentiment,omitempty"`
	// Sentiment score from -1 (negative) to +1 (positive)
	SentimentScore *float64 `json:"sentiment_score,omitempty"`
	// AI-detected emotion (joy, frustration, anger, etc.)
	Emotion *string `json:"emotion,omitempty"`
	// AI-extracted topics/themes from text
	Topics []string `json:"topics,omitempty"`
	// Anonymous ID or email hash for grouping responses
	UserIdentifier string `json:"user_identifier,omitempty"`
	// OpenAI embedding vector for semantic search (1536 dimensions for text-embedding-3-small)
	Embedding *pgvector.Vector `json:"embedding,omitempty"`
	// Name of the embedding model used (e.g., text-embedding-3-small)
	EmbeddingModel *string `json:"embedding_model,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FeedbackRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case feedbackrecord.FieldEmbedding:
			values[i] = &sql.NullScanner{S: new(pgvector.Vector)}
		case feedbackrecord.FieldValueJSON, feedbackrecord.FieldMetadata, feedbackrecord.FieldTopics:
			values[i] = new([]byte)
		case feedbackrecord.FieldValueBoolean:
			values[i] = new(sql.NullBool)
		case feedbackrecord.FieldValueNumber, feedbackrecord.FieldSentimentScore:
			values[i] = new(sql.NullFloat64)
		case feedbackrecord.FieldTenantID, feedbackrecord.FieldResponseID, feedbackrecord.FieldSourceType, feedbackrecord.FieldSourceID, feedbackrecord.FieldSourceName, feedbackrecord.FieldFieldID, feedbackrecord.FieldFieldLabel, feedbackrecord.FieldFieldType, feedbackrecord.FieldValueText, feedbackrecord.FieldLanguage, feedbackrecord.FieldSentiment, feedbackrecord.FieldEmotion, feedbackrecord.FieldUserIdentifier, feedbackrecord.FieldEmbeddingModel:
			values[i] = new(sql.NullString)
		case feedbackrecord.FieldCollectedAt, feedbackrecord.FieldCreatedAt, feedbackrecord.FieldUpdatedAt, feedbackrecord.FieldValueDate:
			values[i] = new(sql.NullTime)
		case feedbackrecord.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FeedbackRecord fields.
func (_m *FeedbackRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case feedbackrecord.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case feedbackrecord.FieldCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field collected_at", values[i])
			} else if value.Valid {
				_m.CollectedAt = value.Time
			}
		case feedbackrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case feedbackrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case feedbackrecord.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case feedbackrecord.FieldResponseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_id", values[i])
			} else if value.Valid {
				_m.ResponseID = value.String
			}
		case feedbackrecord.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case feedbackrecord.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case feedbackrecord.FieldSourceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_name", values[i])
			} else if value.Valid {
				_m.SourceName = value.String
			}
		case feedbackrecord.FieldFieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_id", values[i])
			} else if value.Valid {
				_m.FieldID = value.String
			}
		case feedbackrecord.FieldFieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_label", values[i])
			} else if value.Valid {
				_m.FieldLabel = value.String
			}
		case feedbackrecord.FieldFieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field field_type", values[i])
			} else if value.Valid {
				_m.FieldType = value.String
			}
		case feedbackrecord.FieldValueText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value_text", values[i])
			} else if value.Valid {
				_m.ValueText = new(string)
				*_m.ValueText = value.String
			}
		case feedbackrecord.FieldValueNumber:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value_number", values[i])
			} else if value.Valid {
				_m.ValueNumber = new(float64)
				*_m.ValueNumber = value.Float64
			}
		case feedbackrecord.FieldValueBoolean:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field value_boolean", values[i])
			} else if value.Valid {
				_m.ValueBoolean = new(bool)
				*_m.ValueBoolean = value.Bool
			}
		case feedbackrecord.FieldValueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field value_date", values[i])
			} else if value.Valid {
				_m.ValueDate = new(time.Time)
				*_m.ValueDate = value.Time
			}
		case feedbackrecord.FieldValueJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field value_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ValueJSON); err != nil {
					return fmt.Errorf("unmarshal field value_json: %w", err)
				}
			}
		case feedbackrecord.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case feedbackrecord.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case feedbackrecord.FieldSentiment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sentiment", values[i])
			} else if value.Valid {
				_m.Sentiment = new(string)
				*_m.Sentiment = value.String
			}
		case feedbackrecord.FieldSentimentScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field sentiment_score", values[i])
			} else if value.Valid {
				_m.SentimentScore = new(float64)
				*_m.SentimentScore = value.Float64
			}
		case feedbackrecord.FieldEmotion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field emotion", values[i])
			} else if value.Valid {
				_m.Emotion = new(string)
				*_m.Emotion = value.String
			}
		case feedbackrecord.FieldTopics:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field topics", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Topics); err != nil {
					return fmt.Errorf("unmarshal field topics: %w", err)
				}
			}
		case feedbackrecord.FieldUserIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_identifier", values[i])
			} else if value.Valid {
				_m.UserIdentifier = value.String
			}
		case feedbackrecord.FieldEmbedding:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value.Valid {
				_m.Embedding = new(pgvector.Vector)
				*_m.Embedding = *value.S.(*pgvector.Vector)
			}
		case feedbackrecord.FieldEmbeddingModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_model", values[i])
			} else if value.Valid {
				_m.EmbeddingModel = new(string)
				*_m.EmbeddingModel = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FeedbackRecord.
// This includes values selected through modifiers, order, etc.
func (_m *FeedbackRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FeedbackRecord.
// Note that you need to call FeedbackRecord.Unwrap() before calling this method if this FeedbackRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FeedbackRecord) Update() *FeedbackRecordUpdateOne {
	return NewFeedbackRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FeedbackRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FeedbackRecord) Unwrap() *FeedbackRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FeedbackRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FeedbackRecord) String() string {
	var builder strings.Builder
	builder.WriteString("FeedbackRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("collected_at=")
	builder.WriteString(_m.CollectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("response_id=")
	builder.WriteString(_m.ResponseID)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("source_name=")
	builder.WriteString(_m.SourceName)
	builder.WriteString(", ")
	builder.WriteString("field_id=")
	builder.WriteString(_m.FieldID)
	builder.WriteString(", ")
	builder.WriteString("field_label=")
	builder.WriteString(_m.FieldLabel)
	builder.WriteString(", ")
	builder.WriteString("field_type=")
	builder.WriteString(_m.FieldType)
	builder.WriteString(", ")
	if v := _m.ValueText; v != nil {
		builder.WriteString("value_text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ValueNumber; v != nil {
		builder.WriteString("value_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValueBoolean; v != nil {
		builder.WriteString("value_boolean=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValueDate; v != nil {
		builder.WriteString("value_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("value_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValueJSON))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	if v := _m.Sentiment; v != nil {
		builder.WriteString("sentiment=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SentimentScore; v != nil {
		builder.WriteString("sentiment_score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Emotion; v != nil {
		builder.WriteString("emotion=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("topics=")
	builder.WriteString(fmt.Sprintf("%v", _m.Topics))
	builder.WriteString(", ")
	builder.WriteString("user_identifier=")
	builder.WriteString(_m.UserIdentifier)
	builder.WriteString(", ")
	if v := _m.Embedding; v != nil {
		builder.WriteString("embedding=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EmbeddingModel; v != nil {
		builder.WriteString("embedding_model=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// FeedbackRecords is a parsable slice of FeedbackRecord.
type FeedbackRecords []*FeedbackRecord
