// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/formbricks/hub/internal/ent/enrichmentjob"
	"github.com/formbricks/hub/internal/ent/feedbackrecord"
	"github.com/formbricks/hub/internal/ent/predicate"
	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEnrichmentJob  = "EnrichmentJob"
	TypeFeedbackRecord = "FeedbackRecord"
)

// EnrichmentJobMutation represents an operation that mutates the EnrichmentJob nodes in the graph.
type EnrichmentJobMutation struct {
	config
	op                     Op
	typ                    string
	id                     *uuid.UUID
	job_type               *string
	status                 *string
	text                   *string
	error                  *string
	attempts               *int
	addattempts            *int
	created_at             *time.Time
	processed_at           *time.Time
	clearedFields          map[string]struct{}
	feedback_record        *uuid.UUID
	clearedfeedback_record bool
	done                   bool
	oldValue               func(context.Context) (*EnrichmentJob, error)
	predicates             []predicate.EnrichmentJob
}

var _ ent.Mutation = (*EnrichmentJobMutation)(nil)

// enrichmentjobOption allows management of the mutation configuration using functional options.
type enrichmentjobOption func(*EnrichmentJobMutation)

// newEnrichmentJobMutation creates new mutation for the EnrichmentJob entity.
func newEnrichmentJobMutation(c config, op Op, opts ...enrichmentjobOption) *EnrichmentJobMutation {
	m := &EnrichmentJobMutation{
		config:        c,
		op:            op,
		typ:           TypeEnrichmentJob,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEnrichmentJobID sets the ID field of the mutation.
func withEnrichmentJobID(id uuid.UUID) enrichmentjobOption {
	return func(m *EnrichmentJobMutation) {
		var (
			err   error
			once  sync.Once
			value *EnrichmentJob
		)
		m.oldValue = func(ctx context.Context) (*EnrichmentJob, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().EnrichmentJob.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEnrichmentJob sets the old EnrichmentJob of the mutation.
func withEnrichmentJob(node *EnrichmentJob) enrichmentjobOption {
	return func(m *EnrichmentJobMutation) {
		m.oldValue = func(context.Context) (*EnrichmentJob, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EnrichmentJobMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EnrichmentJobMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of EnrichmentJob entities.
func (m *EnrichmentJobMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EnrichmentJobMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EnrichmentJobMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().EnrichmentJob.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetFeedbackRecordID sets the "feedback_record_id" field.
func (m *EnrichmentJobMutation) SetFeedbackRecordID(u uuid.UUID) {
	m.feedback_record = &u
}

// FeedbackRecordID returns the value of the "feedback_record_id" field in the mutation.
func (m *EnrichmentJobMutation) FeedbackRecordID() (r uuid.UUID, exists bool) {
	v := m.feedback_record
	if v == nil {
		return
	}
	return *v, true
}

// OldFeedbackRecordID returns the old "feedback_record_id" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldFeedbackRecordID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFeedbackRecordID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFeedbackRecordID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFeedbackRecordID: %w", err)
	}
	return oldValue.FeedbackRecordID, nil
}

// ClearFeedbackRecordID clears the value of the "feedback_record_id" field.
func (m *EnrichmentJobMutation) ClearFeedbackRecordID() {
	m.feedback_record = nil
	m.clearedFields[enrichmentjob.FieldFeedbackRecordID] = struct{}{}
}

// FeedbackRecordIDCleared returns if the "feedback_record_id" field was cleared in this mutation.
func (m *EnrichmentJobMutation) FeedbackRecordIDCleared() bool {
	_, ok := m.clearedFields[enrichmentjob.FieldFeedbackRecordID]
	return ok
}

// ResetFeedbackRecordID resets all changes to the "feedback_record_id" field.
func (m *EnrichmentJobMutation) ResetFeedbackRecordID() {
	m.feedback_record = nil
	delete(m.clearedFields, enrichmentjob.FieldFeedbackRecordID)
}

// SetJobType sets the "job_type" field.
func (m *EnrichmentJobMutation) SetJobType(s string) {
	m.job_type = &s
}

// JobType returns the value of the "job_type" field in the mutation.
func (m *EnrichmentJobMutation) JobType() (r string, exists bool) {
	v := m.job_type
	if v == nil {
		return
	}
	return *v, true
}

// OldJobType returns the old "job_type" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldJobType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldJobType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldJobType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldJobType: %w", err)
	}
	return oldValue.JobType, nil
}

// ResetJobType resets all changes to the "job_type" field.
func (m *EnrichmentJobMutation) ResetJobType() {
	m.job_type = nil
}

// SetStatus sets the "status" field.
func (m *EnrichmentJobMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *EnrichmentJobMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *EnrichmentJobMutation) ResetStatus() {
	m.status = nil
}

// SetText sets the "text" field.
func (m *EnrichmentJobMutation) SetText(s string) {
	m.text = &s
}

// Text returns the value of the "text" field in the mutation.
func (m *EnrichmentJobMutation) Text() (r string, exists bool) {
	v := m.text
	if v == nil {
		return
	}
	return *v, true
}

// OldText returns the old "text" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldText(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldText is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldText requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldText: %w", err)
	}
	return oldValue.Text, nil
}

// ResetText resets all changes to the "text" field.
func (m *EnrichmentJobMutation) ResetText() {
	m.text = nil
}

// SetError sets the "error" field.
func (m *EnrichmentJobMutation) SetError(s string) {
	m.error = &s
}

// Error returns the value of the "error" field in the mutation.
func (m *EnrichmentJobMutation) Error() (r string, exists bool) {
	v := m.error
	if v == nil {
		return
	}
	return *v, true
}

// OldError returns the old "error" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldError(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldError: %w", err)
	}
	return oldValue.Error, nil
}

// ClearError clears the value of the "error" field.
func (m *EnrichmentJobMutation) ClearError() {
	m.error = nil
	m.clearedFields[enrichmentjob.FieldError] = struct{}{}
}

// ErrorCleared returns if the "error" field was cleared in this mutation.
func (m *EnrichmentJobMutation) ErrorCleared() bool {
	_, ok := m.clearedFields[enrichmentjob.FieldError]
	return ok
}

// ResetError resets all changes to the "error" field.
func (m *EnrichmentJobMutation) ResetError() {
	m.error = nil
	delete(m.clearedFields, enrichmentjob.FieldError)
}

// SetAttempts sets the "attempts" field.
func (m *EnrichmentJobMutation) SetAttempts(i int) {
	m.attempts = &i
	m.addattempts = nil
}

// Attempts returns the value of the "attempts" field in the mutation.
func (m *EnrichmentJobMutation) Attempts() (r int, exists bool) {
	v := m.attempts
	if v == nil {
		return
	}
	return *v, true
}

// OldAttempts returns the old "attempts" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldAttempts(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttempts is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttempts requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttempts: %w", err)
	}
	return oldValue.Attempts, nil
}

// AddAttempts adds i to the "attempts" field.
func (m *EnrichmentJobMutation) AddAttempts(i int) {
	if m.addattempts != nil {
		*m.addattempts += i
	} else {
		m.addattempts = &i
	}
}

// AddedAttempts returns the value that was added to the "attempts" field in this mutation.
func (m *EnrichmentJobMutation) AddedAttempts() (r int, exists bool) {
	v := m.addattempts
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttempts resets all changes to the "attempts" field.
func (m *EnrichmentJobMutation) ResetAttempts() {
	m.attempts = nil
	m.addattempts = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *EnrichmentJobMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *EnrichmentJobMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *EnrichmentJobMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetProcessedAt sets the "processed_at" field.
func (m *EnrichmentJobMutation) SetProcessedAt(t time.Time) {
	m.processed_at = &t
}

// ProcessedAt returns the value of the "processed_at" field in the mutation.
func (m *EnrichmentJobMutation) ProcessedAt() (r time.Time, exists bool) {
	v := m.processed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldProcessedAt returns the old "processed_at" field's value of the EnrichmentJob entity.
// If the EnrichmentJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EnrichmentJobMutation) OldProcessedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProcessedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProcessedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProcessedAt: %w", err)
	}
	return oldValue.ProcessedAt, nil
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (m *EnrichmentJobMutation) ClearProcessedAt() {
	m.processed_at = nil
	m.clearedFields[enrichmentjob.FieldProcessedAt] = struct{}{}
}

// ProcessedAtCleared returns if the "processed_at" field was cleared in this mutation.
func (m *EnrichmentJobMutation) ProcessedAtCleared() bool {
	_, ok := m.clearedFields[enrichmentjob.FieldProcessedAt]
	return ok
}

// ResetProcessedAt resets all changes to the "processed_at" field.
func (m *EnrichmentJobMutation) ResetProcessedAt() {
	m.processed_at = nil
	delete(m.clearedFields, enrichmentjob.FieldProcessedAt)
}

// ClearFeedbackRecord clears the "feedback_record" edge to the FeedbackRecord entity.
func (m *EnrichmentJobMutation) ClearFeedbackRecord() {
	m.clearedfeedback_record = true
	m.clearedFields[enrichmentjob.FieldFeedbackRecordID] = struct{}{}
}

// FeedbackRecordCleared reports if the "feedback_record" edge to the FeedbackRecord entity was cleared.
func (m *EnrichmentJobMutation) FeedbackRecordCleared() bool {
	return m.FeedbackRecordIDCleared() || m.clearedfeedback_record
}

// FeedbackRecordIDs returns the "feedback_record" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FeedbackRecordID instead. It exists only for internal usage by the builders.
func (m *EnrichmentJobMutation) FeedbackRecordIDs() (ids []uuid.UUID) {
	if id := m.feedback_record; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFeedbackRecord resets all changes to the "feedback_record" edge.
func (m *EnrichmentJobMutation) ResetFeedbackRecord() {
	m.feedback_record = nil
	m.clearedfeedback_record = false
}

// Where appends a list predicates to the EnrichmentJobMutation builder.
func (m *EnrichmentJobMutation) Where(ps ...predicate.EnrichmentJob) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EnrichmentJobMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EnrichmentJobMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.EnrichmentJob, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EnrichmentJobMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EnrichmentJobMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (EnrichmentJob).
func (m *EnrichmentJobMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EnrichmentJobMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.feedback_record != nil {
		fields = append(fields, enrichmentjob.FieldFeedbackRecordID)
	}
	if m.job_type != nil {
		fields = append(fields, enrichmentjob.FieldJobType)
	}
	if m.status != nil {
		fields = append(fields, enrichmentjob.FieldStatus)
	}
	if m.text != nil {
		fields = append(fields, enrichmentjob.FieldText)
	}
	if m.error != nil {
		fields = append(fields, enrichmentjob.FieldError)
	}
	if m.attempts != nil {
		fields = append(fields, enrichmentjob.FieldAttempts)
	}
	if m.created_at != nil {
		fields = append(fields, enrichmentjob.FieldCreatedAt)
	}
	if m.processed_at != nil {
		fields = append(fields, enrichmentjob.FieldProcessedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EnrichmentJobMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case enrichmentjob.FieldFeedbackRecordID:
		return m.FeedbackRecordID()
	case enrichmentjob.FieldJobType:
		return m.JobType()
	case enrichmentjob.FieldStatus:
		return m.Status()
	case enrichmentjob.FieldText:
		return m.Text()
	case enrichmentjob.FieldError:
		return m.Error()
	case enrichmentjob.FieldAttempts:
		return m.Attempts()
	case enrichmentjob.FieldCreatedAt:
		return m.CreatedAt()
	case enrichmentjob.FieldProcessedAt:
		return m.ProcessedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EnrichmentJobMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case enrichmentjob.FieldFeedbackRecordID:
		return m.OldFeedbackRecordID(ctx)
	case enrichmentjob.FieldJobType:
		return m.OldJobType(ctx)
	case enrichmentjob.FieldStatus:
		return m.OldStatus(ctx)
	case enrichmentjob.FieldText:
		return m.OldText(ctx)
	case enrichmentjob.FieldError:
		return m.OldError(ctx)
	case enrichmentjob.FieldAttempts:
		return m.OldAttempts(ctx)
	case enrichmentjob.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case enrichmentjob.FieldProcessedAt:
		return m.OldProcessedAt(ctx)
	}
	return nil, fmt.Errorf("unknown EnrichmentJob field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EnrichmentJobMutation) SetField(name string, value ent.Value) error {
	switch name {
	case enrichmentjob.FieldFeedbackRecordID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFeedbackRecordID(v)
		return nil
	case enrichmentjob.FieldJobType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJobType(v)
		return nil
	case enrichmentjob.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case enrichmentjob.FieldText:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetText(v)
		return nil
	case enrichmentjob.FieldError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetError(v)
		return nil
	case enrichmentjob.FieldAttempts:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttempts(v)
		return nil
	case enrichmentjob.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case enrichmentjob.FieldProcessedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProcessedAt(v)
		return nil
	}
	return fmt.Errorf("unknown EnrichmentJob field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EnrichmentJobMutation) AddedFields() []string {
	var fields []string
	if m.addattempts != nil {
		fields = append(fields, enrichmentjob.FieldAttempts)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EnrichmentJobMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case enrichmentjob.FieldAttempts:
		return m.AddedAttempts()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EnrichmentJobMutation) AddField(name string, value ent.Value) error {
	switch name {
	case enrichmentjob.FieldAttempts:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttempts(v)
		return nil
	}
	return fmt.Errorf("unknown EnrichmentJob numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EnrichmentJobMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(enrichmentjob.FieldFeedbackRecordID) {
		fields = append(fields, enrichmentjob.FieldFeedbackRecordID)
	}
	if m.FieldCleared(enrichmentjob.FieldError) {
		fields = append(fields, enrichmentjob.FieldError)
	}
	if m.FieldCleared(enrichmentjob.FieldProcessedAt) {
		fields = append(fields, enrichmentjob.FieldProcessedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EnrichmentJobMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EnrichmentJobMutation) ClearField(name string) error {
	switch name {
	case enrichmentjob.FieldFeedbackRecordID:
		m.ClearFeedbackRecordID()
		return nil
	case enrichmentjob.FieldError:
		m.ClearError()
		return nil
	case enrichmentjob.FieldProcessedAt:
		m.ClearProcessedAt()
		return nil
	}
	return fmt.Errorf("unknown EnrichmentJob nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EnrichmentJobMutation) ResetField(name string) error {
	switch name {
	case enrichmentjob.FieldFeedbackRecordID:
		m.ResetFeedbackRecordID()
		return nil
	case enrichmentjob.FieldJobType:
		m.ResetJobType()
		return nil
	case enrichmentjob.FieldStatus:
		m.ResetStatus()
		return nil
	case enrichmentjob.FieldText:
		m.ResetText()
		return nil
	case enrichmentjob.FieldError:
		m.ResetError()
		return nil
	case enrichmentjob.FieldAttempts:
		m.ResetAttempts()
		return nil
	case enrichmentjob.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case enrichmentjob.FieldProcessedAt:
		m.ResetProcessedAt()
		return nil
	}
	return fmt.Errorf("unknown EnrichmentJob field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EnrichmentJobMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.feedback_record != nil {
		edges = append(edges, enrichmentjob.EdgeFeedbackRecord)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EnrichmentJobMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case enrichmentjob.EdgeFeedbackRecord:
		if id := m.feedback_record; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EnrichmentJobMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EnrichmentJobMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EnrichmentJobMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedfeedback_record {
		edges = append(edges, enrichmentjob.EdgeFeedbackRecord)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EnrichmentJobMutation) EdgeCleared(name string) bool {
	switch name {
	case enrichmentjob.EdgeFeedbackRecord:
		return m.clearedfeedback_record
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EnrichmentJobMutation) ClearEdge(name string) error {
	switch name {
	case enrichmentjob.EdgeFeedbackRecord:
		m.ClearFeedbackRecord()
		return nil
	}
	return fmt.Errorf("unknown EnrichmentJob unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EnrichmentJobMutation) ResetEdge(name string) error {
	switch name {
	case enrichmentjob.EdgeFeedbackRecord:
		m.ResetFeedbackRecord()
		return nil
	}
	return fmt.Errorf("unknown EnrichmentJob edge %s", name)
}

// FeedbackRecordMutation represents an operation that mutates the FeedbackRecord nodes in the graph.
type FeedbackRecordMutation struct {
	config
	op                 Op
	typ                string
	id                 *uuid.UUID
	collected_at       *time.Time
	created_at         *time.Time
	updated_at         *time.Time
	tenant_id          *string
	response_id        *string
	source_type        *string
	source_id          *string
	source_name        *string
	field_id           *string
	field_label        *string
	field_type         *string
	value_text         *string
	value_number       *float64
	addvalue_number    *float64
	value_boolean      *bool
	value_date         *time.Time
	value_json         *map[string]interface{}
	metadata           *map[string]interface{}
	language           *string
	sentiment          *string
	sentiment_score    *float64
	addsentiment_score *float64
	emotion            *string
	topics             *[]string
	appendtopics       []string
	user_identifier    *string
	embedding          *pgvector.Vector
	embedding_model    *string
	clearedFields      map[string]struct{}
	done               bool
	oldValue           func(context.Context) (*FeedbackRecord, error)
	predicates         []predicate.FeedbackRecord
}

var _ ent.Mutation = (*FeedbackRecordMutation)(nil)

// feedbackrecordOption allows management of the mutation configuration using functional options.
type feedbackrecordOption func(*FeedbackRecordMutation)

// newFeedbackRecordMutation creates new mutation for the FeedbackRecord entity.
func newFeedbackRecordMutation(c config, op Op, opts ...feedbackrecordOption) *FeedbackRecordMutation {
	m := &FeedbackRecordMutation{
		config:        c,
		op:            op,
		typ:           TypeFeedbackRecord,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFeedbackRecordID sets the ID field of the mutation.
func withFeedbackRecordID(id uuid.UUID) feedbackrecordOption {
	return func(m *FeedbackRecordMutation) {
		var (
			err   error
			once  sync.Once
			value *FeedbackRecord
		)
		m.oldValue = func(ctx context.Context) (*FeedbackRecord, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().FeedbackRecord.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFeedbackRecord sets the old FeedbackRecord of the mutation.
func withFeedbackRecord(node *FeedbackRecord) feedbackrecordOption {
	return func(m *FeedbackRecordMutation) {
		m.oldValue = func(context.Context) (*FeedbackRecord, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FeedbackRecordMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FeedbackRecordMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of FeedbackRecord entities.
func (m *FeedbackRecordMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FeedbackRecordMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FeedbackRecordMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().FeedbackRecord.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCollectedAt sets the "collected_at" field.
func (m *FeedbackRecordMutation) SetCollectedAt(t time.Time) {
	m.collected_at = &t
}

// CollectedAt returns the value of the "collected_at" field in the mutation.
func (m *FeedbackRecordMutation) CollectedAt() (r time.Time, exists bool) {
	v := m.collected_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCollectedAt returns the old "collected_at" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldCollectedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCollectedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCollectedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCollectedAt: %w", err)
	}
	return oldValue.CollectedAt, nil
}

// ResetCollectedAt resets all changes to the "collected_at" field.
func (m *FeedbackRecordMutation) ResetCollectedAt() {
	m.collected_at = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *FeedbackRecordMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *FeedbackRecordMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *FeedbackRecordMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *FeedbackRecordMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *FeedbackRecordMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *FeedbackRecordMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTenantID sets the "tenant_id" field.
func (m *FeedbackRecordMutation) SetTenantID(s string) {
	m.tenant_id = &s
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *FeedbackRecordMutation) TenantID() (r string, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldTenantID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// ClearTenantID clears the value of the "tenant_id" field.
func (m *FeedbackRecordMutation) ClearTenantID() {
	m.tenant_id = nil
	m.clearedFields[feedbackrecord.FieldTenantID] = struct{}{}
}

// TenantIDCleared returns if the "tenant_id" field was cleared in this mutation.
func (m *FeedbackRecordMutation) TenantIDCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldTenantID]
	return ok
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *FeedbackRecordMutation) ResetTenantID() {
	m.tenant_id = nil
	delete(m.clearedFields, feedbackrecord.FieldTenantID)
}

// SetResponseID sets the "response_id" field.
func (m *FeedbackRecordMutation) SetResponseID(s string) {
	m.response_id = &s
}

// ResponseID returns the value of the "response_id" field in the mutation.
func (m *FeedbackRecordMutation) ResponseID() (r string, exists bool) {
	v := m.response_id
	if v == nil {
		return
	}
	return *v, true
}

// OldResponseID returns the old "response_id" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldResponseID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponseID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponseID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponseID: %w", err)
	}
	return oldValue.ResponseID, nil
}

// ClearResponseID clears the value of the "response_id" field.
func (m *FeedbackRecordMutation) ClearResponseID() {
	m.response_id = nil
	m.clearedFields[feedbackrecord.FieldResponseID] = struct{}{}
}

// ResponseIDCleared returns if the "response_id" field was cleared in this mutation.
func (m *FeedbackRecordMutation) ResponseIDCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldResponseID]
	return ok
}

// ResetResponseID resets all changes to the "response_id" field.
func (m *FeedbackRecordMutation) ResetResponseID() {
	m.response_id = nil
	delete(m.clearedFields, feedbackrecord.FieldResponseID)
}

// SetSourceType sets the "source_type" field.
func (m *FeedbackRecordMutation) SetSourceType(s string) {
	m.source_type = &s
}

// SourceType returns the value of the "source_type" field in the mutation.
func (m *FeedbackRecordMutation) SourceType() (r string, exists bool) {
	v := m.source_type
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceType returns the old "source_type" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldSourceType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceType: %w", err)
	}
	return oldValue.SourceType, nil
}

// ResetSourceType resets all changes to the "source_type" field.
func (m *FeedbackRecordMutation) ResetSourceType() {
	m.source_type = nil
}

// SetSourceID sets the "source_id" field.
func (m *FeedbackRecordMutation) SetSourceID(s string) {
	m.source_id = &s
}

// SourceID returns the value of the "source_id" field in the mutation.
func (m *FeedbackRecordMutation) SourceID() (r string, exists bool) {
	v := m.source_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceID returns the old "source_id" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldSourceID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceID: %w", err)
	}
	return oldValue.SourceID, nil
}

// ClearSourceID clears the value of the "source_id" field.
func (m *FeedbackRecordMutation) ClearSourceID() {
	m.source_id = nil
	m.clearedFields[feedbackrecord.FieldSourceID] = struct{}{}
}

// SourceIDCleared returns if the "source_id" field was cleared in this mutation.
func (m *FeedbackRecordMutation) SourceIDCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldSourceID]
	return ok
}

// ResetSourceID resets all changes to the "source_id" field.
func (m *FeedbackRecordMutation) ResetSourceID() {
	m.source_id = nil
	delete(m.clearedFields, feedbackrecord.FieldSourceID)
}

// SetSourceName sets the "source_name" field.
func (m *FeedbackRecordMutation) SetSourceName(s string) {
	m.source_name = &s
}

// SourceName returns the value of the "source_name" field in the mutation.
func (m *FeedbackRecordMutation) SourceName() (r string, exists bool) {
	v := m.source_name
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceName returns the old "source_name" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldSourceName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceName: %w", err)
	}
	return oldValue.SourceName, nil
}

// ClearSourceName clears the value of the "source_name" field.
func (m *FeedbackRecordMutation) ClearSourceName() {
	m.source_name = nil
	m.clearedFields[feedbackrecord.FieldSourceName] = struct{}{}
}

// SourceNameCleared returns if the "source_name" field was cleared in this mutation.
func (m *FeedbackRecordMutation) SourceNameCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldSourceName]
	return ok
}

// ResetSourceName resets all changes to the "source_name" field.
func (m *FeedbackRecordMutation) ResetSourceName() {
	m.source_name = nil
	delete(m.clearedFields, feedbackrecord.FieldSourceName)
}

// SetFieldID sets the "field_id" field.
func (m *FeedbackRecordMutation) SetFieldID(s string) {
	m.field_id = &s
}

// FieldID returns the value of the "field_id" field in the mutation.
func (m *FeedbackRecordMutation) FieldID() (r string, exists bool) {
	v := m.field_id
	if v == nil {
		return
	}
	return *v, true
}

// OldFieldID returns the old "field_id" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldFieldID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFieldID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFieldID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFieldID: %w", err)
	}
	return oldValue.FieldID, nil
}

// ResetFieldID resets all changes to the "field_id" field.
func (m *FeedbackRecordMutation) ResetFieldID() {
	m.field_id = nil
}

// SetFieldLabel sets the "field_label" field.
func (m *FeedbackRecordMutation) SetFieldLabel(s string) {
	m.field_label = &s
}

// FieldLabel returns the value of the "field_label" field in the mutation.
func (m *FeedbackRecordMutation) FieldLabel() (r string, exists bool) {
	v := m.field_label
	if v == nil {
		return
	}
	return *v, true
}

// OldFieldLabel returns the old "field_label" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldFieldLabel(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFieldLabel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFieldLabel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFieldLabel: %w", err)
	}
	return oldValue.FieldLabel, nil
}

// ClearFieldLabel clears the value of the "field_label" field.
func (m *FeedbackRecordMutation) ClearFieldLabel() {
	m.field_label = nil
	m.clearedFields[feedbackrecord.FieldFieldLabel] = struct{}{}
}

// FieldLabelCleared returns if the "field_label" field was cleared in this mutation.
func (m *FeedbackRecordMutation) FieldLabelCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldFieldLabel]
	return ok
}

// ResetFieldLabel resets all changes to the "field_label" field.
func (m *FeedbackRecordMutation) ResetFieldLabel() {
	m.field_label = nil
	delete(m.clearedFields, feedbackrecord.FieldFieldLabel)
}

// SetFieldType sets the "field_type" field.
func (m *FeedbackRecordMutation) SetFieldType(s string) {
	m.field_type = &s
}

// FieldType returns the value of the "field_type" field in the mutation.
func (m *FeedbackRecordMutation) FieldType() (r string, exists bool) {
	v := m.field_type
	if v == nil {
		return
	}
	return *v, true
}

// OldFieldType returns the old "field_type" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldFieldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFieldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFieldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFieldType: %w", err)
	}
	return oldValue.FieldType, nil
}

// ResetFieldType resets all changes to the "field_type" field.
func (m *FeedbackRecordMutation) ResetFieldType() {
	m.field_type = nil
}

// SetValueText sets the "value_text" field.
func (m *FeedbackRecordMutation) SetValueText(s string) {
	m.value_text = &s
}

// ValueText returns the value of the "value_text" field in the mutation.
func (m *FeedbackRecordMutation) ValueText() (r string, exists bool) {
	v := m.value_text
	if v == nil {
		return
	}
	return *v, true
}

// OldValueText returns the old "value_text" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldValueText(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValueText is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValueText requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValueText: %w", err)
	}
	return oldValue.ValueText, nil
}

// ClearValueText clears the value of the "value_text" field.
func (m *FeedbackRecordMutation) ClearValueText() {
	m.value_text = nil
	m.clearedFields[feedbackrecord.FieldValueText] = struct{}{}
}

// ValueTextCleared returns if the "value_text" field was cleared in this mutation.
func (m *FeedbackRecordMutation) ValueTextCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldValueText]
	return ok
}

// ResetValueText resets all changes to the "value_text" field.
func (m *FeedbackRecordMutation) ResetValueText() {
	m.value_text = nil
	delete(m.clearedFields, feedbackrecord.FieldValueText)
}

// SetValueNumber sets the "value_number" field.
func (m *FeedbackRecordMutation) SetValueNumber(f float64) {
	m.value_number = &f
	m.addvalue_number = nil
}

// ValueNumber returns the value of the "value_number" field in the mutation.
func (m *FeedbackRecordMutation) ValueNumber() (r float64, exists bool) {
	v := m.value_number
	if v == nil {
		return
	}
	return *v, true
}

// OldValueNumber returns the old "value_number" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldValueNumber(ctx context.Context) (v *float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValueNumber is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValueNumber requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValueNumber: %w", err)
	}
	return oldValue.ValueNumber, nil
}

// AddValueNumber adds f to the "value_number" field.
func (m *FeedbackRecordMutation) AddValueNumber(f float64) {
	if m.addvalue_number != nil {
		*m.addvalue_number += f
	} else {
		m.addvalue_number = &f
	}
}

// AddedValueNumber returns the value that was added to the "value_number" field in this mutation.
func (m *FeedbackRecordMutation) AddedValueNumber() (r float64, exists bool) {
	v := m.addvalue_number
	if v == nil {
		return
	}
	return *v, true
}

// ClearValueNumber clears the value of the "value_number" field.
func (m *FeedbackRecordMutation) ClearValueNumber() {
	m.value_number = nil
	m.addvalue_number = nil
	m.clearedFields[feedbackrecord.FieldValueNumber] = struct{}{}
}

// ValueNumberCleared returns if the "value_number" field was cleared in this mutation.
func (m *FeedbackRecordMutation) ValueNumberCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldValueNumber]
	return ok
}

// ResetValueNumber resets all changes to the "value_number" field.
func (m *FeedbackRecordMutation) ResetValueNumber() {
	m.value_number = nil
	m.addvalue_number = nil
	delete(m.clearedFields, feedbackrecord.FieldValueNumber)
}

// SetValueBoolean sets the "value_boolean" field.
func (m *FeedbackRecordMutation) SetValueBoolean(b bool) {
	m.value_boolean = &b
}

// ValueBoolean returns the value of the "value_boolean" field in the mutation.
func (m *FeedbackRecordMutation) ValueBoolean() (r bool, exists bool) {
	v := m.value_boolean
	if v == nil {
		return
	}
	return *v, true
}

// OldValueBoolean returns the old "value_boolean" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldValueBoolean(ctx context.Context) (v *bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValueBoolean is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValueBoolean requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValueBoolean: %w", err)
	}
	return oldValue.ValueBoolean, nil
}

// ClearValueBoolean clears the value of the "value_boolean" field.
func (m *FeedbackRecordMutation) ClearValueBoolean() {
	m.value_boolean = nil
	m.clearedFields[feedbackrecord.FieldValueBoolean] = struct{}{}
}

// ValueBooleanCleared returns if the "value_boolean" field was cleared in this mutation.
func (m *FeedbackRecordMutation) ValueBooleanCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldValueBoolean]
	return ok
}

// ResetValueBoolean resets all changes to the "value_boolean" field.
func (m *FeedbackRecordMutation) ResetValueBoolean() {
	m.value_boolean = nil
	delete(m.clearedFields, feedbackrecord.FieldValueBoolean)
}

// SetValueDate sets the "value_date" field.
func (m *FeedbackRecordMutation) SetValueDate(t time.Time) {
	m.value_date = &t
}

// ValueDate returns the value of the "value_date" field in the mutation.
func (m *FeedbackRecordMutation) ValueDate() (r time.Time, exists bool) {
	v := m.value_date
	if v == nil {
		return
	}
	return *v, true
}

// OldValueDate returns the old "value_date" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldValueDate(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValueDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValueDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValueDate: %w", err)
	}
	return oldValue.ValueDate, nil
}

// ClearValueDate clears the value of the "value_date" field.
func (m *FeedbackRecordMutation) ClearValueDate() {
	m.value_date = nil
	m.clearedFields[feedbackrecord.FieldValueDate] = struct{}{}
}

// ValueDateCleared returns if the "value_date" field was cleared in this mutation.
func (m *FeedbackRecordMutation) ValueDateCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldValueDate]
	return ok
}

// ResetValueDate resets all changes to the "value_date" field.
func (m *FeedbackRecordMutation) ResetValueDate() {
	m.value_date = nil
	delete(m.clearedFields, feedbackrecord.FieldValueDate)
}

// SetValueJSON sets the "value_json" field.
func (m *FeedbackRecordMutation) SetValueJSON(value map[string]interface{}) {
	m.value_json = &value
}

// ValueJSON returns the value of the "value_json" field in the mutation.
func (m *FeedbackRecordMutation) ValueJSON() (r map[string]interface{}, exists bool) {
	v := m.value_json
	if v == nil {
		return
	}
	return *v, true
}

// OldValueJSON returns the old "value_json" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldValueJSON(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValueJSON is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValueJSON requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValueJSON: %w", err)
	}
	return oldValue.ValueJSON, nil
}

// ClearValueJSON clears the value of the "value_json" field.
func (m *FeedbackRecordMutation) ClearValueJSON() {
	m.value_json = nil
	m.clearedFields[feedbackrecord.FieldValueJSON] = struct{}{}
}

// ValueJSONCleared returns if the "value_json" field was cleared in this mutation.
func (m *FeedbackRecordMutation) ValueJSONCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldValueJSON]
	return ok
}

// ResetValueJSON resets all changes to the "value_json" field.
func (m *FeedbackRecordMutation) ResetValueJSON() {
	m.value_json = nil
	delete(m.clearedFields, feedbackrecord.FieldValueJSON)
}

// SetMetadata sets the "metadata" field.
func (m *FeedbackRecordMutation) SetMetadata(value map[string]interface{}) {
	m.metadata = &value
}

// Metadata returns the value of the "metadata" field in the mutation.
func (m *FeedbackRecordMutation) Metadata() (r map[string]interface{}, exists bool) {
	v := m.metadata
	if v == nil {
		return
	}
	return *v, true
}

// OldMetadata returns the old "metadata" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldMetadata(ctx context.Context) (v map[string]interface{}, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMetadata is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMetadata requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMetadata: %w", err)
	}
	return oldValue.Metadata, nil
}

// ClearMetadata clears the value of the "metadata" field.
func (m *FeedbackRecordMutation) ClearMetadata() {
	m.metadata = nil
	m.clearedFields[feedbackrecord.FieldMetadata] = struct{}{}
}

// MetadataCleared returns if the "metadata" field was cleared in this mutation.
func (m *FeedbackRecordMutation) MetadataCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldMetadata]
	return ok
}

// ResetMetadata resets all changes to the "metadata" field.
func (m *FeedbackRecordMutation) ResetMetadata() {
	m.metadata = nil
	delete(m.clearedFields, feedbackrecord.FieldMetadata)
}

// SetLanguage sets the "language" field.
func (m *FeedbackRecordMutation) SetLanguage(s string) {
	m.language = &s
}

// Language returns the value of the "language" field in the mutation.
func (m *FeedbackRecordMutation) Language() (r string, exists bool) {
	v := m.language
	if v == nil {
		return
	}
	return *v, true
}

// OldLanguage returns the old "language" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldLanguage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLanguage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLanguage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLanguage: %w", err)
	}
	return oldValue.Language, nil
}

// ClearLanguage clears the value of the "language" field.
func (m *FeedbackRecordMutation) ClearLanguage() {
	m.language = nil
	m.clearedFields[feedbackrecord.FieldLanguage] = struct{}{}
}

// LanguageCleared returns if the "language" field was cleared in this mutation.
func (m *FeedbackRecordMutation) LanguageCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldLanguage]
	return ok
}

// ResetLanguage resets all changes to the "language" field.
func (m *FeedbackRecordMutation) ResetLanguage() {
	m.language = nil
	delete(m.clearedFields, feedbackrecord.FieldLanguage)
}

// SetSentiment sets the "sentiment" field.
func (m *FeedbackRecordMutation) SetSentiment(s string) {
	m.sentiment = &s
}

// Sentiment returns the value of the "sentiment" field in the mutation.
func (m *FeedbackRecordMutation) Sentiment() (r string, exists bool) {
	v := m.sentiment
	if v == nil {
		return
	}
	return *v, true
}

// OldSentiment returns the old "sentiment" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldSentiment(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSentiment is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSentiment requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSentiment: %w", err)
	}
	return oldValue.Sentiment, nil
}

// ClearSentiment clears the value of the "sentiment" field.
func (m *FeedbackRecordMutation) ClearSentiment() {
	m.sentiment = nil
	m.clearedFields[feedbackrecord.FieldSentiment] = struct{}{}
}

// SentimentCleared returns if the "sentiment" field was cleared in this mutation.
func (m *FeedbackRecordMutation) SentimentCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldSentiment]
	return ok
}

// ResetSentiment resets all changes to the "sentiment" field.
func (m *FeedbackRecordMutation) ResetSentiment() {
	m.sentiment = nil
	delete(m.clearedFields, feedbackrecord.FieldSentiment)
}

// SetSentimentScore sets the "sentiment_score" field.
func (m *FeedbackRecordMutation) SetSentimentScore(f float64) {
	m.sentiment_score = &f
	m.addsentiment_score = nil
}

// SentimentScore returns the value of the "sentiment_score" field in the mutation.
func (m *FeedbackRecordMutation) SentimentScore() (r float64, exists bool) {
	v := m.sentiment_score
	if v == nil {
		return
	}
	return *v, true
}

// OldSentimentScore returns the old "sentiment_score" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldSentimentScore(ctx context.Context) (v *float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSentimentScore is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSentimentScore requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSentimentScore: %w", err)
	}
	return oldValue.SentimentScore, nil
}

// AddSentimentScore adds f to the "sentiment_score" field.
func (m *FeedbackRecordMutation) AddSentimentScore(f float64) {
	if m.addsentiment_score != nil {
		*m.addsentiment_score += f
	} else {
		m.addsentiment_score = &f
	}
}

// AddedSentimentScore returns the value that was added to the "sentiment_score" field in this mutation.
func (m *FeedbackRecordMutation) AddedSentimentScore() (r float64, exists bool) {
	v := m.addsentiment_score
	if v == nil {
		return
	}
	return *v, true
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (m *FeedbackRecordMutation) ClearSentimentScore() {
	m.sentiment_score = nil
	m.addsentiment_score = nil
	m.clearedFields[feedbackrecord.FieldSentimentScore] = struct{}{}
}

// SentimentScoreCleared returns if the "sentiment_score" field was cleared in this mutation.
func (m *FeedbackRecordMutation) SentimentScoreCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldSentimentScore]
	return ok
}

// ResetSentimentScore resets all changes to the "sentiment_score" field.
func (m *FeedbackRecordMutation) ResetSentimentScore() {
	m.sentiment_score = nil
	m.addsentiment_score = nil
	delete(m.clearedFields, feedbackrecord.FieldSentimentScore)
}

// SetEmotion sets the "emotion" field.
func (m *FeedbackRecordMutation) SetEmotion(s string) {
	m.emotion = &s
}

// Emotion returns the value of the "emotion" field in the mutation.
func (m *FeedbackRecordMutation) Emotion() (r string, exists bool) {
	v := m.emotion
	if v == nil {
		return
	}
	return *v, true
}

// OldEmotion returns the old "emotion" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldEmotion(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmotion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmotion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmotion: %w", err)
	}
	return oldValue.Emotion, nil
}

// ClearEmotion clears the value of the "emotion" field.
func (m *FeedbackRecordMutation) ClearEmotion() {
	m.emotion = nil
	m.clearedFields[feedbackrecord.FieldEmotion] = struct{}{}
}

// EmotionCleared returns if the "emotion" field was cleared in this mutation.
func (m *FeedbackRecordMutation) EmotionCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldEmotion]
	return ok
}

// ResetEmotion resets all changes to the "emotion" field.
func (m *FeedbackRecordMutation) ResetEmotion() {
	m.emotion = nil
	delete(m.clearedFields, feedbackrecord.FieldEmotion)
}

// SetTopics sets the "topics" field.
func (m *FeedbackRecordMutation) SetTopics(s []string) {
	m.topics = &s
	m.appendtopics = nil
}

// Topics returns the value of the "topics" field in the mutation.
func (m *FeedbackRecordMutation) Topics() (r []string, exists bool) {
	v := m.topics
	if v == nil {
		return
	}
	return *v, true
}

// OldTopics returns the old "topics" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldTopics(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTopics is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTopics requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTopics: %w", err)
	}
	return oldValue.Topics, nil
}

// AppendTopics adds s to the "topics" field.
func (m *FeedbackRecordMutation) AppendTopics(s []string) {
	m.appendtopics = append(m.appendtopics, s...)
}

// AppendedTopics returns the list of values that were appended to the "topics" field in this mutation.
func (m *FeedbackRecordMutation) AppendedTopics() ([]string, bool) {
	if len(m.appendtopics) == 0 {
		return nil, false
	}
	return m.appendtopics, true
}

// ClearTopics clears the value of the "topics" field.
func (m *FeedbackRecordMutation) ClearTopics() {
	m.topics = nil
	m.appendtopics = nil
	m.clearedFields[feedbackrecord.FieldTopics] = struct{}{}
}

// TopicsCleared returns if the "topics" field was cleared in this mutation.
func (m *FeedbackRecordMutation) TopicsCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldTopics]
	return ok
}

// ResetTopics resets all changes to the "topics" field.
func (m *FeedbackRecordMutation) ResetTopics() {
	m.topics = nil
	m.appendtopics = nil
	delete(m.clearedFields, feedbackrecord.FieldTopics)
}

// SetUserIdentifier sets the "user_identifier" field.
func (m *FeedbackRecordMutation) SetUserIdentifier(s string) {
	m.user_identifier = &s
}

// UserIdentifier returns the value of the "user_identifier" field in the mutation.
func (m *FeedbackRecordMutation) UserIdentifier() (r string, exists bool) {
	v := m.user_identifier
	if v == nil {
		return
	}
	return *v, true
}

// OldUserIdentifier returns the old "user_identifier" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldUserIdentifier(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserIdentifier is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserIdentifier requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserIdentifier: %w", err)
	}
	return oldValue.UserIdentifier, nil
}

// ClearUserIdentifier clears the value of the "user_identifier" field.
func (m *FeedbackRecordMutation) ClearUserIdentifier() {
	m.user_identifier = nil
	m.clearedFields[feedbackrecord.FieldUserIdentifier] = struct{}{}
}

// UserIdentifierCleared returns if the "user_identifier" field was cleared in this mutation.
func (m *FeedbackRecordMutation) UserIdentifierCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldUserIdentifier]
	return ok
}

// ResetUserIdentifier resets all changes to the "user_identifier" field.
func (m *FeedbackRecordMutation) ResetUserIdentifier() {
	m.user_identifier = nil
	delete(m.clearedFields, feedbackrecord.FieldUserIdentifier)
}

// SetEmbedding sets the "embedding" field.
func (m *FeedbackRecordMutation) SetEmbedding(pg pgvector.Vector) {
	m.embedding = &pg
}

// Embedding returns the value of the "embedding" field in the mutation.
func (m *FeedbackRecordMutation) Embedding() (r pgvector.Vector, exists bool) {
	v := m.embedding
	if v == nil {
		return
	}
	return *v, true
}

// OldEmbedding returns the old "embedding" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldEmbedding(ctx context.Context) (v *pgvector.Vector, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmbedding is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmbedding requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmbedding: %w", err)
	}
	return oldValue.Embedding, nil
}

// ClearEmbedding clears the value of the "embedding" field.
func (m *FeedbackRecordMutation) ClearEmbedding() {
	m.embedding = nil
	m.clearedFields[feedbackrecord.FieldEmbedding] = struct{}{}
}

// EmbeddingCleared returns if the "embedding" field was cleared in this mutation.
func (m *FeedbackRecordMutation) EmbeddingCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldEmbedding]
	return ok
}

// ResetEmbedding resets all changes to the "embedding" field.
func (m *FeedbackRecordMutation) ResetEmbedding() {
	m.embedding = nil
	delete(m.clearedFields, feedbackrecord.FieldEmbedding)
}

// SetEmbeddingModel sets the "embedding_model" field.
func (m *FeedbackRecordMutation) SetEmbeddingModel(s string) {
	m.embedding_model = &s
}

// EmbeddingModel returns the value of the "embedding_model" field in the mutation.
func (m *FeedbackRecordMutation) EmbeddingModel() (r string, exists bool) {
	v := m.embedding_model
	if v == nil {
		return
	}
	return *v, true
}

// OldEmbeddingModel returns the old "embedding_model" field's value of the FeedbackRecord entity.
// If the FeedbackRecord object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FeedbackRecordMutation) OldEmbeddingModel(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmbeddingModel is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmbeddingModel requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmbeddingModel: %w", err)
	}
	return oldValue.EmbeddingModel, nil
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (m *FeedbackRecordMutation) ClearEmbeddingModel() {
	m.embedding_model = nil
	m.clearedFields[feedbackrecord.FieldEmbeddingModel] = struct{}{}
}

// EmbeddingModelCleared returns if the "embedding_model" field was cleared in this mutation.
func (m *FeedbackRecordMutation) EmbeddingModelCleared() bool {
	_, ok := m.clearedFields[feedbackrecord.FieldEmbeddingModel]
	return ok
}

// ResetEmbeddingModel resets all changes to the "embedding_model" field.
func (m *FeedbackRecordMutation) ResetEmbeddingModel() {
	m.embedding_model = nil
	delete(m.clearedFields, feedbackrecord.FieldEmbeddingModel)
}

// Where appends a list predicates to the FeedbackRecordMutation builder.
func (m *FeedbackRecordMutation) Where(ps ...predicate.FeedbackRecord) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FeedbackRecordMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FeedbackRecordMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.FeedbackRecord, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FeedbackRecordMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FeedbackRecordMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (FeedbackRecord).
func (m *FeedbackRecordMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FeedbackRecordMutation) Fields() []string {
	fields := make([]string, 0, 25)
	if m.collected_at != nil {
		fields = append(fields, feedbackrecord.FieldCollectedAt)
	}
	if m.created_at != nil {
		fields = append(fields, feedbackrecord.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, feedbackrecord.FieldUpdatedAt)
	}
	if m.tenant_id != nil {
		fields = append(fields, feedbackrecord.FieldTenantID)
	}
	if m.response_id != nil {
		fields = append(fields, feedbackrecord.FieldResponseID)
	}
	if m.source_type != nil {
		fields = append(fields, feedbackrecord.FieldSourceType)
	}
	if m.source_id != nil {
		fields = append(fields, feedbackrecord.FieldSourceID)
	}
	if m.source_name != nil {
		fields = append(fields, feedbackrecord.FieldSourceName)
	}
	if m.field_id != nil {
		fields = append(fields, feedbackrecord.FieldFieldID)
	}
	if m.field_label != nil {
		fields = append(fields, feedbackrecord.FieldFieldLabel)
	}
	if m.field_type != nil {
		fields = append(fields, feedbackrecord.FieldFieldType)
	}
	if m.value_text != nil {
		fields = append(fields, feedbackrecord.FieldValueText)
	}
	if m.value_number != nil {
		fields = append(fields, feedbackrecord.FieldValueNumber)
	}
	if m.value_boolean != nil {
		fields = append(fields, feedbackrecord.FieldValueBoolean)
	}
	if m.value_date != nil {
		fields = append(fields, feedbackrecord.FieldValueDate)
	}
	if m.value_json != nil {
		fields = append(fields, feedbackrecord.FieldValueJSON)
	}
	if m.metadata != nil {
		fields = append(fields, feedbackrecord.FieldMetadata)
	}
	if m.language != nil {
		fields = append(fields, feedbackrecord.FieldLanguage)
	}
	if m.sentiment != nil {
		fields = append(fields, feedbackrecord.FieldSentiment)
	}
	if m.sentiment_score != nil {
		fields = append(fields, feedbackrecord.FieldSentimentScore)
	}
	if m.emotion != nil {
		fields = append(fields, feedbackrecord.FieldEmotion)
	}
	if m.topics != nil {
		fields = append(fields, feedbackrecord.FieldTopics)
	}
	if m.user_identifier != nil {
		fields = append(fields, feedbackrecord.FieldUserIdentifier)
	}
	if m.embedding != nil {
		fields = append(fields, feedbackrecord.FieldEmbedding)
	}
	if m.embedding_model != nil {
		fields = append(fields, feedbackrecord.FieldEmbeddingModel)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FeedbackRecordMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case feedbackrecord.FieldCollectedAt:
		return m.CollectedAt()
	case feedbackrecord.FieldCreatedAt:
		return m.CreatedAt()
	case feedbackrecord.FieldUpdatedAt:
		return m.UpdatedAt()
	case feedbackrecord.FieldTenantID:
		return m.TenantID()
	case feedbackrecord.FieldResponseID:
		return m.ResponseID()
	case feedbackrecord.FieldSourceType:
		return m.SourceType()
	case feedbackrecord.FieldSourceID:
		return m.SourceID()
	case feedbackrecord.FieldSourceName:
		return m.SourceName()
	case feedbackrecord.FieldFieldID:
		return m.FieldID()
	case feedbackrecord.FieldFieldLabel:
		return m.FieldLabel()
	case feedbackrecord.FieldFieldType:
		return m.FieldType()
	case feedbackrecord.FieldValueText:
		return m.ValueText()
	case feedbackrecord.FieldValueNumber:
		return m.ValueNumber()
	case feedbackrecord.FieldValueBoolean:
		return m.ValueBoolean()
	case feedbackrecord.FieldValueDate:
		return m.ValueDate()
	case feedbackrecord.FieldValueJSON:
		return m.ValueJSON()
	case feedbackrecord.FieldMetadata:
		return m.Metadata()
	case feedbackrecord.FieldLanguage:
		return m.Language()
	case feedbackrecord.FieldSentiment:
		return m.Sentiment()
	case feedbackrecord.FieldSentimentScore:
		return m.SentimentScore()
	case feedbackrecord.FieldEmotion:
		return m.Emotion()
	case feedbackrecord.FieldTopics:
		return m.Topics()
	case feedbackrecord.FieldUserIdentifier:
		return m.UserIdentifier()
	case feedbackrecord.FieldEmbedding:
		return m.Embedding()
	case feedbackrecord.FieldEmbeddingModel:
		return m.EmbeddingModel()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FeedbackRecordMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case feedbackrecord.FieldCollectedAt:
		return m.OldCollectedAt(ctx)
	case feedbackrecord.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case feedbackrecord.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case feedbackrecord.FieldTenantID:
		return m.OldTenantID(ctx)
	case feedbackrecord.FieldResponseID:
		return m.OldResponseID(ctx)
	case feedbackrecord.FieldSourceType:
		return m.OldSourceType(ctx)
	case feedbackrecord.FieldSourceID:
		return m.OldSourceID(ctx)
	case feedbackrecord.FieldSourceName:
		return m.OldSourceName(ctx)
	case feedbackrecord.FieldFieldID:
		return m.OldFieldID(ctx)
	case feedbackrecord.FieldFieldLabel:
		return m.OldFieldLabel(ctx)
	case feedbackrecord.FieldFieldType:
		return m.OldFieldType(ctx)
	case feedbackrecord.FieldValueText:
		return m.OldValueText(ctx)
	case feedbackrecord.FieldValueNumber:
		return m.OldValueNumber(ctx)
	case feedbackrecord.FieldValueBoolean:
		return m.OldValueBoolean(ctx)
	case feedbackrecord.FieldValueDate:
		return m.OldValueDate(ctx)
	case feedbackrecord.FieldValueJSON:
		return m.OldValueJSON(ctx)
	case feedbackrecord.FieldMetadata:
		return m.OldMetadata(ctx)
	case feedbackrecord.FieldLanguage:
		return m.OldLanguage(ctx)
	case feedbackrecord.FieldSentiment:
		return m.OldSentiment(ctx)
	case feedbackrecord.FieldSentimentScore:
		return m.OldSentimentScore(ctx)
	case feedbackrecord.FieldEmotion:
		return m.OldEmotion(ctx)
	case feedbackrecord.FieldTopics:
		return m.OldTopics(ctx)
	case feedbackrecord.FieldUserIdentifier:
		return m.OldUserIdentifier(ctx)
	case feedbackrecord.FieldEmbedding:
		return m.OldEmbedding(ctx)
	case feedbackrecord.FieldEmbeddingModel:
		return m.OldEmbeddingModel(ctx)
	}
	return nil, fmt.Errorf("unknown FeedbackRecord field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FeedbackRecordMutation) SetField(name string, value ent.Value) error {
	switch name {
	case feedbackrecord.FieldCollectedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCollectedAt(v)
		return nil
	case feedbackrecord.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case feedbackrecord.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case feedbackrecord.FieldTenantID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case feedbackrecord.FieldResponseID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponseID(v)
		return nil
	case feedbackrecord.FieldSourceType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceType(v)
		return nil
	case feedbackrecord.FieldSourceID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceID(v)
		return nil
	case feedbackrecord.FieldSourceName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceName(v)
		return nil
	case feedbackrecord.FieldFieldID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFieldID(v)
		return nil
	case feedbackrecord.FieldFieldLabel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFieldLabel(v)
		return nil
	case feedbackrecord.FieldFieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFieldType(v)
		return nil
	case feedbackrecord.FieldValueText:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValueText(v)
		return nil
	case feedbackrecord.FieldValueNumber:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValueNumber(v)
		return nil
	case feedbackrecord.FieldValueBoolean:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValueBoolean(v)
		return nil
	case feedbackrecord.FieldValueDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValueDate(v)
		return nil
	case feedbackrecord.FieldValueJSON:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValueJSON(v)
		return nil
	case feedbackrecord.FieldMetadata:
		v, ok := value.(map[string]interface{})
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMetadata(v)
		return nil
	case feedbackrecord.FieldLanguage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLanguage(v)
		return nil
	case feedbackrecord.FieldSentiment:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSentiment(v)
		return nil
	case feedbackrecord.FieldSentimentScore:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSentimentScore(v)
		return nil
	case feedbackrecord.FieldEmotion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmotion(v)
		return nil
	case feedbackrecord.FieldTopics:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTopics(v)
		return nil
	case feedbackrecord.FieldUserIdentifier:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserIdentifier(v)
		return nil
	case feedbackrecord.FieldEmbedding:
		v, ok := value.(pgvector.Vector)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmbedding(v)
		return nil
	case feedbackrecord.FieldEmbeddingModel:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmbeddingModel(v)
		return nil
	}
	return fmt.Errorf("unknown FeedbackRecord field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FeedbackRecordMutation) AddedFields() []string {
	var fields []string
	if m.addvalue_number != nil {
		fields = append(fields, feedbackrecord.FieldValueNumber)
	}
	if m.addsentiment_score != nil {
		fields = append(fields, feedbackrecord.FieldSentimentScore)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FeedbackRecordMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case feedbackrecord.FieldValueNumber:
		return m.AddedValueNumber()
	case feedbackrecord.FieldSentimentScore:
		return m.AddedSentimentScore()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FeedbackRecordMutation) AddField(name string, value ent.Value) error {
	switch name {
	case feedbackrecord.FieldValueNumber:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValueNumber(v)
		return nil
	case feedbackrecord.FieldSentimentScore:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSentimentScore(v)
		return nil
	}
	return fmt.Errorf("unknown FeedbackRecord numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FeedbackRecordMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(feedbackrecord.FieldTenantID) {
		fields = append(fields, feedbackrecord.FieldTenantID)
	}
	if m.FieldCleared(feedbackrecord.FieldResponseID) {
		fields = append(fields, feedbackrecord.FieldResponseID)
	}
	if m.FieldCleared(feedbackrecord.FieldSourceID) {
		fields = append(fields, feedbackrecord.FieldSourceID)
	}
	if m.FieldCleared(feedbackrecord.FieldSourceName) {
		fields = append(fields, feedbackrecord.FieldSourceName)
	}
	if m.FieldCleared(feedbackrecord.FieldFieldLabel) {
		fields = append(fields, feedbackrecord.FieldFieldLabel)
	}
	if m.FieldCleared(feedbackrecord.FieldValueText) {
		fields = append(fields, feedbackrecord.FieldValueText)
	}
	if m.FieldCleared(feedbackrecord.FieldValueNumber) {
		fields = append(fields, feedbackrecord.FieldValueNumber)
	}
	if m.FieldCleared(feedbackrecord.FieldValueBoolean) {
		fields = append(fields, feedbackrecord.FieldValueBoolean)
	}
	if m.FieldCleared(feedbackrecord.FieldValueDate) {
		fields = append(fields, feedbackrecord.FieldValueDate)
	}
	if m.FieldCleared(feedbackrecord.FieldValueJSON) {
		fields = append(fields, feedbackrecord.FieldValueJSON)
	}
	if m.FieldCleared(feedbackrecord.FieldMetadata) {
		fields = append(fields, feedbackrecord.FieldMetadata)
	}
	if m.FieldCleared(feedbackrecord.FieldLanguage) {
		fields = append(fields, feedbackrecord.FieldLanguage)
	}
	if m.FieldCleared(feedbackrecord.FieldSentiment) {
		fields = append(fields, feedbackrecord.FieldSentiment)
	}
	if m.FieldCleared(feedbackrecord.FieldSentimentScore) {
		fields = append(fields, feedbackrecord.FieldSentimentScore)
	}
	if m.FieldCleared(feedbackrecord.FieldEmotion) {
		fields = append(fields, feedbackrecord.FieldEmotion)
	}
	if m.FieldCleared(feedbackrecord.FieldTopics) {
		fields = append(fields, feedbackrecord.FieldTopics)
	}
	if m.FieldCleared(feedbackrecord.FieldUserIdentifier) {
		fields = append(fields, feedbackrecord.FieldUserIdentifier)
	}
	if m.FieldCleared(feedbackrecord.FieldEmbedding) {
		fields = append(fields, feedbackrecord.FieldEmbedding)
	}
	if m.FieldCleared(feedbackrecord.FieldEmbeddingModel) {
		fields = append(fields, feedbackrecord.FieldEmbeddingModel)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FeedbackRecordMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FeedbackRecordMutation) ClearField(name string) error {
	switch name {
	case feedbackrecord.FieldTenantID:
		m.ClearTenantID()
		return nil
	case feedbackrecord.FieldResponseID:
		m.ClearResponseID()
		return nil
	case feedbackrecord.FieldSourceID:
		m.ClearSourceID()
		return nil
	case feedbackrecord.FieldSourceName:
		m.ClearSourceName()
		return nil
	case feedbackrecord.FieldFieldLabel:
		m.ClearFieldLabel()
		return nil
	case feedbackrecord.FieldValueText:
		m.ClearValueText()
		return nil
	case feedbackrecord.FieldValueNumber:
		m.ClearValueNumber()
		return nil
	case feedbackrecord.FieldValueBoolean:
		m.ClearValueBoolean()
		return nil
	case feedbackrecord.FieldValueDate:
		m.ClearValueDate()
		return nil
	case feedbackrecord.FieldValueJSON:
		m.ClearValueJSON()
		return nil
	case feedbackrecord.FieldMetadata:
		m.ClearMetadata()
		return nil
	case feedbackrecord.FieldLanguage:
		m.ClearLanguage()
		return nil
	case feedbackrecord.FieldSentiment:
		m.ClearSentiment()
		return nil
	case feedbackrecord.FieldSentimentScore:
		m.ClearSentimentScore()
		return nil
	case feedbackrecord.FieldEmotion:
		m.ClearEmotion()
		return nil
	case feedbackrecord.FieldTopics:
		m.ClearTopics()
		return nil
	case feedbackrecord.FieldUserIdentifier:
		m.ClearUserIdentifier()
		return nil
	case feedbackrecord.FieldEmbedding:
		m.ClearEmbedding()
		return nil
	case feedbackrecord.FieldEmbeddingModel:
		m.ClearEmbeddingModel()
		return nil
	}
	return fmt.Errorf("unknown FeedbackRecord nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FeedbackRecordMutation) ResetField(name string) error {
	switch name {
	case feedbackrecord.FieldCollectedAt:
		m.ResetCollectedAt()
		return nil
	case feedbackrecord.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case feedbackrecord.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case feedbackrecord.FieldTenantID:
		m.ResetTenantID()
		return nil
	case feedbackrecord.FieldResponseID:
		m.ResetResponseID()
		return nil
	case feedbackrecord.FieldSourceType:
		m.ResetSourceType()
		return nil
	case feedbackrecord.FieldSourceID:
		m.ResetSourceID()
		return nil
	case feedbackrecord.FieldSourceName:
		m.ResetSourceName()
		return nil
	case feedbackrecord.FieldFieldID:
		m.ResetFieldID()
		return nil
	case feedbackrecord.FieldFieldLabel:
		m.ResetFieldLabel()
		return nil
	case feedbackrecord.FieldFieldType:
		m.ResetFieldType()
		return nil
	case feedbackrecord.FieldValueText:
		m.ResetValueText()
		return nil
	case feedbackrecord.FieldValueNumber:
		m.ResetValueNumber()
		return nil
	case feedbackrecord.FieldValueBoolean:
		m.ResetValueBoolean()
		return nil
	case feedbackrecord.FieldValueDate:
		m.ResetValueDate()
		return nil
	case feedbackrecord.FieldValueJSON:
		m.ResetValueJSON()
		return nil
	case feedbackrecord.FieldMetadata:
		m.ResetMetadata()
		return nil
	case feedbackrecord.FieldLanguage:
		m.ResetLanguage()
		return nil
	case feedbackrecord.FieldSentiment:
		m.ResetSentiment()
		return nil
	case feedbackrecord.FieldSentimentScore:
		m.ResetSentimentScore()
		return nil
	case feedbackrecord.FieldEmotion:
		m.ResetEmotion()
		return nil
	case feedbackrecord.FieldTopics:
		m.ResetTopics()
		return nil
	case feedbackrecord.FieldUserIdentifier:
		m.ResetUserIdentifier()
		return nil
	case feedbackrecord.FieldEmbedding:
		m.ResetEmbedding()
		return nil
	case feedbackrecord.FieldEmbeddingModel:
		m.ResetEmbeddingModel()
		return nil
	}
	return fmt.Errorf("unknown FeedbackRecord field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FeedbackRecordMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FeedbackRecordMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FeedbackRecordMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FeedbackRecordMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FeedbackRecordMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FeedbackRecordMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FeedbackRecordMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown FeedbackRecord unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FeedbackRecordMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown FeedbackRecord edge %s", name)
}
