// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EnrichmentJob is the predicate function for enrichmentjob builders.
type EnrichmentJob func(*sql.Selector)

// FeedbackRecord is the predicate function for feedbackrecord builders.
type FeedbackRecord func(*sql.Selector)
