-- +goose up
-- Language enrichment (ENG-1255): translated copy of an open-text answer plus the
-- target locale it was produced in. Both are server-generated by the async
-- translation worker; they are NULL until a tenant configures a target language and
-- the record is enriched. The original value_text is preserved (embeddings continue
-- to operate on the source-language text).
ALTER TABLE feedback_records ADD COLUMN value_text_translated TEXT;
ALTER TABLE feedback_records ADD COLUMN translation_lang_key VARCHAR(35);

-- +goose down
ALTER TABLE feedback_records DROP COLUMN IF EXISTS translation_lang_key;
ALTER TABLE feedback_records DROP COLUMN IF EXISTS value_text_translated;
