-- +goose up
-- Sentiment enrichment (ENG-1529): polarity classification of open-text feedback.
-- sentiment + sentiment_score are server-generated by the async sentiment worker; both are
-- NULL until a record is enriched (or sentiment is disabled / the record is ineligible).
-- Keep the label set in sync with models.SentimentValue (Go) and the OpenAPI enum.
-- The CHECKs validate each field independently (valid label; score in [-2, 2]); the worker
-- guarantees the label/score pairing -- a SQL CHECK for that would be brittle, esp. "mixed".
ALTER TABLE feedback_records
  ADD COLUMN sentiment VARCHAR(16),
  ADD COLUMN sentiment_score DOUBLE PRECISION,
  ADD CONSTRAINT feedback_records_sentiment_valid CHECK (
    sentiment IS NULL OR sentiment IN
      ('very_negative', 'negative', 'neutral', 'positive', 'very_positive', 'mixed')
  ),
  ADD CONSTRAINT feedback_records_sentiment_score_range CHECK (
    sentiment_score IS NULL OR (sentiment_score >= -2.0 AND sentiment_score <= 2.0)
  );

-- Sentiment is sparse (NULL until enriched) and Hub reads are always tenant-scoped, so a
-- partial composite index serves filter/group-by-sentiment while keeping the index small and
-- the ingestion-path write overhead minimal (NULL rows are not indexed).
CREATE INDEX idx_feedback_records_tenant_sentiment
  ON feedback_records (tenant_id, sentiment) WHERE sentiment IS NOT NULL;

-- +goose down
DROP INDEX IF EXISTS idx_feedback_records_tenant_sentiment;
ALTER TABLE feedback_records
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_score_range,
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_valid,
  DROP COLUMN IF EXISTS sentiment_score,
  DROP COLUMN IF EXISTS sentiment;
