-- +goose NO TRANSACTION
-- +goose up
-- Sentiment enrichment (ENG-1529): polarity classification of open-text feedback.
-- sentiment + sentiment_score are server-generated by the async sentiment worker; both are
-- NULL until a record is enriched (or sentiment is disabled / the record is ineligible).
-- Keep the label set in sync with models.SentimentValue (Go) and the OpenAPI enum.
-- The CHECKs validate each field's domain (valid label; score in [-1, 1], the conventional
-- signed sentiment-polarity range) and that the two are populated together (both set or both
-- NULL). Their *value* relationship (e.g. "very_positive" ~ +1, "mixed" ~ 0) is steered by the
-- classifier prompt, not enforced -- a SQL CHECK pinning
-- label-to-score would be brittle, esp. for "mixed".
--
-- Runs without a transaction (like the other index migrations) so it never holds a long
-- ACCESS EXCLUSIVE lock on feedback_records (the primary, high-write table):
--   * ADD COLUMN of a nullable column with no default is metadata-only (instant).
--   * the CHECKs are added NOT VALID (instant, no scan; immediately enforced for new/updated
--     rows) and VALIDATEd as a separate, auto-committed step that takes only SHARE UPDATE
--     EXCLUSIVE, so reads and writes proceed during the verification scan.
--   * the index is built CONCURRENTLY.
-- Every statement is also RE-RUNNABLE: under NO TRANSACTION each statement auto-commits while
-- goose records the version only at the end, so an interrupted deploy re-runs the whole file —
-- the guards keep that from crash-looping on "already exists".
ALTER TABLE feedback_records
  ADD COLUMN IF NOT EXISTS sentiment VARCHAR(16),
  ADD COLUMN IF NOT EXISTS sentiment_score DOUBLE PRECISION;

ALTER TABLE feedback_records
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_valid;
ALTER TABLE feedback_records
  ADD CONSTRAINT feedback_records_sentiment_valid CHECK (
    sentiment IS NULL OR sentiment IN
      ('very_negative', 'negative', 'neutral', 'positive', 'very_positive', 'mixed')
  ) NOT VALID;

ALTER TABLE feedback_records
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_score_range;
ALTER TABLE feedback_records
  ADD CONSTRAINT feedback_records_sentiment_score_range CHECK (
    sentiment_score IS NULL OR (sentiment_score >= -1.0 AND sentiment_score <= 1.0)
  ) NOT VALID;

-- sentiment and sentiment_score are populated together: both set (enriched) or both NULL (not
-- yet enriched). Defense-in-depth against a half-populated write slipping past the service.
ALTER TABLE feedback_records
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_pairing;
ALTER TABLE feedback_records
  ADD CONSTRAINT feedback_records_sentiment_pairing CHECK (
    (sentiment IS NULL) = (sentiment_score IS NULL)
  ) NOT VALID;

ALTER TABLE feedback_records VALIDATE CONSTRAINT feedback_records_sentiment_valid;
ALTER TABLE feedback_records VALIDATE CONSTRAINT feedback_records_sentiment_score_range;
ALTER TABLE feedback_records VALIDATE CONSTRAINT feedback_records_sentiment_pairing;

-- Sentiment is sparse (NULL until enriched) and Hub reads are always tenant-scoped, so a
-- partial composite index serves filter/group-by-sentiment while keeping the index small and
-- the ingestion-path write overhead minimal (NULL rows are not indexed).
-- DROP-then-CREATE (not IF NOT EXISTS) so a re-run after an interrupted build replaces the
-- INVALID leftover instead of keeping it.
DROP INDEX CONCURRENTLY IF EXISTS idx_feedback_records_tenant_sentiment;
CREATE INDEX CONCURRENTLY idx_feedback_records_tenant_sentiment
  ON feedback_records (tenant_id, sentiment) WHERE sentiment IS NOT NULL;

-- +goose down
DROP INDEX CONCURRENTLY IF EXISTS idx_feedback_records_tenant_sentiment;
ALTER TABLE feedback_records
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_pairing,
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_score_range,
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_valid,
  DROP COLUMN IF EXISTS sentiment_score,
  DROP COLUMN IF EXISTS sentiment;
