-- +goose NO TRANSACTION
-- +goose Up
-- Sentiment enrichment (ENG-1529): polarity classification of open-text feedback.
-- sentiment + sentiment_score are server-generated by the async sentiment worker; both are
-- NULL until a record is enriched (or sentiment is disabled / the record is ineligible).
-- Keep the label set in sync with models.SentimentValue (Go) and the OpenAPI enum.
-- The CHECKs validate each field independently (valid label; score in [-2, 2]). Their
-- relationship (e.g. "positive" ~ +1, "mixed" ~ 0) is steered by the classifier prompt, not
-- enforced here -- a SQL CHECK pinning label-to-score would be brittle, esp. for "mixed".
--
-- Runs without a transaction (like the other index migrations) so it never holds a long
-- ACCESS EXCLUSIVE lock on feedback_records (the primary, high-write table):
--   * ADD COLUMN of a nullable column with no default is metadata-only (instant).
--   * the CHECKs are added NOT VALID (instant, no scan; immediately enforced for new/updated
--     rows) and VALIDATEd as a separate, auto-committed step that takes only SHARE UPDATE
--     EXCLUSIVE, so reads and writes proceed during the verification scan.
--   * the index is built CONCURRENTLY.
ALTER TABLE feedback_records
  ADD COLUMN sentiment VARCHAR(16),
  ADD COLUMN sentiment_score DOUBLE PRECISION;

ALTER TABLE feedback_records
  ADD CONSTRAINT feedback_records_sentiment_valid CHECK (
    sentiment IS NULL OR sentiment IN
      ('very_negative', 'negative', 'neutral', 'positive', 'very_positive', 'mixed')
  ) NOT VALID;

ALTER TABLE feedback_records
  ADD CONSTRAINT feedback_records_sentiment_score_range CHECK (
    sentiment_score IS NULL OR (sentiment_score >= -2.0 AND sentiment_score <= 2.0)
  ) NOT VALID;

ALTER TABLE feedback_records VALIDATE CONSTRAINT feedback_records_sentiment_valid;
ALTER TABLE feedback_records VALIDATE CONSTRAINT feedback_records_sentiment_score_range;

-- Sentiment is sparse (NULL until enriched) and Hub reads are always tenant-scoped, so a
-- partial composite index serves filter/group-by-sentiment while keeping the index small and
-- the ingestion-path write overhead minimal (NULL rows are not indexed).
CREATE INDEX CONCURRENTLY idx_feedback_records_tenant_sentiment
  ON feedback_records (tenant_id, sentiment) WHERE sentiment IS NOT NULL;

-- +goose Down
DROP INDEX CONCURRENTLY IF EXISTS idx_feedback_records_tenant_sentiment;
ALTER TABLE feedback_records
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_score_range,
  DROP CONSTRAINT IF EXISTS feedback_records_sentiment_valid,
  DROP COLUMN IF EXISTS sentiment_score,
  DROP COLUMN IF EXISTS sentiment;
