name: Bug Report
description: Report a bug or unexpected behavior in Formbricks Hub
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us resolve the issue quickly.

  - type: input
    id: version
    attributes:
      label: Formbricks Hub Version
      description: What version of Formbricks Hub are you running?
      placeholder: "e.g., v0.1.0, latest, commit SHA"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running Formbricks Hub?
      options:
        - Docker
        - Docker Compose
        - Kubernetes
        - Binary/Local Development
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Start Hub API with config...
        2. Make API request to...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please paste any relevant logs or error messages.
      placeholder: |
        Paste logs here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information like API keys!)
      placeholder: |
        Environment variables, docker-compose.yml, etc.
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have removed any sensitive information from logs and configuration
          required: true
        - label: I am using the latest version of Formbricks Hub (or have noted my version above)
          required: false

