blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://docs.formbricks.com/store
    about: Check out our comprehensive documentation for guides and references
  - name: 💬 GitHub Discussions
    url: https://github.com/formbricks/store/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/formbricks/store/security/policy
    about: Report security vulnerabilities privately to security@formbricks.com

