// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/hub/apps/hub/internal/ent/enrichmentjob"
	"github.com/formbricks/hub/apps/hub/internal/ent/predicate"
)

// EnrichmentJobUpdate is the builder for updating EnrichmentJob entities.
type EnrichmentJobUpdate struct {
	config
	hooks    []Hook
	mutation *EnrichmentJobMutation
}

// Where appends a list predicates to the EnrichmentJobUpdate builder.
func (_u *EnrichmentJobUpdate) Where(ps ...predicate.EnrichmentJob) *EnrichmentJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobType sets the "job_type" field.
func (_u *EnrichmentJobUpdate) SetJobType(v string) *EnrichmentJobUpdate {
	_u.mutation.SetJobType(v)
	return _u
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (_u *EnrichmentJobUpdate) SetNillableJobType(v *string) *EnrichmentJobUpdate {
	if v != nil {
		_u.SetJobType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnrichmentJobUpdate) SetStatus(v string) *EnrichmentJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnrichmentJobUpdate) SetNillableStatus(v *string) *EnrichmentJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *EnrichmentJobUpdate) SetText(v string) *EnrichmentJobUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *EnrichmentJobUpdate) SetNillableText(v *string) *EnrichmentJobUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *EnrichmentJobUpdate) SetError(v string) *EnrichmentJobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *EnrichmentJobUpdate) SetNillableError(v *string) *EnrichmentJobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *EnrichmentJobUpdate) ClearError() *EnrichmentJobUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EnrichmentJobUpdate) SetAttempts(v int) *EnrichmentJobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EnrichmentJobUpdate) SetNillableAttempts(v *int) *EnrichmentJobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EnrichmentJobUpdate) AddAttempts(v int) *EnrichmentJobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *EnrichmentJobUpdate) SetProcessedAt(v time.Time) *EnrichmentJobUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *EnrichmentJobUpdate) SetNillableProcessedAt(v *time.Time) *EnrichmentJobUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *EnrichmentJobUpdate) ClearProcessedAt() *EnrichmentJobUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// Mutation returns the EnrichmentJobMutation object of the builder.
func (_u *EnrichmentJobUpdate) Mutation() *EnrichmentJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnrichmentJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrichmentJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnrichmentJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrichmentJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrichmentJobUpdate) check() error {
	if _u.mutation.ExperienceCleared() && len(_u.mutation.ExperienceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnrichmentJob.experience"`)
	}
	return nil
}

func (_u *EnrichmentJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrichmentjob.Table, enrichmentjob.Columns, sqlgraph.NewFieldSpec(enrichmentjob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobType(); ok {
		_spec.SetField(enrichmentjob.FieldJobType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enrichmentjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(enrichmentjob.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(enrichmentjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(enrichmentjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(enrichmentjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(enrichmentjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(enrichmentjob.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(enrichmentjob.FieldProcessedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrichmentjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnrichmentJobUpdateOne is the builder for updating a single EnrichmentJob entity.
type EnrichmentJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnrichmentJobMutation
}

// SetJobType sets the "job_type" field.
func (_u *EnrichmentJobUpdateOne) SetJobType(v string) *EnrichmentJobUpdateOne {
	_u.mutation.SetJobType(v)
	return _u
}

// SetNillableJobType sets the "job_type" field if the given value is not nil.
func (_u *EnrichmentJobUpdateOne) SetNillableJobType(v *string) *EnrichmentJobUpdateOne {
	if v != nil {
		_u.SetJobType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnrichmentJobUpdateOne) SetStatus(v string) *EnrichmentJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnrichmentJobUpdateOne) SetNillableStatus(v *string) *EnrichmentJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *EnrichmentJobUpdateOne) SetText(v string) *EnrichmentJobUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *EnrichmentJobUpdateOne) SetNillableText(v *string) *EnrichmentJobUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *EnrichmentJobUpdateOne) SetError(v string) *EnrichmentJobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *EnrichmentJobUpdateOne) SetNillableError(v *string) *EnrichmentJobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *EnrichmentJobUpdateOne) ClearError() *EnrichmentJobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *EnrichmentJobUpdateOne) SetAttempts(v int) *EnrichmentJobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *EnrichmentJobUpdateOne) SetNillableAttempts(v *int) *EnrichmentJobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *EnrichmentJobUpdateOne) AddAttempts(v int) *EnrichmentJobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *EnrichmentJobUpdateOne) SetProcessedAt(v time.Time) *EnrichmentJobUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *EnrichmentJobUpdateOne) SetNillableProcessedAt(v *time.Time) *EnrichmentJobUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *EnrichmentJobUpdateOne) ClearProcessedAt() *EnrichmentJobUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// Mutation returns the EnrichmentJobMutation object of the builder.
func (_u *EnrichmentJobUpdateOne) Mutation() *EnrichmentJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the EnrichmentJobUpdate builder.
func (_u *EnrichmentJobUpdateOne) Where(ps ...predicate.EnrichmentJob) *EnrichmentJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnrichmentJobUpdateOne) Select(field string, fields ...string) *EnrichmentJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnrichmentJob entity.
func (_u *EnrichmentJobUpdateOne) Save(ctx context.Context) (*EnrichmentJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnrichmentJobUpdateOne) SaveX(ctx context.Context) *EnrichmentJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnrichmentJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnrichmentJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnrichmentJobUpdateOne) check() error {
	if _u.mutation.ExperienceCleared() && len(_u.mutation.ExperienceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnrichmentJob.experience"`)
	}
	return nil
}

func (_u *EnrichmentJobUpdateOne) sqlSave(ctx context.Context) (_node *EnrichmentJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enrichmentjob.Table, enrichmentjob.Columns, sqlgraph.NewFieldSpec(enrichmentjob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnrichmentJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enrichmentjob.FieldID)
		for _, f := range fields {
			if !enrichmentjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enrichmentjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobType(); ok {
		_spec.SetField(enrichmentjob.FieldJobType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enrichmentjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(enrichmentjob.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(enrichmentjob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(enrichmentjob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(enrichmentjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(enrichmentjob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(enrichmentjob.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(enrichmentjob.FieldProcessedAt, field.TypeTime)
	}
	_node = &EnrichmentJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enrichmentjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
