// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/hub/apps/hub/internal/ent/experiencedata"
	"github.com/formbricks/hub/apps/hub/internal/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ExperienceDataUpdate is the builder for updating ExperienceData entities.
type ExperienceDataUpdate struct {
	config
	hooks    []Hook
	mutation *ExperienceDataMutation
}

// Where appends a list predicates to the ExperienceDataUpdate builder.
func (_u *ExperienceDataUpdate) Where(ps ...predicate.ExperienceData) *ExperienceDataUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCollectedAt sets the "collected_at" field.
func (_u *ExperienceDataUpdate) SetCollectedAt(v time.Time) *ExperienceDataUpdate {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableCollectedAt(v *time.Time) *ExperienceDataUpdate {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExperienceDataUpdate) SetUpdatedAt(v time.Time) *ExperienceDataUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ExperienceDataUpdate) SetTenantID(v string) *ExperienceDataUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableTenantID(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ExperienceDataUpdate) ClearTenantID() *ExperienceDataUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetResponseID sets the "response_id" field.
func (_u *ExperienceDataUpdate) SetResponseID(v string) *ExperienceDataUpdate {
	_u.mutation.SetResponseID(v)
	return _u
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableResponseID(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetResponseID(*v)
	}
	return _u
}

// ClearResponseID clears the value of the "response_id" field.
func (_u *ExperienceDataUpdate) ClearResponseID() *ExperienceDataUpdate {
	_u.mutation.ClearResponseID()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ExperienceDataUpdate) SetSourceType(v string) *ExperienceDataUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableSourceType(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ExperienceDataUpdate) SetSourceID(v string) *ExperienceDataUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableSourceID(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ExperienceDataUpdate) ClearSourceID() *ExperienceDataUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ExperienceDataUpdate) SetSourceName(v string) *ExperienceDataUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableSourceName(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ExperienceDataUpdate) ClearSourceName() *ExperienceDataUpdate {
	_u.mutation.ClearSourceName()
	return _u
}

// SetFieldID sets the "field_id" field.
func (_u *ExperienceDataUpdate) SetFieldID(v string) *ExperienceDataUpdate {
	_u.mutation.SetFieldID(v)
	return _u
}

// SetNillableFieldID sets the "field_id" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableFieldID(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetFieldID(*v)
	}
	return _u
}

// SetFieldLabel sets the "field_label" field.
func (_u *ExperienceDataUpdate) SetFieldLabel(v string) *ExperienceDataUpdate {
	_u.mutation.SetFieldLabel(v)
	return _u
}

// SetNillableFieldLabel sets the "field_label" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableFieldLabel(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetFieldLabel(*v)
	}
	return _u
}

// ClearFieldLabel clears the value of the "field_label" field.
func (_u *ExperienceDataUpdate) ClearFieldLabel() *ExperienceDataUpdate {
	_u.mutation.ClearFieldLabel()
	return _u
}

// SetFieldType sets the "field_type" field.
func (_u *ExperienceDataUpdate) SetFieldType(v string) *ExperienceDataUpdate {
	_u.mutation.SetFieldType(v)
	return _u
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableFieldType(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetFieldType(*v)
	}
	return _u
}

// SetValueText sets the "value_text" field.
func (_u *ExperienceDataUpdate) SetValueText(v string) *ExperienceDataUpdate {
	_u.mutation.SetValueText(v)
	return _u
}

// SetNillableValueText sets the "value_text" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableValueText(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetValueText(*v)
	}
	return _u
}

// ClearValueText clears the value of the "value_text" field.
func (_u *ExperienceDataUpdate) ClearValueText() *ExperienceDataUpdate {
	_u.mutation.ClearValueText()
	return _u
}

// SetValueNumber sets the "value_number" field.
func (_u *ExperienceDataUpdate) SetValueNumber(v float64) *ExperienceDataUpdate {
	_u.mutation.ResetValueNumber()
	_u.mutation.SetValueNumber(v)
	return _u
}

// SetNillableValueNumber sets the "value_number" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableValueNumber(v *float64) *ExperienceDataUpdate {
	if v != nil {
		_u.SetValueNumber(*v)
	}
	return _u
}

// AddValueNumber adds value to the "value_number" field.
func (_u *ExperienceDataUpdate) AddValueNumber(v float64) *ExperienceDataUpdate {
	_u.mutation.AddValueNumber(v)
	return _u
}

// ClearValueNumber clears the value of the "value_number" field.
func (_u *ExperienceDataUpdate) ClearValueNumber() *ExperienceDataUpdate {
	_u.mutation.ClearValueNumber()
	return _u
}

// SetValueBoolean sets the "value_boolean" field.
func (_u *ExperienceDataUpdate) SetValueBoolean(v bool) *ExperienceDataUpdate {
	_u.mutation.SetValueBoolean(v)
	return _u
}

// SetNillableValueBoolean sets the "value_boolean" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableValueBoolean(v *bool) *ExperienceDataUpdate {
	if v != nil {
		_u.SetValueBoolean(*v)
	}
	return _u
}

// ClearValueBoolean clears the value of the "value_boolean" field.
func (_u *ExperienceDataUpdate) ClearValueBoolean() *ExperienceDataUpdate {
	_u.mutation.ClearValueBoolean()
	return _u
}

// SetValueDate sets the "value_date" field.
func (_u *ExperienceDataUpdate) SetValueDate(v time.Time) *ExperienceDataUpdate {
	_u.mutation.SetValueDate(v)
	return _u
}

// SetNillableValueDate sets the "value_date" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableValueDate(v *time.Time) *ExperienceDataUpdate {
	if v != nil {
		_u.SetValueDate(*v)
	}
	return _u
}

// ClearValueDate clears the value of the "value_date" field.
func (_u *ExperienceDataUpdate) ClearValueDate() *ExperienceDataUpdate {
	_u.mutation.ClearValueDate()
	return _u
}

// SetValueJSON sets the "value_json" field.
func (_u *ExperienceDataUpdate) SetValueJSON(v map[string]interface{}) *ExperienceDataUpdate {
	_u.mutation.SetValueJSON(v)
	return _u
}

// ClearValueJSON clears the value of the "value_json" field.
func (_u *ExperienceDataUpdate) ClearValueJSON() *ExperienceDataUpdate {
	_u.mutation.ClearValueJSON()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ExperienceDataUpdate) SetMetadata(v map[string]interface{}) *ExperienceDataUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ExperienceDataUpdate) ClearMetadata() *ExperienceDataUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *ExperienceDataUpdate) SetLanguage(v string) *ExperienceDataUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableLanguage(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *ExperienceDataUpdate) ClearLanguage() *ExperienceDataUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// SetSentiment sets the "sentiment" field.
func (_u *ExperienceDataUpdate) SetSentiment(v string) *ExperienceDataUpdate {
	_u.mutation.SetSentiment(v)
	return _u
}

// SetNillableSentiment sets the "sentiment" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableSentiment(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetSentiment(*v)
	}
	return _u
}

// ClearSentiment clears the value of the "sentiment" field.
func (_u *ExperienceDataUpdate) ClearSentiment() *ExperienceDataUpdate {
	_u.mutation.ClearSentiment()
	return _u
}

// SetSentimentScore sets the "sentiment_score" field.
func (_u *ExperienceDataUpdate) SetSentimentScore(v float64) *ExperienceDataUpdate {
	_u.mutation.ResetSentimentScore()
	_u.mutation.SetSentimentScore(v)
	return _u
}

// SetNillableSentimentScore sets the "sentiment_score" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableSentimentScore(v *float64) *ExperienceDataUpdate {
	if v != nil {
		_u.SetSentimentScore(*v)
	}
	return _u
}

// AddSentimentScore adds value to the "sentiment_score" field.
func (_u *ExperienceDataUpdate) AddSentimentScore(v float64) *ExperienceDataUpdate {
	_u.mutation.AddSentimentScore(v)
	return _u
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (_u *ExperienceDataUpdate) ClearSentimentScore() *ExperienceDataUpdate {
	_u.mutation.ClearSentimentScore()
	return _u
}

// SetEmotion sets the "emotion" field.
func (_u *ExperienceDataUpdate) SetEmotion(v string) *ExperienceDataUpdate {
	_u.mutation.SetEmotion(v)
	return _u
}

// SetNillableEmotion sets the "emotion" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableEmotion(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetEmotion(*v)
	}
	return _u
}

// ClearEmotion clears the value of the "emotion" field.
func (_u *ExperienceDataUpdate) ClearEmotion() *ExperienceDataUpdate {
	_u.mutation.ClearEmotion()
	return _u
}

// SetTopics sets the "topics" field.
func (_u *ExperienceDataUpdate) SetTopics(v []string) *ExperienceDataUpdate {
	_u.mutation.SetTopics(v)
	return _u
}

// AppendTopics appends value to the "topics" field.
func (_u *ExperienceDataUpdate) AppendTopics(v []string) *ExperienceDataUpdate {
	_u.mutation.AppendTopics(v)
	return _u
}

// ClearTopics clears the value of the "topics" field.
func (_u *ExperienceDataUpdate) ClearTopics() *ExperienceDataUpdate {
	_u.mutation.ClearTopics()
	return _u
}

// SetUserIdentifier sets the "user_identifier" field.
func (_u *ExperienceDataUpdate) SetUserIdentifier(v string) *ExperienceDataUpdate {
	_u.mutation.SetUserIdentifier(v)
	return _u
}

// SetNillableUserIdentifier sets the "user_identifier" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableUserIdentifier(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetUserIdentifier(*v)
	}
	return _u
}

// ClearUserIdentifier clears the value of the "user_identifier" field.
func (_u *ExperienceDataUpdate) ClearUserIdentifier() *ExperienceDataUpdate {
	_u.mutation.ClearUserIdentifier()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *ExperienceDataUpdate) SetEmbedding(v pgvector.Vector) *ExperienceDataUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableEmbedding(v *pgvector.Vector) *ExperienceDataUpdate {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *ExperienceDataUpdate) ClearEmbedding() *ExperienceDataUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *ExperienceDataUpdate) SetEmbeddingModel(v string) *ExperienceDataUpdate {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *ExperienceDataUpdate) SetNillableEmbeddingModel(v *string) *ExperienceDataUpdate {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (_u *ExperienceDataUpdate) ClearEmbeddingModel() *ExperienceDataUpdate {
	_u.mutation.ClearEmbeddingModel()
	return _u
}

// Mutation returns the ExperienceDataMutation object of the builder.
func (_u *ExperienceDataUpdate) Mutation() *ExperienceDataMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExperienceDataUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceDataUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExperienceDataUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceDataUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExperienceDataUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := experiencedata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceDataUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := experiencedata.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseID(); ok {
		if err := experiencedata.ResponseIDValidator(v); err != nil {
			return &ValidationError{Name: "response_id", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.response_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := experiencedata.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldID(); ok {
		if err := experiencedata.FieldIDValidator(v); err != nil {
			return &ValidationError{Name: "field_id", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.field_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldType(); ok {
		if err := experiencedata.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.field_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := experiencedata.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.language": %w`, err)}
		}
	}
	return nil
}

func (_u *ExperienceDataUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experiencedata.Table, experiencedata.Columns, sqlgraph.NewFieldSpec(experiencedata.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(experiencedata.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(experiencedata.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(experiencedata.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(experiencedata.FieldTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseID(); ok {
		_spec.SetField(experiencedata.FieldResponseID, field.TypeString, value)
	}
	if _u.mutation.ResponseIDCleared() {
		_spec.ClearField(experiencedata.FieldResponseID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(experiencedata.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(experiencedata.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(experiencedata.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(experiencedata.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(experiencedata.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.FieldID(); ok {
		_spec.SetField(experiencedata.FieldFieldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FieldLabel(); ok {
		_spec.SetField(experiencedata.FieldFieldLabel, field.TypeString, value)
	}
	if _u.mutation.FieldLabelCleared() {
		_spec.ClearField(experiencedata.FieldFieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.FieldType(); ok {
		_spec.SetField(experiencedata.FieldFieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueText(); ok {
		_spec.SetField(experiencedata.FieldValueText, field.TypeString, value)
	}
	if _u.mutation.ValueTextCleared() {
		_spec.ClearField(experiencedata.FieldValueText, field.TypeString)
	}
	if value, ok := _u.mutation.ValueNumber(); ok {
		_spec.SetField(experiencedata.FieldValueNumber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValueNumber(); ok {
		_spec.AddField(experiencedata.FieldValueNumber, field.TypeFloat64, value)
	}
	if _u.mutation.ValueNumberCleared() {
		_spec.ClearField(experiencedata.FieldValueNumber, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ValueBoolean(); ok {
		_spec.SetField(experiencedata.FieldValueBoolean, field.TypeBool, value)
	}
	if _u.mutation.ValueBooleanCleared() {
		_spec.ClearField(experiencedata.FieldValueBoolean, field.TypeBool)
	}
	if value, ok := _u.mutation.ValueDate(); ok {
		_spec.SetField(experiencedata.FieldValueDate, field.TypeTime, value)
	}
	if _u.mutation.ValueDateCleared() {
		_spec.ClearField(experiencedata.FieldValueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ValueJSON(); ok {
		_spec.SetField(experiencedata.FieldValueJSON, field.TypeJSON, value)
	}
	if _u.mutation.ValueJSONCleared() {
		_spec.ClearField(experiencedata.FieldValueJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(experiencedata.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(experiencedata.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(experiencedata.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(experiencedata.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.Sentiment(); ok {
		_spec.SetField(experiencedata.FieldSentiment, field.TypeString, value)
	}
	if _u.mutation.SentimentCleared() {
		_spec.ClearField(experiencedata.FieldSentiment, field.TypeString)
	}
	if value, ok := _u.mutation.SentimentScore(); ok {
		_spec.SetField(experiencedata.FieldSentimentScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSentimentScore(); ok {
		_spec.AddField(experiencedata.FieldSentimentScore, field.TypeFloat64, value)
	}
	if _u.mutation.SentimentScoreCleared() {
		_spec.ClearField(experiencedata.FieldSentimentScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Emotion(); ok {
		_spec.SetField(experiencedata.FieldEmotion, field.TypeString, value)
	}
	if _u.mutation.EmotionCleared() {
		_spec.ClearField(experiencedata.FieldEmotion, field.TypeString)
	}
	if value, ok := _u.mutation.Topics(); ok {
		_spec.SetField(experiencedata.FieldTopics, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTopics(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, experiencedata.FieldTopics, value)
		})
	}
	if _u.mutation.TopicsCleared() {
		_spec.ClearField(experiencedata.FieldTopics, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserIdentifier(); ok {
		_spec.SetField(experiencedata.FieldUserIdentifier, field.TypeString, value)
	}
	if _u.mutation.UserIdentifierCleared() {
		_spec.ClearField(experiencedata.FieldUserIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(experiencedata.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(experiencedata.FieldEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(experiencedata.FieldEmbeddingModel, field.TypeString, value)
	}
	if _u.mutation.EmbeddingModelCleared() {
		_spec.ClearField(experiencedata.FieldEmbeddingModel, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experiencedata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExperienceDataUpdateOne is the builder for updating a single ExperienceData entity.
type ExperienceDataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExperienceDataMutation
}

// SetCollectedAt sets the "collected_at" field.
func (_u *ExperienceDataUpdateOne) SetCollectedAt(v time.Time) *ExperienceDataUpdateOne {
	_u.mutation.SetCollectedAt(v)
	return _u
}

// SetNillableCollectedAt sets the "collected_at" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableCollectedAt(v *time.Time) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetCollectedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExperienceDataUpdateOne) SetUpdatedAt(v time.Time) *ExperienceDataUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ExperienceDataUpdateOne) SetTenantID(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableTenantID(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *ExperienceDataUpdateOne) ClearTenantID() *ExperienceDataUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetResponseID sets the "response_id" field.
func (_u *ExperienceDataUpdateOne) SetResponseID(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetResponseID(v)
	return _u
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableResponseID(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetResponseID(*v)
	}
	return _u
}

// ClearResponseID clears the value of the "response_id" field.
func (_u *ExperienceDataUpdateOne) ClearResponseID() *ExperienceDataUpdateOne {
	_u.mutation.ClearResponseID()
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ExperienceDataUpdateOne) SetSourceType(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableSourceType(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ExperienceDataUpdateOne) SetSourceID(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableSourceID(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *ExperienceDataUpdateOne) ClearSourceID() *ExperienceDataUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ExperienceDataUpdateOne) SetSourceName(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableSourceName(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ExperienceDataUpdateOne) ClearSourceName() *ExperienceDataUpdateOne {
	_u.mutation.ClearSourceName()
	return _u
}

// SetFieldID sets the "field_id" field.
func (_u *ExperienceDataUpdateOne) SetFieldID(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetFieldID(v)
	return _u
}

// SetNillableFieldID sets the "field_id" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableFieldID(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetFieldID(*v)
	}
	return _u
}

// SetFieldLabel sets the "field_label" field.
func (_u *ExperienceDataUpdateOne) SetFieldLabel(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetFieldLabel(v)
	return _u
}

// SetNillableFieldLabel sets the "field_label" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableFieldLabel(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetFieldLabel(*v)
	}
	return _u
}

// ClearFieldLabel clears the value of the "field_label" field.
func (_u *ExperienceDataUpdateOne) ClearFieldLabel() *ExperienceDataUpdateOne {
	_u.mutation.ClearFieldLabel()
	return _u
}

// SetFieldType sets the "field_type" field.
func (_u *ExperienceDataUpdateOne) SetFieldType(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetFieldType(v)
	return _u
}

// SetNillableFieldType sets the "field_type" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableFieldType(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetFieldType(*v)
	}
	return _u
}

// SetValueText sets the "value_text" field.
func (_u *ExperienceDataUpdateOne) SetValueText(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetValueText(v)
	return _u
}

// SetNillableValueText sets the "value_text" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableValueText(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetValueText(*v)
	}
	return _u
}

// ClearValueText clears the value of the "value_text" field.
func (_u *ExperienceDataUpdateOne) ClearValueText() *ExperienceDataUpdateOne {
	_u.mutation.ClearValueText()
	return _u
}

// SetValueNumber sets the "value_number" field.
func (_u *ExperienceDataUpdateOne) SetValueNumber(v float64) *ExperienceDataUpdateOne {
	_u.mutation.ResetValueNumber()
	_u.mutation.SetValueNumber(v)
	return _u
}

// SetNillableValueNumber sets the "value_number" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableValueNumber(v *float64) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetValueNumber(*v)
	}
	return _u
}

// AddValueNumber adds value to the "value_number" field.
func (_u *ExperienceDataUpdateOne) AddValueNumber(v float64) *ExperienceDataUpdateOne {
	_u.mutation.AddValueNumber(v)
	return _u
}

// ClearValueNumber clears the value of the "value_number" field.
func (_u *ExperienceDataUpdateOne) ClearValueNumber() *ExperienceDataUpdateOne {
	_u.mutation.ClearValueNumber()
	return _u
}

// SetValueBoolean sets the "value_boolean" field.
func (_u *ExperienceDataUpdateOne) SetValueBoolean(v bool) *ExperienceDataUpdateOne {
	_u.mutation.SetValueBoolean(v)
	return _u
}

// SetNillableValueBoolean sets the "value_boolean" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableValueBoolean(v *bool) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetValueBoolean(*v)
	}
	return _u
}

// ClearValueBoolean clears the value of the "value_boolean" field.
func (_u *ExperienceDataUpdateOne) ClearValueBoolean() *ExperienceDataUpdateOne {
	_u.mutation.ClearValueBoolean()
	return _u
}

// SetValueDate sets the "value_date" field.
func (_u *ExperienceDataUpdateOne) SetValueDate(v time.Time) *ExperienceDataUpdateOne {
	_u.mutation.SetValueDate(v)
	return _u
}

// SetNillableValueDate sets the "value_date" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableValueDate(v *time.Time) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetValueDate(*v)
	}
	return _u
}

// ClearValueDate clears the value of the "value_date" field.
func (_u *ExperienceDataUpdateOne) ClearValueDate() *ExperienceDataUpdateOne {
	_u.mutation.ClearValueDate()
	return _u
}

// SetValueJSON sets the "value_json" field.
func (_u *ExperienceDataUpdateOne) SetValueJSON(v map[string]interface{}) *ExperienceDataUpdateOne {
	_u.mutation.SetValueJSON(v)
	return _u
}

// ClearValueJSON clears the value of the "value_json" field.
func (_u *ExperienceDataUpdateOne) ClearValueJSON() *ExperienceDataUpdateOne {
	_u.mutation.ClearValueJSON()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ExperienceDataUpdateOne) SetMetadata(v map[string]interface{}) *ExperienceDataUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ExperienceDataUpdateOne) ClearMetadata() *ExperienceDataUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *ExperienceDataUpdateOne) SetLanguage(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableLanguage(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *ExperienceDataUpdateOne) ClearLanguage() *ExperienceDataUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// SetSentiment sets the "sentiment" field.
func (_u *ExperienceDataUpdateOne) SetSentiment(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetSentiment(v)
	return _u
}

// SetNillableSentiment sets the "sentiment" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableSentiment(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetSentiment(*v)
	}
	return _u
}

// ClearSentiment clears the value of the "sentiment" field.
func (_u *ExperienceDataUpdateOne) ClearSentiment() *ExperienceDataUpdateOne {
	_u.mutation.ClearSentiment()
	return _u
}

// SetSentimentScore sets the "sentiment_score" field.
func (_u *ExperienceDataUpdateOne) SetSentimentScore(v float64) *ExperienceDataUpdateOne {
	_u.mutation.ResetSentimentScore()
	_u.mutation.SetSentimentScore(v)
	return _u
}

// SetNillableSentimentScore sets the "sentiment_score" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableSentimentScore(v *float64) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetSentimentScore(*v)
	}
	return _u
}

// AddSentimentScore adds value to the "sentiment_score" field.
func (_u *ExperienceDataUpdateOne) AddSentimentScore(v float64) *ExperienceDataUpdateOne {
	_u.mutation.AddSentimentScore(v)
	return _u
}

// ClearSentimentScore clears the value of the "sentiment_score" field.
func (_u *ExperienceDataUpdateOne) ClearSentimentScore() *ExperienceDataUpdateOne {
	_u.mutation.ClearSentimentScore()
	return _u
}

// SetEmotion sets the "emotion" field.
func (_u *ExperienceDataUpdateOne) SetEmotion(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetEmotion(v)
	return _u
}

// SetNillableEmotion sets the "emotion" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableEmotion(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetEmotion(*v)
	}
	return _u
}

// ClearEmotion clears the value of the "emotion" field.
func (_u *ExperienceDataUpdateOne) ClearEmotion() *ExperienceDataUpdateOne {
	_u.mutation.ClearEmotion()
	return _u
}

// SetTopics sets the "topics" field.
func (_u *ExperienceDataUpdateOne) SetTopics(v []string) *ExperienceDataUpdateOne {
	_u.mutation.SetTopics(v)
	return _u
}

// AppendTopics appends value to the "topics" field.
func (_u *ExperienceDataUpdateOne) AppendTopics(v []string) *ExperienceDataUpdateOne {
	_u.mutation.AppendTopics(v)
	return _u
}

// ClearTopics clears the value of the "topics" field.
func (_u *ExperienceDataUpdateOne) ClearTopics() *ExperienceDataUpdateOne {
	_u.mutation.ClearTopics()
	return _u
}

// SetUserIdentifier sets the "user_identifier" field.
func (_u *ExperienceDataUpdateOne) SetUserIdentifier(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetUserIdentifier(v)
	return _u
}

// SetNillableUserIdentifier sets the "user_identifier" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableUserIdentifier(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetUserIdentifier(*v)
	}
	return _u
}

// ClearUserIdentifier clears the value of the "user_identifier" field.
func (_u *ExperienceDataUpdateOne) ClearUserIdentifier() *ExperienceDataUpdateOne {
	_u.mutation.ClearUserIdentifier()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *ExperienceDataUpdateOne) SetEmbedding(v pgvector.Vector) *ExperienceDataUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableEmbedding(v *pgvector.Vector) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *ExperienceDataUpdateOne) ClearEmbedding() *ExperienceDataUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetEmbeddingModel sets the "embedding_model" field.
func (_u *ExperienceDataUpdateOne) SetEmbeddingModel(v string) *ExperienceDataUpdateOne {
	_u.mutation.SetEmbeddingModel(v)
	return _u
}

// SetNillableEmbeddingModel sets the "embedding_model" field if the given value is not nil.
func (_u *ExperienceDataUpdateOne) SetNillableEmbeddingModel(v *string) *ExperienceDataUpdateOne {
	if v != nil {
		_u.SetEmbeddingModel(*v)
	}
	return _u
}

// ClearEmbeddingModel clears the value of the "embedding_model" field.
func (_u *ExperienceDataUpdateOne) ClearEmbeddingModel() *ExperienceDataUpdateOne {
	_u.mutation.ClearEmbeddingModel()
	return _u
}

// Mutation returns the ExperienceDataMutation object of the builder.
func (_u *ExperienceDataUpdateOne) Mutation() *ExperienceDataMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExperienceDataUpdate builder.
func (_u *ExperienceDataUpdateOne) Where(ps ...predicate.ExperienceData) *ExperienceDataUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExperienceDataUpdateOne) Select(field string, fields ...string) *ExperienceDataUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExperienceData entity.
func (_u *ExperienceDataUpdateOne) Save(ctx context.Context) (*ExperienceData, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExperienceDataUpdateOne) SaveX(ctx context.Context) *ExperienceData {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExperienceDataUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExperienceDataUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExperienceDataUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := experiencedata.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExperienceDataUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := experiencedata.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseID(); ok {
		if err := experiencedata.ResponseIDValidator(v); err != nil {
			return &ValidationError{Name: "response_id", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.response_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := experiencedata.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldID(); ok {
		if err := experiencedata.FieldIDValidator(v); err != nil {
			return &ValidationError{Name: "field_id", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.field_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FieldType(); ok {
		if err := experiencedata.FieldTypeValidator(v); err != nil {
			return &ValidationError{Name: "field_type", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.field_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := experiencedata.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "ExperienceData.language": %w`, err)}
		}
	}
	return nil
}

func (_u *ExperienceDataUpdateOne) sqlSave(ctx context.Context) (_node *ExperienceData, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(experiencedata.Table, experiencedata.Columns, sqlgraph.NewFieldSpec(experiencedata.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExperienceData.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, experiencedata.FieldID)
		for _, f := range fields {
			if !experiencedata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != experiencedata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CollectedAt(); ok {
		_spec.SetField(experiencedata.FieldCollectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(experiencedata.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(experiencedata.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(experiencedata.FieldTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseID(); ok {
		_spec.SetField(experiencedata.FieldResponseID, field.TypeString, value)
	}
	if _u.mutation.ResponseIDCleared() {
		_spec.ClearField(experiencedata.FieldResponseID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(experiencedata.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(experiencedata.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(experiencedata.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(experiencedata.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(experiencedata.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.FieldID(); ok {
		_spec.SetField(experiencedata.FieldFieldID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FieldLabel(); ok {
		_spec.SetField(experiencedata.FieldFieldLabel, field.TypeString, value)
	}
	if _u.mutation.FieldLabelCleared() {
		_spec.ClearField(experiencedata.FieldFieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.FieldType(); ok {
		_spec.SetField(experiencedata.FieldFieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueText(); ok {
		_spec.SetField(experiencedata.FieldValueText, field.TypeString, value)
	}
	if _u.mutation.ValueTextCleared() {
		_spec.ClearField(experiencedata.FieldValueText, field.TypeString)
	}
	if value, ok := _u.mutation.ValueNumber(); ok {
		_spec.SetField(experiencedata.FieldValueNumber, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedValueNumber(); ok {
		_spec.AddField(experiencedata.FieldValueNumber, field.TypeFloat64, value)
	}
	if _u.mutation.ValueNumberCleared() {
		_spec.ClearField(experiencedata.FieldValueNumber, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ValueBoolean(); ok {
		_spec.SetField(experiencedata.FieldValueBoolean, field.TypeBool, value)
	}
	if _u.mutation.ValueBooleanCleared() {
		_spec.ClearField(experiencedata.FieldValueBoolean, field.TypeBool)
	}
	if value, ok := _u.mutation.ValueDate(); ok {
		_spec.SetField(experiencedata.FieldValueDate, field.TypeTime, value)
	}
	if _u.mutation.ValueDateCleared() {
		_spec.ClearField(experiencedata.FieldValueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ValueJSON(); ok {
		_spec.SetField(experiencedata.FieldValueJSON, field.TypeJSON, value)
	}
	if _u.mutation.ValueJSONCleared() {
		_spec.ClearField(experiencedata.FieldValueJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(experiencedata.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(experiencedata.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(experiencedata.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(experiencedata.FieldLanguage, field.TypeString)
	}
	if value, ok := _u.mutation.Sentiment(); ok {
		_spec.SetField(experiencedata.FieldSentiment, field.TypeString, value)
	}
	if _u.mutation.SentimentCleared() {
		_spec.ClearField(experiencedata.FieldSentiment, field.TypeString)
	}
	if value, ok := _u.mutation.SentimentScore(); ok {
		_spec.SetField(experiencedata.FieldSentimentScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSentimentScore(); ok {
		_spec.AddField(experiencedata.FieldSentimentScore, field.TypeFloat64, value)
	}
	if _u.mutation.SentimentScoreCleared() {
		_spec.ClearField(experiencedata.FieldSentimentScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Emotion(); ok {
		_spec.SetField(experiencedata.FieldEmotion, field.TypeString, value)
	}
	if _u.mutation.EmotionCleared() {
		_spec.ClearField(experiencedata.FieldEmotion, field.TypeString)
	}
	if value, ok := _u.mutation.Topics(); ok {
		_spec.SetField(experiencedata.FieldTopics, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTopics(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, experiencedata.FieldTopics, value)
		})
	}
	if _u.mutation.TopicsCleared() {
		_spec.ClearField(experiencedata.FieldTopics, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserIdentifier(); ok {
		_spec.SetField(experiencedata.FieldUserIdentifier, field.TypeString, value)
	}
	if _u.mutation.UserIdentifierCleared() {
		_spec.ClearField(experiencedata.FieldUserIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(experiencedata.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(experiencedata.FieldEmbedding, field.TypeOther)
	}
	if value, ok := _u.mutation.EmbeddingModel(); ok {
		_spec.SetField(experiencedata.FieldEmbeddingModel, field.TypeString, value)
	}
	if _u.mutation.EmbeddingModelCleared() {
		_spec.ClearField(experiencedata.FieldEmbeddingModel, field.TypeString)
	}
	_node = &ExperienceData{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{experiencedata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
