// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/formbricks/hub/apps/hub/internal/ent/experiencedata"
	"github.com/formbricks/hub/apps/hub/internal/ent/predicate"
)

// ExperienceDataDelete is the builder for deleting a ExperienceData entity.
type ExperienceDataDelete struct {
	config
	hooks    []Hook
	mutation *ExperienceDataMutation
}

// Where appends a list predicates to the ExperienceDataDelete builder.
func (_d *ExperienceDataDelete) Where(ps ...predicate.ExperienceData) *ExperienceDataDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExperienceDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExperienceDataDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExperienceDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(experiencedata.Table, sqlgraph.NewFieldSpec(experiencedata.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExperienceDataDeleteOne is the builder for deleting a single ExperienceData entity.
type ExperienceDataDeleteOne struct {
	_d *ExperienceDataDelete
}

// Where appends a list predicates to the ExperienceDataDelete builder.
func (_d *ExperienceDataDeleteOne) Where(ps ...predicate.ExperienceData) *ExperienceDataDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExperienceDataDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{experiencedata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExperienceDataDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
