// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/formbricks/hub/apps/hub/internal/ent/enrichmentjob"
	"github.com/formbricks/hub/apps/hub/internal/ent/feedbackrecord"
	"github.com/formbricks/hub/apps/hub/internal/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	enrichmentjobFields := schema.EnrichmentJob{}.Fields()
	_ = enrichmentjobFields
	// enrichmentjobDescJobType is the schema descriptor for job_type field.
	enrichmentjobDescJobType := enrichmentjobFields[2].Descriptor()
	// enrichmentjob.DefaultJobType holds the default value on creation for the job_type field.
	enrichmentjob.DefaultJobType = enrichmentjobDescJobType.Default.(string)
	// enrichmentjobDescStatus is the schema descriptor for status field.
	enrichmentjobDescStatus := enrichmentjobFields[3].Descriptor()
	// enrichmentjob.DefaultStatus holds the default value on creation for the status field.
	enrichmentjob.DefaultStatus = enrichmentjobDescStatus.Default.(string)
	// enrichmentjobDescAttempts is the schema descriptor for attempts field.
	enrichmentjobDescAttempts := enrichmentjobFields[6].Descriptor()
	// enrichmentjob.DefaultAttempts holds the default value on creation for the attempts field.
	enrichmentjob.DefaultAttempts = enrichmentjobDescAttempts.Default.(int)
	// enrichmentjobDescCreatedAt is the schema descriptor for created_at field.
	enrichmentjobDescCreatedAt := enrichmentjobFields[7].Descriptor()
	// enrichmentjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	enrichmentjob.DefaultCreatedAt = enrichmentjobDescCreatedAt.Default.(func() time.Time)
	// enrichmentjobDescID is the schema descriptor for id field.
	enrichmentjobDescID := enrichmentjobFields[0].Descriptor()
	// enrichmentjob.DefaultID holds the default value on creation for the id field.
	enrichmentjob.DefaultID = enrichmentjobDescID.Default.(func() uuid.UUID)
	feedbackrecordFields := schema.FeedbackRecord{}.Fields()
	_ = feedbackrecordFields
	// feedbackrecordDescCollectedAt is the schema descriptor for collected_at field.
	feedbackrecordDescCollectedAt := feedbackrecordFields[1].Descriptor()
	// feedbackrecord.DefaultCollectedAt holds the default value on creation for the collected_at field.
	feedbackrecord.DefaultCollectedAt = feedbackrecordDescCollectedAt.Default.(func() time.Time)
	// feedbackrecordDescCreatedAt is the schema descriptor for created_at field.
	feedbackrecordDescCreatedAt := feedbackrecordFields[2].Descriptor()
	// feedbackrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	feedbackrecord.DefaultCreatedAt = feedbackrecordDescCreatedAt.Default.(func() time.Time)
	// feedbackrecordDescUpdatedAt is the schema descriptor for updated_at field.
	feedbackrecordDescUpdatedAt := feedbackrecordFields[3].Descriptor()
	// feedbackrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	feedbackrecord.DefaultUpdatedAt = feedbackrecordDescUpdatedAt.Default.(func() time.Time)
	// feedbackrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	feedbackrecord.UpdateDefaultUpdatedAt = feedbackrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// feedbackrecordDescTenantID is the schema descriptor for tenant_id field.
	feedbackrecordDescTenantID := feedbackrecordFields[4].Descriptor()
	// feedbackrecord.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	feedbackrecord.TenantIDValidator = feedbackrecordDescTenantID.Validators[0].(func(string) error)
	// feedbackrecordDescResponseID is the schema descriptor for response_id field.
	feedbackrecordDescResponseID := feedbackrecordFields[5].Descriptor()
	// feedbackrecord.ResponseIDValidator is a validator for the "response_id" field. It is called by the builders before save.
	feedbackrecord.ResponseIDValidator = feedbackrecordDescResponseID.Validators[0].(func(string) error)
	// feedbackrecordDescSourceType is the schema descriptor for source_type field.
	feedbackrecordDescSourceType := feedbackrecordFields[6].Descriptor()
	// feedbackrecord.SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	feedbackrecord.SourceTypeValidator = feedbackrecordDescSourceType.Validators[0].(func(string) error)
	// feedbackrecordDescFieldID is the schema descriptor for field_id field.
	feedbackrecordDescFieldID := feedbackrecordFields[9].Descriptor()
	// feedbackrecord.FieldIDValidator is a validator for the "field_id" field. It is called by the builders before save.
	feedbackrecord.FieldIDValidator = feedbackrecordDescFieldID.Validators[0].(func(string) error)
	// feedbackrecordDescFieldType is the schema descriptor for field_type field.
	feedbackrecordDescFieldType := feedbackrecordFields[11].Descriptor()
	// feedbackrecord.FieldTypeValidator is a validator for the "field_type" field. It is called by the builders before save.
	feedbackrecord.FieldTypeValidator = func() func(string) error {
		validators := feedbackrecordDescFieldType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(field_type string) error {
			for _, fn := range fns {
				if err := fn(field_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// feedbackrecordDescLanguage is the schema descriptor for language field.
	feedbackrecordDescLanguage := feedbackrecordFields[18].Descriptor()
	// feedbackrecord.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	feedbackrecord.LanguageValidator = feedbackrecordDescLanguage.Validators[0].(func(string) error)
	// feedbackrecordDescID is the schema descriptor for id field.
	feedbackrecordDescID := feedbackrecordFields[0].Descriptor()
	// feedbackrecord.DefaultID holds the default value on creation for the id field.
	feedbackrecord.DefaultID = feedbackrecordDescID.Default.(func() uuid.UUID)
}
