// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Tiago Farto",
            "email": "tiago@formbricks.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/feedback-records": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists feedback records with optional filters and pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback Records"
                ],
                "summary": "List feedback records with filters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by tenant ID",
                        "name": "tenant_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by response ID",
                        "name": "response_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source ID",
                        "name": "source_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by field type",
                        "name": "field_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user identifier",
                        "name": "user_identifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by collected_at \u003e= since (ISO 8601 format)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by collected_at \u003c= until (ISO 8601 format)",
                        "name": "until",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to return (max 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListFeedbackRecordsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new feedback record data point",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback Records"
                ],
                "summary": "Create feedback record",
                "parameters": [
                    {
                        "description": "Feedback record data to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateFeedbackRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/FeedbackRecord"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently deletes all feedback record data points matching the specified user_identifier. This endpoint supports GDPR Article 17 (Right to Erasure) requests.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback Records"
                ],
                "summary": "Bulk delete feedback records by user identifier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete all records matching this user identifier",
                        "name": "user_identifier",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by tenant ID (optional, for multi-tenant deployments)",
                        "name": "tenant_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/BulkDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "user_identifier is required",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            }
        },
        "/v1/feedback-records/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Performs vector similarity search on feedback record data using OpenAI embeddings. Only returns text records that have been embedded.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback Records"
                ],
                "summary": "Search feedback records using semantic search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Natural language search query",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of results to return (default 10, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source type",
                        "name": "source_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by collection date (ISO 8601)",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by collection date (ISO 8601)",
                        "name": "until",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SearchFeedbackRecordsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters or missing query",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            }
        },
        "/v1/feedback-records/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a single feedback record data point by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback Records"
                ],
                "summary": "Get a feedback record by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback Record ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FeedbackRecord"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "404": {
                        "description": "Feedback record not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permanently deletes a feedback record data point",
                "tags": [
                    "Feedback Records"
                ],
                "summary": "Delete a feedback record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback Record ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid UUID format",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "404": {
                        "description": "Feedback record not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates specific fields of a feedback record data point",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedback Records"
                ],
                "summary": "Update a feedback record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feedback Record ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateFeedbackRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FeedbackRecord"
                        }
                    },
                    "400": {
                        "description": "Invalid request or UUID format",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    },
                    "404": {
                        "description": "Feedback record not found",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "BulkDeleteResponse": {
            "type": "object",
            "properties": {
                "deleted_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "CreateFeedbackRecordRequest": {
            "type": "object",
            "properties": {
                "collected_at": {
                    "type": "string"
                },
                "field_id": {
                    "type": "string"
                },
                "field_label": {
                    "type": "string"
                },
                "field_type": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "response_id": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "object"
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        },
        "ErrorDetail": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "FeedbackRecord": {
            "type": "object",
            "properties": {
                "collected_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "field_id": {
                    "type": "string"
                },
                "field_label": {
                    "type": "string"
                },
                "field_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "response_id": {
                    "type": "string"
                },
                "source_id": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "object"
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        },
        "ListFeedbackRecordsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/FeedbackRecord"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "ProblemDetails": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ErrorDetail"
                    }
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "SearchFeedbackRecordsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SearchResultItem"
                    }
                }
            }
        },
        "SearchResultItem": {
            "type": "object",
            "properties": {
                "collected_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "field_id": {
                    "type": "string"
                },
                "field_label": {
                    "type": "string"
                },
                "field_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "response_id": {
                    "type": "string"
                },
                "similarity_score": {
                    "type": "number"
                },
                "source_id": {
                    "type": "string"
                },
                "source_name": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "object"
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        },
        "UpdateFeedbackRecordRequest": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object"
                },
                "user_identifier": {
                    "type": "string"
                },
                "value_boolean": {
                    "type": "boolean"
                },
                "value_date": {
                    "type": "string"
                },
                "value_json": {
                    "type": "object"
                },
                "value_number": {
                    "type": "number"
                },
                "value_text": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and your API key.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Formbricks Hub API",
	Description:      "API for managing feedback records collection",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
